build.rs
src/msac.rs

* Update `build.rs` to build and link assembly for aarch64.
* Add asm calls to `msac.rs`.

Setup aarch64 asm

---

Cargo.lock
Cargo.toml
c2rust-lib.rs
src/cpu.rs
src/data.rs
src/lib.rs
src/log.rs
src/picture.rs
src/recon_tmpl_16.rs
src/recon_tmpl_8.rs
tools/dav1d.rs
tools/dav1d_cli_parse.rs
tools/input/annexb.rs
tools/input/input.rs
tools/input/ivf.rs
tools/input/section5.rs
tools/output/md5.rs
tools/output/output.rs
tools/output/y4m2.rs
tools/output/yuv.rs

The following changes are necessary but not sufficient to run on platforms other than Linux. I have a few more fixes in the pipeline but I'd like to land these first to not unduly interfere with #26.

Initial portability fixes

---

src/cdef_tmpl_16.rs
src/cdef_tmpl_8.rs

This is the aarch64 companion to #33.

Add aarch64 assembly for cdef_tmpl_*

---

src/cdf.rs
src/data.rs
src/decode.rs
src/obu.rs
src/picture.rs
src/ref.rs

Deduplicate inline `fn dav1d_ref_inc` to `src/ref.rs`

---

src/tables.rs

With this change, all 790 enabled tests pass on a machine with avx512. I will prioritize getting #74 done so CI will catch such issues going forward.

Fix alignment for dav1d_sgr_x_by_x

---

src/decode.rs

Convert the variables `ts` and `f` from raw pointers to references, and cleanup all the places where we were previously dereferencing them.

decode_b: Convert ts and f variables to references

---

src/decode.rs
src/levels.rs

* Add helper methods to `mv` an `Av1Block` for accessing unnamed fields.

decode_b: Cleanup a chunk of code

---

src/ipred_tmpl_16.rs
src/ipred_tmpl_8.rs
src/x86/ipred.h
src/x86/ipred16_sse.asm
src/x86/ipred_sse.asm
tests/checkasm/ipred.c

Backport x86 asm ipred changes from dav1d 1.2.0

---

src/arm/64/ipred.S
src/arm/ipred.h

Includes improved code for existing ipred functions and indentation/naming fixes. Partially addresses #225

Backport arm asm changes from dav1d 1.2.0

---

c2rust-lib.rs
include/dav1d/common.rs
include/pthread.rs
include/stdio.rs
include/sys/types.rs
src/data.rs
src/decode.rs
src/internal.rs
src/lib.rs
src/mem.rs
src/obu.rs
src/thread_data.rs
src/thread_task.rs
tools/input/annexb.rs
tools/input/ivf.rs
tools/input/section5.rs

Frank's fixes for macOS to enable benchmarking + a few portability fixes of my own.

Fix issues preventing macOS from building and passing tests

---

src/looprestoration_tmpl_16.rs
src/looprestoration_tmpl_8.rs

Add armv7 assembly for wiener_filter

---

src/thread_task.c
src/thread_task.rs

Backports a fix from dav1d 1.2.1

threading: Fix a race on task_thread.init_done

---

src/mc.rs

Intermediate values may exceed u8 range. Use u16 instead. Also modify add to saturating add to avoid possibiliy of overflow (unconfirmed).

Fix overflow issue introduced in 49035f4

---

src/ipred_tmpl_16.rs
src/x86/ipred.h
src/x86/ipred16_sse.asm
src/x86/ipred_sse.asm

Adds SSSE3 version of 16-bit IPRED_Z2 function

Backport x86 assembly code from dav1d 1.2.1

---

src/itx.rs
src/itx_tmpl_16.rs
src/itx_tmpl_8.rs

Addressing comments from @kkysen after #366 was already merged.

Minor cleanup in `itx_tmpl`

---

src/decode.rs

More than just a slight optimization, this also more closely aligns to how the C was written while also being safe and zero overhead.  In C, `pc` is left uninitialized and unused when `t.frame_thread.pass == 2`.  The easiest way to make this safe in Rust was to default/zero initialize in this case and use `pc` normally in the rest of the function, but that has a slight overhead of initializing a `[0u16; 16]`.  This changes it to use an `Option`, more similar to the C, but to avoid `.unwrap()`s, it uses `if let Some(pc) = pc` instead of `if t.frame_thread.pass != 2` in the rest of the function.

`fn decode_sb`: Slightly optimize var `pc`

---

src/decode.rs

The `data`, `sz` slice will be made safe in another PR since it spans many functions.

`fn setup_tile`: Cleanup and make mostly safe

---

src/decode.rs

`fn setup_tile`: Add back comments and line breaks from C

---

src/qm.rs

In preparation for making it safe.

`fn dav1d_init_qm_tables`: Further cleanup

---

include/common/bitdepth.rs
src/looprestoration.rs

Fixes https://github.com/memorysafety/rav1d/pull/379#discussion_r1304680075.

`bd_fn!`: Add bitdepth-dispatching macro

---

include/dav1d/common.rs
include/dav1d/data.rs
src/decode.rs
src/internal.rs

There's still some more things left to clean up, but they're more cross-cutting so I'm saving them until later.

`fn dav1d_submit_frame`: Cleanup mostly

---

src/wedge.rs

This one is trickier, uglier, and has higher overhead, but it should all run at compile-time.

`fn insert_border`: `const`ify

---

src/lib.rs
src/wedge.rs

Finally `src/wedge.rs` is fully safe and fully `const`!

`static dav1d_wedge_masks`: Make safe

---

src/ipred_prepare.rs

After using `bitflags!` for #500, I realized I could use it for #497 instead of rolling my own version (using `bool` bitfields).  So this supercedes #497, but I'm leaving that open so the history doesn't get overly complicated.

`struct Needs`: Use `bitflags!` instead of `bools_bitfield_struct!`

---

src/cpu.rs

This adds `fn CpuFlags::compile_time_detect` for compile-time CPU feature detection for dead code elimination.  `dav1d_get_cpu_flags` does this in `src/cpu.h`, too, but we only transpiled the `SSE2` case, which is the only one enabled by default for the default target.  This was done in C for dead code elimination, so it should be useful for us, too, even though it seems to override the purpose of `fn dav1d_set_cpu_flags_mask` (a `DAV1D_API`).

`fn dav1d_get_cpu_flags`: Add compile-time CPU feature detection 

---

build.rs

`avx` (`avx2`, `avx512`) are only available on `x86_64`, not `x86`, so we don't need to compile them on `x86`, as that'll only take longer to compile and bloat the binaries.
`dav1d` doesn't seem to do this for some reason, but in C, it gates `avx` asm calls behind `x86_64`, as we do, too.
For `ipred16`, `ipred16_avx2` defines a couple constants used by `ipred16_sse`, so we have to compile `ipred16_avx2` on `x86`, still. 
This is presumably a bug, and I'll try to upstream a fix for this.

`build.rs`: Don't compile `avx` asm for `x86`

---

src/lib.rs

We forgot to re-transpile the `goto`-less `dav1d_parse_sequence_header` to remove the `current_block_*` state machine.

`fn rav1d_parse_sequence_header`: get rid of `current_block`

---

src/filmgrain.rs

This also explicitly truncates `ar_lag` to 2 bits (so `ar_lag <= ar_pad`), which it already is when being set, but the compiler can't see that (a `u2` would be appropriate). `ar_lag <= ar_pad` proves all the bounds are in-bounds, but the compiler only sees this when using slicing and iterators.
There are still some bounds checks for the luma code, but that only happens once per inner loop so it's less bad.
This increases perf by ~4-5% on `donna` and removes 4 bounds checks per `fn`.

`fn generate_grain_{y,uv}_rust`: Replace indexing `ar_lag` loops with iterators to elide bounds checks

---

.github/workflows/build-and-benchmark-x86.yml

Caught by kkysen during review.

CI: Fix git fetch command

---

src/lib.rs

Moves `Rav1dContext` destruction from `fn close_internal` to the `Drop` impl for the struct.

`struct Rav1dContext`: Move destruction into `impl Drop`

---

src/recon.rs

We can't hold a mutable reference to the `cbi` field while passing a reference to the frame data to children. Instead we can store an index and do the dereference when needed.

`mod recon`: Use `cbi` index instead of mutable reference

---

src/decode.rs
src/internal.rs
src/lib.rs

`Rav1dFrameContext_frame_thread::tile_start_off`: Make into `Vec`

---

src/decode.rs
src/internal.rs
src/intra_edge.rs
src/lib.rs

`mod intra_edge`: Make fully safe and `const fn`-initialized

---

src/c_arc.rs
src/lib.rs

These are annoying and trivial; not sure how they slipped through.

Fix some unused imports that slipped through

---

include/common/bitdepth.rs

@randomPoison, follow-up to https://github.com/memorysafety/rav1d/pull/777#discussion_r1508337862.  I wanted to share the implementation between `BPC::pxstride` and `BitDepth::pxstride`.

`fn BPC::pxstride`: Move `fn pxstride` to `BPC`, too, to allow it to be used non-generically

---

src/arm/64/looprestoration.S
src/arm/64/looprestoration16.S
src/arm/64/looprestoration_common.S
src/arm/64/looprestoration_tmpl.S
src/arm/looprestoration.h
src/looprestoration.rs

Backport changes from dav1d 1.3.0 and provide Rust equivalents to C functions.

 Add arm/aarch64 assembly code for loop restoration from dav1d 1.3.0

---

include/dav1d/headers.rs
src/fg_apply.rs
src/obu.rs

https://aomediacodec.github.io/av1-spec/av1-spec.pdf#page=130.

`enum Rav1dMatrixCoefficients`: make a real enum

---

src/decode.rs
src/internal.rs
src/recon.rs

`struct Rav1dTileState::dq`: Make into enum

---

include/dav1d/headers.rs
src/obu.rs

https://aomediacodec.github.io/av1-spec/av1-spec.pdf#page=129

`struct Rav1dTransferCharacteristics`: make a newtype wrapper

---

.github/workflows/build-and-benchmark-x86.yml
.github/workflows/build-and-test-aarch64-darwin.yml
.github/workflows/build-and-test-arm.yml
.github/workflows/build-and-test-x86.yml
.github/workflows/cargo-fmt.yml

Opening a PR or pushing to it seems to trigger each workflow twice. Trying to fix that lest it bottlenecks testing.

Trigger workflows on pushes to main and pull_requests

---

src/lib.rs

* Fixes #864.
See #889 for why stack size setting was fully removed instead of ported.

`fn pthread_attr_setstacksize`: Remove stack size setting

---

src/refmvs.rs

`fn rav1d_refmvs_init`: Cleanup and make safe

---

src/internal.rs
src/recon.rs

* Fixes part of #703.
* Fixes part of #841.

`fn {ob,}mc`: Cleanup

---

src/recon.rs

* Fixes part of #703.
* Fixes part of #841.

`fn warp_affine`: Cleanup

---

src/recon.rs

Maybe `t.b{x,y}` should be in their own field?  It'd be helpful since that's also what we pass to `debug_block_info!`.

`fn warp_affine`: Make `wmp` arg a ref by splitting the `t` arg into its used fields (for borrowck)

---

src/thread_task.rs

Cleanup state machine control flow

---

src/decode.rs
src/recon.rs
src/refmvs.rs

* Fixes field `rp_proj` of #823.
* Fixes #823.

`struct {RefMvsFrame,refmvs_tile}::rp_proj`: Make a `Vec` and an index into it

---

src/decode.rs
src/refmvs.rs

Also getting changed with #960, so you can review them together.

`struct RefMvsFrame::r`: Pass `refmvs_block_unaligned`s (12 bytes) instead of `&refmvs_block` where possible to shorten borrows

---

src/disjoint_mut.rs

We were not adding any useful information at the numerous call sites for `index()`, and the safety involved here is thread safety to avoid data races, which we don't require for this application when handling pixel data and other plain data collections. This change makes `index()` a safe function and only requires safety comments for mutable access.

Make `DisjointMut::index()` safe

---

src/decode.rs
src/internal.rs
src/recon.rs

`struct Rav1dFrameData::qm`: Make into static reference

---

src/disjoint_mut.rs

When backtraces are disabled (due to their large performance overhead), we can still capture the `Location::caller()`, which is quite cheap.  This is very useful for rare panics in CI, which can be hard to reproduce.
This also makes the out-of-bounds error messages more informative (they say which thing exactly is out of bounds and what the bound was, like `std`).

`struct DisjointMut`: Store `Location::caller()` and improve out of bounds error messages

---

src/disjoint_mut.rs

A majority of our slice ranges are of the form `[start..][..len]`.  This is easy to express with normal slices where we can do the slicing multiple times, but with `DisjointMut`, that's harder, so this adds support for `.index((start.., ..len))` to achieve the same.  It's not as clear what it means initially, but we use this idiom so much I think it might be worth it for clarity through brevity.

`trait DisjointMutIndex`: Add an `impl` for `(RangeFrom<usize>, RangeTo<usize>)` for `[start..][..len]` bounds

---

.github/workflows/build-and-test-qemu.yml
.github/workflows/test.sh

CI: test AVX512 assembly routines with QEMU

---

src/looprestoration.rs
src/lr_apply.rs

This is the last remaining `union` besides `BitDepthUnion`, which should be able to replace with a `zerocopy` `union` (but also isn't that `unsafe`, as it's safe as long as you pass the correct generics).

`struct LooprestorationParams`: Make a `zerocopy` "`union`"

---

src/itx.rs

* Fixes `fn inv_txfm_add_rust` of #817.
* Fixes `fn inv_txfm_add_rust` of #836.

`fn inv_txfm_add_rust`: Cleanup and make mostly safe

---

src/thread_task.rs

We encountered a rare conflict between trying to read the frame data for `check_tile` and a concurrent write. This change just blocks so we can have access to the necessary frame data. We believe this will be rare and therefore not have a significant performance impact.

Block while trying to read frame data for `check_tile`

---

src/mc.rs

`fn resize_rust`: Cleanup

---

src/internal.rs
src/mc.rs
src/recon.rs

`fn emu_edge_rust`: Cleanup and make mostly safe

---

src/mc.rs

Last bit of cleanup in `mc.rs` for https://github.com/memorysafety/rav1d/issues/819.

`mc.rs`: Replace C types with Rust equivalents

---

src/refmvs.rs

Last bit of cleanup for https://github.com/memorysafety/rav1d/issues/820.

`refmvs.rs`: Replace C types with Rust equivalents

---

src/looprestoration.rs

`fn padding`: use signed `stride` parameter

---

src/internal.rs
src/ipred.rs
src/recon.rs

`fn cfl_pred`: Cleanup and make safer

---

src/internal.rs
src/ipred.rs
src/recon.rs

`fn dc_gen{_top,_left}`: Cleanup and make safe

---

src/ipred.rs

`fn ipred_paeth_rust`: Cleanup and make safer

---

src/fg_apply.rs
src/filmgrain.rs

Preparing to make the picture data safe here, so wanted to clean up some other things first.

`fn rav1d_apply_grain_row`: Some more cleanup

---

src/filmgrain.rs

This prepares things for when the raw ptrs becomes `Rav1dPictureDataComponent`s, and thus fully safe.

`fn fg{y,uv}_32x32xn_rust`: Use slices where possible

---

src/recon.rs

The `fn` ptr calls are still `unsafe`; I'll fix those later.

`fn obmc`: Make `dst` data race safe, at least within the `fn`

---

src/cdef.rs

`mod cdef`: Cleanup

---

src/ipred.rs

`fn ipred_z2_rust`: Cleanup and make mostly safe

---

src/ipred.rs

`fn ipred_z3_rust`: Cleanup and make mostly safe

---

src/ipred.rs

`fn ipred_z1_rust`: Cleanup and make mostly safe

---

src/obu.rs

`mod obu`: `#![deny(unsafe_code)]`

---

src/ipred.rs
src/loopfilter.rs

`fn ipred_z*_neon`: Cleanup and make safer

---

src/ipred.rs

`mod ipred`: Mark `#![deny(unsafe_op_in_unsafe_fn)]`

---

src/decode.rs
src/pal.rs

`fn pal_idx_finish`: Make safe and remove UB

---

src/align.rs

This makes all `unsafe` ops in `mod align` justified.  The remaining one, `fn <Align* as AsMutPtr>::as_mut_ptr`, I added a `// SAFETY` comment and fixed the impl to avoid creating a temporary `&mut`.
I also adjusted a few of the other comments, and also made the temporary `&mut` more apparent in one of them.

`mod align`: Make safe

---

src/mc.rs

Only 63 `unsafe` ops left now!

`fn mc{,t}{,_scaled}`: Make safe w/ `Rav1dPictureDataComponentOffset`

---

src/decode.c
src/obu.c

Includes:
- remove parameter from call to `fn dav1d_alloc_aligned`
- fix error handling in `fn dav1d_parse_obus`

Fix C build

---

src/lib.rs

`fn output_image`: Make safe

---

src/recon.rs

Lots of borrows and captures make it difficult to make this a closure or `fn`, so it's easiest to translate this as a macro.

`fn decode_coefs`: Translate `decode_coefs_class!` macro as a macro

---

src/align.rs

This removes a bunch of alignment checks when using `.{slice,element}_as`.

`fn AsMutPtr::as_mut_ptr`: `unsafe`ly `assume` alignment when it's greater than the `Target` type

---

include/dav1d/headers.rs

Fix leak by making it a ptr to `Rav1dITUTT35::payload` (as a ref) instead of cloning it and using `Box::into_raw` (with no paired `Box::from_raw` possible).

`struct Dav1dITUTT35::payload`: Fix leak

---

src/c_box.rs

* Part of #1177.
This makes `CBox<T: Send + Sync>: Send + Sync`.
The `Unique<T>` here is just `core::ptr::Unique` copied essentially, but since that is `#[doc(hidden)]`, I didn't want to use it directly.

`struct Unique<T>`: Copy `#[doc(hidden)]` `core:::ptr::Unique` for use in `CBox::C::data`

---

src/decode.rs
src/internal.rs
src/lf_apply.rs
src/lr_apply.rs
src/recon.rs
src/thread_task.rs

* Fixes #860.
Also finished cleaning up `mod lr_apply` by making `LrRestorePlanes` a `bitflags!`.

`mod lr_apply`: Make safe

---

src/looprestoration.rs

`mod looprestoration`: Mark safe

---

src/looprestoration.rs

`mod looprestoration::neon`: Final cleanup

---

src/c_arc.rs

* Part of #1177.
This makes `CArc<T: Send + Sync>: Send + Sync`.
Accidentally "merged" #1278 (it says merged but I didn't merge it) when I flipped the order of the branches and PRs.

`struct StableRef`: Refactor out from `CArc::{,base_}stable_ref` and `unsafe impl Send + Sync` on it

---

lib.rs
src/cdf.rs
src/decode.rs
src/loopfilter.rs
src/lr_apply.rs

* Fixes `#![allow(non_snake_case)]` of #1299.

`#![allow(non_snake_case)]`: Fix and remove

---

src/disjoint_mut.rs

`mod disjoint_mut`: Remove old `#![allow(unused)]`

---

build.rs
include/common/bitdepth.rs
src/arm/64/mc.S
src/arm/64/mc_dotprod.S
src/arm/64/util.S
src/arm/mc.h
src/mc.rs
src/meson.build

Improvements include implementation of various functions using `dotprod` and `i8mm` ISA extensions.

Backport arm asm improvements from dav1d 1.4.2

---

src/lib.c
src/refmvs.c
src/refmvs.h
src/refmvs.rs

`mod refmvs`: backport changes from dav1d 1.5.0

---

.github/workflows/build-and-test-qemu.yml

What if we try an older ubuntu image

---

build.rs
src/mc.rs
src/meson.build
src/x86/looprestoration16_avx2.asm
src/x86/looprestoration_avx2.asm
src/x86/mc.h
src/x86/mc16_avx512.asm
src/x86/mc16_sse.asm
src/x86/mc_sse.asm

Backport x86 asm changes from dav1d 1.5.0

---

include/common/attributes.h
src/refmvs.h
src/refmvs.rs

Backport data size checks from dav1d 1.5.0

---

Cargo.toml
build.rs
src/arm/64/filmgrain.S
src/arm/64/filmgrain16.S
src/arm/64/ipred.S
src/arm/64/ipred16.S
src/arm/64/looprestoration_common.S
src/arm/64/mc.S
src/arm/64/mc16.S
src/arm/64/mc16_sve.S
src/arm/64/mc_dotprod.S
src/arm/64/refmvs.S
src/arm/asm.S
src/arm/cpu.c
src/arm/mc.h
src/mc.rs
src/meson.build

* Part of #1371.
Adds some ARM SVE2 assembly.

Backport ARM asm from dav1d 1.5.0

---

src/x86/looprestoration16_sse.asm
src/x86/looprestoration_sse.asm
src/x86/mc.h

Backport x86 asm from dav1d 1.5.1

---

src/arm/32/looprestoration_tmpl.S
src/arm/64/looprestoration16.S
src/arm/64/looprestoration_common.S
src/arm/64/looprestoration_tmpl.S
src/arm/64/refmvs.S
src/arm/asm-offsets.h
src/arm/cpu.c
src/arm/looprestoration.h
src/arm/refmvs.h
src/looprestoration.rs
src/refmvs.rs

Backport aarch64 asm changes from dav1d 1.5.1

---

src/recon.rs
src/recon_tmpl.c

`fn decode_coefs`: backport changes from dav1d 1.5.0

---

src/cdef_apply.rs

Split into a separate PR from #1397 @kkysen

perf: Only init `lr_bak` once (hoisted from the loop) in `fn rav1d_cdef_brow`

---

src/cdef.rs

Hi,
Took a look at the `rav1d` vs `dav1d` perf contest, and was able to find a small (~1%) improvement (as measured on my M3 MacBook Air).
This PR includes two changes:
1. In the `cdef_filter_neon_erased` call, replace `Align16([0; TMP_LEN])` with `Align16([MaybeUninit::uninit(); TMP_LEN])`.
2. In `rav1d_cdef_brow`, move up the `let mut lr_bak = Align16([..])` initialization to be outside the loop. (now in #1399 )
I believe these should be safe and correct since the C version doesn't seem to initialize `ALIGN_STK_16`-created data, but this should definitely be double-checked by someone more familiar with the code 🙏 
These changes are the result of comparing runs of `dav1d` and `rav1d`, which showed:
1. `cdef_filter_neon_erased` had a much larger "self" time vs. …

perf: arm: don't init `tmp_buf` before calling padding and filter funcs

---

src/cdef_apply.rs

(Split from #1418)
Noticed that `backup2x8` is slower compared the `dav1d`, which seems to be related to the `.stride()` call which isn't optimized away in both loops.
Perf diff is very small by only comparing this PR to the current main (244cc0b363bce7493e5b5e0ce0f092f68bf1bfe9), but it becomes more noticeable in after the main change in #1418 (still on the order of 100ms-200ms in my tests)

perf: `fn backup2x8`: call stride only once since it optimizes better

---

src/cdef.rs
src/decode.rs
src/lib.rs
src/obu.rs
src/recon.rs

Clean up some clippy errors
