- src/cdf.rs
- src/data.rs
- src/decode.rs
- src/lib.rs
- src/obu.rs
- src/picture.rs
- src/thread_task.rs
The initial transpile used a version of dav1d which did not handle C11 atomics correctly. This change fixes translations of atomic_add.
> Fix translation of atomic_add

- .github/workflows/build-and-test.yml
Closes #4.
Notes:
- covers x86_64 on ubuntu-latest. 
- caches rust toolchain and crates
- all tests are run (not just those that exercise the transpiled rust). I ran into some problem running the transpiled subset; not sure this is worth chasing down but it does increase the time to complete the test.
- uploads the test log as build artefact.
> Setup basic CI

- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
The assembly code is specific to x86-64 compilers and a comment in the C code indicates that it is meant to coerce the compiler into generating better code for 64-bit constants. See https://github.com/memorysafety/rav1d/blob/main/src/recon_tmpl.c#L147.
All tests pass on linux-aarch64 with this change. Closes #17.
> Remove non-functional inline assembly

- .gitignore
- Cargo.lock
- Cargo.toml
- build.rs
- c2rust-lib.rs
- src/align.rs
- src/cdef_apply_tmpl_16.rs
- src/cdef_apply_tmpl_8.rs
- src/cdf.rs
- src/cpu.rs
- src/decode.rs
- src/lf_apply_tmpl_16.rs
- src/lf_apply_tmpl_8.rs
- src/lib.rs
- src/log.rs
- src/lr_apply_tmpl_16.rs
- src/lr_apply_tmpl_8.rs
- src/msac.c
- src/msac.h
- src/msac.rs
- src/obu.rs
- src/picture.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/ref.rs
- src/thread_task.rs
- src/x86/cpu.rs
- src/x86/msac.h
- tools/dav1d.rs
* Setup `build.rs` to build and link x86 assembly. Initial setup builds `msac.asm` and `cpuid.asm`.
* Modify `msac.h` to replace asm `#define`s with function calls and re-transpile to update generated Rust.
* Fix alignment in structs defined in `cdf.h`. c2rust doesn't support transpiling alignment attributes, so the original transpile didn't respect alignment. This caused segfaults in the assembly since the SIMD instructions have stricter alignment requirements.
* De-duplicate structs defined in `cdf.h` to ensure that all usages of those structs share the same definition now that we have manual edits to them.
* Add `AlignN` structs to enforce struct field alignment.
> Integrate x86-64 assembly from msac.h

- c2rust-lib.rs
- src/arm/cpu.rs
- src/cpu.rs
Translate the logic for [`dav1d_get_cpu_flags_arm`](https://github.com/memorysafety/rav1d/blob/39968db983ce4211e48ca173e8d5d189b3b666c6/src/arm/cpu.c#L83). I tried to replicate the original logic using Rust's conditional compilation mechanisms, but the translations isn't one-to-one.
> Get CPU flags for arm targets

- build.rs
- src/cdef_tmpl_16.rs
- src/cdef_tmpl_8.rs
Add the x86 assembly for `cdef.h` and `cdef_tmpl.c`. Arm assembly is now being built and linked, but init logic for it has not yet been added.
> Setup x86 asm for cdef_tmpl

- src/cdef_apply_tmpl_16.rs
- src/cdef_apply_tmpl_8.rs
- src/cdf.rs
- src/decode.rs
- src/lf_apply_tmpl_16.rs
- src/lf_apply_tmpl_8.rs
- src/lib.rs
- src/log.rs
- src/lr_apply_tmpl_16.rs
- src/lr_apply_tmpl_8.rs
- src/obu.rs
- src/picture.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/thread_task.rs
- tools/dav1d.rs
- tools/dav1d_cli_parse.rs
Remove `va_list`, as `c2rust transpile` replaces its uses with `core::ffi::VaList` and so `va_list` is completely unused.
> Remove `va_list` as it's unused

- src/cdef_apply_tmpl_16.rs
- src/cdef_apply_tmpl_8.rs
- src/cdf.rs
- src/decode.rs
- src/lf_apply_tmpl_16.rs
- src/lf_apply_tmpl_8.rs
- src/lib.rs
- src/log.rs
- src/lr_apply_tmpl_16.rs
- src/lr_apply_tmpl_8.rs
- src/obu.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/thread_task.rs
It was already in `src/picture.rs`, so the primary definition stays there.
> Deduplicate `enum PictureFlags` to `src/picture.rs`

- src/cdef_apply_tmpl_16.rs
- src/cdef_apply_tmpl_8.rs
- src/cdf.rs
- src/decode.rs
- src/ipred_prepare_tmpl_16.rs
- src/ipred_prepare_tmpl_8.rs
- src/lf_apply_tmpl_16.rs
- src/lf_apply_tmpl_8.rs
- src/lib.rs
- src/log.rs
- src/lr_apply_tmpl_16.rs
- src/lr_apply_tmpl_8.rs
- src/obu.rs
- src/picture.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/refmvs.rs
- src/thread_task.rs
It was already in `src/intra_edge.rs`, so the primary definition stays there.
> Deduplicate `enum EdgeFlags` to `src/intra_edge.rs`

- c2rust-lib.rs
- src/cdef_apply_tmpl_16.rs
- src/cdef_apply_tmpl_8.rs
- src/cdf.rs
- src/decode.rs
- src/lf_apply_tmpl_16.rs
- src/lf_apply_tmpl_8.rs
- src/lib.rs
- src/log.rs
- src/looprestoration.rs
- src/looprestoration_tmpl_16.rs
- src/looprestoration_tmpl_8.rs
- src/lr_apply_tmpl_16.rs
- src/lr_apply_tmpl_8.rs
- src/obu.rs
- src/picture.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/thread_task.rs
`enum LrEdgeFlags` is originally from `src/looprestoration.h`, and so is the same in all instantiations of `src/looprestoration_tmpl.c`, so I've defined it in the newly-created `src/looprestoration.rs` (which will be where `src/looprestoration_tmpl_{8, 16}.rs` will later merge to).
> Deduplicate `enum LrEdgeFlags` to `src/looprestoration.rs`

- c2rust-lib.rs
- src/lf_apply_tmpl_16.rs
- src/lf_apply_tmpl_8.rs
- src/lr_apply.rs
- src/lr_apply_tmpl_16.rs
- src/lr_apply_tmpl_8.rs
`enum LrRestorePlanes` is originally from `src/lr_apply.h`, and so is the same in all instantiations of `src/lr_apply_tmpl.c`, so I've defined it in the newly-created `src/lr_apply.rs` (which will be where `src/lr_apply_tmpl_{8, 16}.rs` will later merge to).
> Deduplicate `enum LrRestorePlanes` to `src/lr_apply.rs`

- src/cdef_apply_tmpl_16.rs
- src/cdef_apply_tmpl_8.rs
- src/cdf.rs
- src/decode.rs
- src/lf_apply_tmpl_16.rs
- src/lf_apply_tmpl_8.rs
- src/lf_mask.rs
- src/lib.rs
- src/log.rs
- src/loopfilter_tmpl_16.rs
- src/loopfilter_tmpl_8.rs
- src/lr_apply_tmpl_16.rs
- src/lr_apply_tmpl_8.rs
- src/obu.rs
- src/picture.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/thread_task.rs
All of these `struct`s are originally from `src/lf_mask.h`, so I've deduplicated them to `src/lf_mask.rs`.  `struct Av1FilterLUT` (b066e6a6f1ac893315b42493f8bd0ef7180cac39) and `struct Av1Filter` (9c3e71c26876eb226a4afa0c3ac05e8cd7863865) were already in `src/lf_mask.rs`, while `struct Av1RestorationUnit` (537bc3a69a89541195f1921e9e87b36162321311) and `struct Av1Restoration` (c3dadcf9336e7fd0857a3277afca7d59aa0bbfe1) were only defined in other `*.rs` files, so they've been deduplicated to `src/lf_mask.rs`, since they were from `src/lf_mask.h`.
> Deduplicate `struct`s from/to `src/lf_mask.{h,rs}`

- src/cdef_apply_tmpl_16.rs
- src/cdef_apply_tmpl_8.rs
- src/cdf.rs
- src/decode.rs
- src/lf_apply_tmpl_16.rs
- src/lf_apply_tmpl_8.rs
- src/lib.rs
- src/log.rs
- src/lr_apply_tmpl_16.rs
- src/lr_apply_tmpl_8.rs
- src/obu.rs
- src/picture.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/thread_task.rs
These should be all of the non-`BITDEPTH`-dependent `typedef`s.
> Deduplicate `ec_win` to `src/msac.rs`

- src/cdef_apply_tmpl_16.rs
- src/cdef_apply_tmpl_8.rs
- src/cdf.rs
- src/decode.rs
- src/internal.rs
- src/lf_apply_tmpl_16.rs
- src/lf_apply_tmpl_8.rs
- src/lib.rs
- src/log.rs
- src/lr_apply_tmpl_16.rs
- src/lr_apply_tmpl_8.rs
- src/obu.rs
- src/picture.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/thread_task.rs
Now that type is deduplicated, it can be easily `#[repr(align(64))]`ed like in the C source: https://github.com/memorysafety/rav1d/blob/c2fb626189f313dd3ed8f1b74dbcfd80f333a43c/src/internal.h#L397-L400
> Deduplicate previously unnamed `union Dav1dTaskContext_cf`

- src/cdef_apply_tmpl_16.rs
- src/cdef_apply_tmpl_8.rs
- src/cdf.rs
- src/decode.rs
- src/internal.rs
- src/lf_apply_tmpl_16.rs
- src/lf_apply_tmpl_8.rs
- src/lib.rs
- src/log.rs
- src/lr_apply_tmpl_16.rs
- src/lr_apply_tmpl_8.rs
- src/obu.rs
- src/picture.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/thread_task.rs
Now that type is deduplicated, it can be easily `#[repr(align(64))]`ed like in the C source: https://github.com/memorysafety/rav1d/blob/c2fb626189f313dd3ed8f1b74dbcfd80f333a43c/src/internal.h#L433-L442
> Deduplicate previously unnamed `union Dav1dTaskContext_scratch_interintra_edge` and its 2 unnamed `struct` fields

- src/recon_tmpl_16.rs
- src/refmvs.rs
- tools/input/section5.rs
To keep things `cargo fix`-clean after #56 so `cargo fix` can be easily used for removing unused imports during deduplication, for example.
Should be mergeable right away; just wanted to double-check with CI first; hence the PR.
> `cargo fix` after #24

- .github/workflows/qemu-arm7.yml
- .github/workflows/test.sh
This is a low risk change so merging without further review. Ping me if autostitch or other tests still time out occasionally.
> Add a timeout multiplier of 2 for arm7 tests

- src/cdef_apply_tmpl_8.rs
- src/fg_apply_tmpl_8.rs
- src/ipred_prepare_tmpl_8.rs
- src/lf_apply_tmpl_8.rs
- src/looprestoration_tmpl_8.rs
- src/lr_apply_tmpl_8.rs
- src/recon_tmpl_16.rs
Accidentally missed some unnamed renames from #84, mostly due to the re-transpilation `cherry-pick` only applying to either the 8 or 16 bitdepth version.  I now went through each renamed type and checked for remaining `C2RustUnnamed_*` types and fixed them.
> Fix missed unnamed renames from #84

- src/cdef_apply_tmpl_16.rs
- src/cdef_apply_tmpl_8.rs
- src/cdf.rs
- src/decode.rs
- src/internal.rs
- src/lf_apply_tmpl_16.rs
- src/lf_apply_tmpl_8.rs
- src/lib.rs
- src/log.rs
- src/lr_apply_tmpl_16.rs
- src/lr_apply_tmpl_8.rs
- src/obu.rs
- src/picture.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/thread_task.rs
Now that type is deduplicated, it can be easily `#[repr(align(64))]`ed like in the C source: https://github.com/memorysafety/rav1d/blob/1b882647c4d16f94efcce81a7111503db3c491d9/src/internal.h#L406-L444
> Deduplicate `struct Dav1dTaskContext_scratch` and its previously unnamed inner types to `src/internal.rs`

- .github/workflows/build-and-test.yml
Assembly is disabled since it doesn't link properly for i686. I suggest we merge and then enable assembly once issue #119 is fixed. WDYT?
> Build and test i686 target

- c2rust-lib.rs
- src/ctx.rs
- src/decode.rs
- src/lf_mask.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
These should be the last non-bitdepth-dependent types to deduplicate.
> Deduplicate `union alias[0-9]+` types

- src/decode.rs
- src/lf_mask.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/tables.rs
Actually this is the last non-bitdepth-dependent deduplicated type.
> Deduplicate `struct TxfmInfo` to `src/tables.rs`

- c2rust-lib.rs
- include/common/dump.rs
- src/cdef.rs
- src/cdef_tmpl_16.rs
- src/cdef_tmpl_8.rs
- src/decode.rs
- src/env.rs
- src/filmgrain.rs
- src/filmgrain_tmpl_16.rs
- src/filmgrain_tmpl_8.rs
- src/ipred.rs
- src/ipred_prepare.rs
- src/ipred_tmpl_16.rs
- src/ipred_tmpl_8.rs
- src/msac.rs
- src/obu.rs
- src/recon.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/refmvs.rs
This deduplicates most of the remaining duplicated inline `fn`s, with the exception of
* a few very large functions that I want to deduplicate in a separate PR
* functions that depend on other duplicated, `static` `fn`s
* and bitdepth-dependent functions
* also I missed non-verbatim `#[inline]` functions, like `#[inline(always)]` and `#[cfg(feature = "asm")]` ones
> Deduplicate most remaining duplicated inline `fn`s

- src/cpu.rs
Removing this gets rid of the last warnings (`#[warn(clashing_extern_declarations)]`).
> Remove an unused `fn dav1d_log` declaration, fixing all warnings

- src/decode.rs
Convert the `t` argument to `decode_b` from `*mut` to a `&mut`, and simplify all references to that variable. I also removed the `extern "C"` from the function declaration since it is only called from within `decode.rs`.
> decode_b: Convert raw pointer to reference

- src/decode.rs
- src/levels.rs
Cleanup the initial variable declarations in `decode_b`, mostly removing redundant type declarations/casts. I also derived `Default` on a few structs to make it easier to initialize.
> decode_b: Cleanup initial variable declarations

- include/common/attributes.rs
- include/common/intops.rs
These functions are already safe, so I just removed the `unsafe` and `extern "C"` and cleaned them up a bit.  They're used all over the place, including in `decode_b` and its children.
> Cleanup and make safe `attributes.rs` and `intops.rs`

- src/decode.rs
`fn affine_lowest_px` and `fn affine_lowest_px_luma` are made safe, but not yet `fn affine_lowest_px_chroma`, because it contains a `&*t.f` deref.  I'll wait until `Dav1dTaskContext::f: *const Dav1dFrameContext` is made a ref to fix that.
In updating the call sites, I passed `b_dim` as an array ref vs. a raw ptr, but since updating all the use sites in `decode_b` would be a lot, I didn't do that yet to not interfere too much with @randomPoison's work in `decode_b`.
> Cleanup and make safe `fn affine_lowest_px*`

- include/dav1d/common.rs
- include/dav1d/data.rs
- include/dav1d/headers.rs
- include/dav1d/picture.rs
- src/cdf.rs
- src/data.rs
- src/decode.rs
- src/env.rs
- src/getbits.rs
- src/lib.rs
- src/mc_tmpl_16.rs
- src/mc_tmpl_8.rs
- src/msac.rs
- src/obu.rs
- src/picture.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/ref.rs
- src/refmvs.rs
- tools/dav1d.rs
We've started to do this already to individual fields, so this just does it for them all.
> Rename all `ref_0`s to `r#ref`

- src/cdef_apply_tmpl_16.rs
- src/cdef_apply_tmpl_8.rs
- src/cdef_tmpl_16.rs
- src/cdef_tmpl_8.rs
- src/cdf.rs
- src/decode.rs
- src/filmgrain_tmpl_16.rs
- src/filmgrain_tmpl_8.rs
- src/intra_edge.rs
- src/ipred_tmpl_8.rs
- src/lf_apply_tmpl_16.rs
- src/lf_apply_tmpl_8.rs
- src/lf_mask.rs
- src/lr_apply_tmpl_16.rs
- src/lr_apply_tmpl_8.rs
- src/msac.rs
- src/obu.rs
- src/picture.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/warpmv.rs
- src/wedge.rs
- tools/dav1d.rs
- tools/input/ivf.rs
- tools/output/md5.rs
`cargo fmt`ing (#177) makes the regexes from #166 pickup a lot more.
> Cleanup remaining trivial redundant casts (after `cargo fmt`)

- src/refmvs.rs
The only unsafe thing left is `refmvs_frame`'s `frm_hdr: *const Dav1dFrameHeader` field.
Also, I wasn't sure about what to name `globalmv` in eb3704da52195fa3628dbee8f6ed703e94250492.
> `fn add_temporal_candidate`: Cleanup and make almost safe

- src/warpmv.rs
These could be further cleaned up by parameterizing over `u32` and `u64`, but it's not that important yet.  I would like to replace the `ulog2` and `u64log2` calls with `{u32, u64}::ilog2`, but `ilog2` was stabilized in Rust `1.67`, and our pinned nightly is a bit behind that.  Would it be a good idea to upgrade that to something newer?  Unfortunately, we'll have to stay on nightly for a while longer until we finish getting rid of varargs, extern types, and intrinsic calls.
> `fn resolve_divisor_{32,64}`: Cleanup and make safe

- include/dav1d/headers.rs
- src/decode.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/tables.rs
- src/warpmv.rs
This also removes the unsafe `union Dav1dWarpedMotionParams_u` in d8e01670d48b2ab26503afd575d9e3f48393af5b.
> `fn dav1d_get_shear_params`: Cleanup and make safe

- src/decode.rs
- src/warpmv.rs
After this, `warpmv.rs` is now entirely safe!
> `fn dav1d_find_affine_int`: Cleanup and make safe

- src/decode.rs
The remaining `unsafe` is in this line:
```rust
let rp = |i: i32, j: i32| &*r(i as isize).offset(j as size);
```
Some of the cleanups here were non-trivial to satisfy the borrow checker, such as:
* 9aac8c97254cb1a47cfdb40c618365c593a8fcdb
* 022d74c08a62ccf072630dee92109fa8b7b353e1
so I had to change some signatures.
> `fn derive_warpmv`: Cleanup and make almost safe

- .github/workflows/cargo-fmt.yml
- build.rs
- rust-toolchain.toml
- src/cdef_tmpl_16.rs
- src/decode.rs
- src/filmgrain_tmpl_16.rs
- src/filmgrain_tmpl_8.rs
- src/ipred_tmpl_16.rs
- src/ipred_tmpl_8.rs
- src/mc_tmpl_16.rs
- src/mc_tmpl_8.rs
- src/refmvs.rs
A few things have gotten mis-formatted as a result of bad merges since the initial formatting pass. This PR adds a new workflow to check formatting in CI, and does one final `cargo fmt` run over everything.
> Add workflow for checking formatting and run one more formatting pass

- src/decode.rs
fe804849ef1fd402c75e9032cb74fdd900572c3a is the only interesting commit here.  In the C, it was nullable, but since the guarding condition was pretty separate, making it an `Option` would be more unwieldy.  Instead, I just initialized to a zeroed array ref instead of null.  It doesn't matter what it's initialized to, as it'll never get rid.  Also, this `pc` var should just be `&` eventually, but `dav1d_msac_decode_symbol_adapt16` takes it as a `*mut` ptr (even though it doesn't actually mutate it), but I'll fix that when I clean up those functions.
> `fn get_{top,left}_partition_ctx`: Cleanup and make safe

- src/decode.rs
- src/env.rs
This does just the simplest cleanups (that apply equally to args of all `fn`s) and makes all the `fn`s safe.  There are still lots of little things to clean up in these functions (e.x. redundant casts), but they're all safe now.
> `fn *_ctx`: Cleanup (minimally) and make safe

- src/decode.rs
- src/env.rs
See d21d91d6532e012fc3e8c5a6d68aa39cc1bcc184 for why it's going to be difficult to make this safe for a while until we clean up a lot more things and understand the dataflow better.
> `fn get_cur_frame_segid`: Cleanup

- src/decode.rs
This cleans up most of the function body in terms of safety, but just like #201 where `cur_seg_map` was difficult to make a safe slice, here `ref_seg_map` is similarly difficult to make a safe slice for the same reason.  That said, from the function body, we can tell how long `ref_seg_map` is assumed to be at maximum, and then immediately convert it to a slice (unsafely with `std::slice::from_raw_parts`), so at least the rest of the function is safe.
> `fn get_prev_frame_segid`: Cleanup and make mostly safe

- src/decode.rs
Fixes incorrect logic introduced in 0ceca4f89 and d41a06c78 where assert! statements were added.
> Fix logic in assert! statements

- src/decode.rs
The `pal_idx` arg remains a raw ptr and unsafe, and it can be made safe, but since the changes to `pal_idx` propagate significantly throughout the code, I'll save it for a separate PR.
> `fn order_palette`: Cleanup and make mostly safe

- .github/workflows/build-and-test-arm7.yml
- build.rs
- src/cdef_tmpl_8.rs
- src/ipred_tmpl_16.rs
- src/ipred_tmpl_8.rs
- src/looprestoration_tmpl_16.rs
- src/looprestoration_tmpl_8.rs
- src/tables.rs
Still need to enable `wiener_filter_neon` and the assembly routines it calls but that can happen in a separate PR.
> Fix numerous alignment issues and enable most arm assembly routines

- src/decode.rs
- src/msac.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
This also removes `#[no_mangle]`s and `extern "C"`s, which can be done now that their declarations have been deduplicated into `use`s.  It also renames the `*_c` `fn` to `*_rust` now that they're in Rust.
> `fn dav1d_msac_*`: Deduplicate declarations

- src/lib.c
- src/lib.rs
Closes #213.  Note that this PR also patches the C sources using the two commits referenced [here](https://github.com/memorysafety/rav1d/issues/213#issuecomment-1535071857). 
With this change, `rav1d` successfully passes all 2763 Argon test vectors 🥳
> Fix threading issue causing Argon test 6075 to hang

- src/decode.rs
- src/msac.rs
- src/recon.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
The major refactor here is making the `cdf: *mut u16` a `&mut [u16]` slice.  All call sites are array refs, so this works nicely (though there are quite a lot of these, ~155).
For `fn dav1d_msac_decode_symbol_adapt_rust`, however, this is trickier, as `cdf` must round-trip through FFI and perhaps an asm call, so slices can't be used.  `cdf.len()` could be added as an extra arg, but that may require changing asm slightly, which I don't want to do at all.  However, `n_symbols` is the last index accessed in `cdf`, so `n_symbols + 1` should be a valid length, possibly smaller.  Thus, an `assert!(n_symbols < cdf.len())` before the `s.symbol_adapt16` call ensures that in `fn dav1d_msac_decode_symbol_adapt_c`, this still holds true, and thus we can safely reconstruct the slice (or a subset) with …
> `fn dav1d_msac_*`: Cleanup and make args safe

- build.rs
- src/cdef_tmpl_16.rs
- src/cdef_tmpl_8.rs
- src/cpu.rs
- src/filmgrain_tmpl_16.rs
- src/filmgrain_tmpl_8.rs
- src/ipred_tmpl_16.rs
- src/ipred_tmpl_8.rs
- src/itx_tmpl_16.rs
- src/itx_tmpl_8.rs
- src/loopfilter_tmpl_16.rs
- src/loopfilter_tmpl_8.rs
- src/looprestoration_tmpl_16.rs
- src/looprestoration_tmpl_8.rs
- src/mc_tmpl_16.rs
- src/mc_tmpl_8.rs
- src/msac.rs
> Fix unused compiler warnings

- src/decode.rs
- src/msac.rs
The remaining significant unsafe part around `MsacContext::buf_{pos,end}` will be fixed in a separate PR (#222), as it's a bit more complex.
> `src/msac.rs`: Cleanup `fn`s and make mostly safe

- src/msac.rs
This adds a safe API around `MsacContext::buf_{pos,end}` and uses it to make `fn ctx_{refill,norm}` safe.
Note that the lifetime requirements for `buf_{pos,end}` are moved to `fn dav1d_msac_init`'s `data` arg's `Safety` comment.  Later, we'll add a proper lifetime here, but that's much more involved as it propagates through a lot of function calls and types.
> `struct MsacContext`, `fn ctx_{refill,norm}`: Make safe

- src/msac.rs
Since `checkasm` has (for C)/will (for Rust) that the `*_c`/`*_rust` safe versions are equivalent to the asm versions, we can safely call the asm versions and thus make all of these functions safe.
> `fn dav1d_msac_decode_*`: Make safe

- src/decode.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/refmvs.rs
Align by aligning a wrapper struct around an inner packed struct, as Rust doesn't allow packed and aligned types (see https://github.com/rust-lang/rust/issues/59154).
> `struct refmvs_block`: Align a wrapper struct for an inner packed struct

- src/align.rs
- src/cdf.rs
- src/decode.rs
- src/env.rs
- src/internal.rs
- src/mc_tmpl_16.rs
- src/mc_tmpl_8.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/scan.rs
- src/tables.rs
- src/wedge.rs
Fixes #122.
This aligns all remaining statics, fields, and variables that use `dav1d`'s C `ALIGN` macro to specify their alignment.
> Fix missing aligns

- src/decode.rs
Recreate the inline macro `assign_comp_mv` and deduplicate the two expansions of it in the Rust code.
> decode_b: Deduplicate assign_comp_mv

- src/decode.c
- src/decode.rs
- src/refmvs.c
- src/refmvs.h
- src/refmvs.rs
- src/x86/refmvs.asm
- src/x86/refmvs.h
- tests/checkasm/refmvs.c
Make `refmvs_temporal_block` a packed structure and abstract functions for loading and saving it. Add asm functions for saving mvs. Partially addresses #225
> Backport refmvs changes from dav1d 1.2.0

- src/decode.rs
- src/recon.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
Since `fn DEBUG_BLOCK_INFO` depends on types (`Dav1dFrameContext`, `Dav1dTaskContext`) that haven't been deduplicated/genericized over bitdepth yet, we can't have a single definition for it, even though it only uses fields that are not bitdepth-dependent.  Thus, I defined a macro that defines the `fn` in each module that uses it.  Once we do bitdepth genericization or split out the non-bitdepth-dependent parts of these types, we can consolidate the `fn`-defining macro into just a normal `fn`.
Also, making some other functions safe requires `DEBUG_BLOCK_INFO` to take refs instead of raw ptrs, which is why I decided to fully deduplicate and clean this up now.
> `fn DEBUG_BLOCK_INFO`: Deduplicate and cleanup

- rust-toolchain.toml
- src/cdef_apply_tmpl_16.rs
- src/cdef_apply_tmpl_8.rs
- src/cdef_tmpl_8.rs
- src/decode.rs
- src/env.rs
- src/fg_apply_tmpl_16.rs
- src/fg_apply_tmpl_8.rs
- src/lf_mask.rs
- src/lr_apply_tmpl_16.rs
- src/lr_apply_tmpl_8.rs
There are some newly stabilized things that we want to use to replace C versions.  `ilog2` from #184 and other cleanups was one of them, and there were some other ones I came across as well.
Also, `#![feature(let_chains)]` became unstable again as it was implemented incorrectly, so I've removed their few uses and manually desugared them or used `Option::filter` instead.
Also, upgrading the toolchain seems to cause test failures now because of stricter checks.  Raw pointer dereferences are now checked for alignment (in debug builds it seems), and that's now uncovering further errors.  Unaligned references are UB in Rust, so we need to fix these.  Tracked in #250.  This is another great reason to upgrade the toolchain, as this is a really useful check.
Update: #251 has been merged into this …
> Update to latest nightly, `nightly-2023-05-10`

- src/decode.rs
- src/lf_mask.rs
A bunch of simple, common cleanups for everything in `src/lf_mask.rs` (`fn`s are called by `decode_b`).
> `src/lf_mask.rs`: Simple cleanup

- src/ctx.rs
- src/decode.rs
- src/lf_mask.rs
I still need to make `txa` a safe slice/array ref (see the discussion below), but doing so in the way it's done in C would be UB in Rust, so I'm going to change the implementation a bit to make it safe, as @fbossen suggested below in a follow-up PR.
> `fn decomp_tx`: Cleanup and make mostly safe

- src/decode.rs
- src/lf_mask.rs
The only unsafe part left is the `txa` stuff, which I'll fix in a separate PR as mentioned in https://github.com/memorysafety/rav1d/pull/261#issuecomment-1555200944.
> `fn mask_edges_inter`: Cleanup and make mostly safe

- src/ctx.rs
- src/decode.rs
- src/lf_mask.rs
The only thing still `unsafe` here is the `case_set*` functions.  I can start looking into how to make that safe soon, though it may end up being a more different implementation (like #127).
> `fn mask_edges_intra`: Cleanup and make mostly safe

- src/lf_mask.rs
This reformulates the usage of `txa` in `decomp_tx` to a way that can be easily made safe (and is actually simpler, too).  Previously, the multidimensional array `txa` was offset in each recursive call but still passed as a pointer to the original sized array.  Making this array pointer a reference would be UB, since it didn't actually point to the whole array anymore, but to somewhere in the middle of it.  Instead, the correct offsets are calculated from `{x,y}_off`, which are existing args, and applied at all `txa` use sites.
Note that this was also previously UB in Rust, as the fake array pointer was dereferenced and that extended out of bounds.
> `fn decomp_tx`: Reformulate `txa` accesses so it can be made safe

- src/decode.rs
There are a couple more cleanups we could do here to elide bounds checks (like they were previously with `unsafe`), which I left `TODO` comments for.  For one of them, the iterator version is much more complex, so I left it out for now.  And for the other, it'd replace a large chunk of logic with `itertools`' `.merge` and `.dedup`, so it'd be simple, but add an `itertools` dependency (which might be something we want to do, eventually).
> `fn read_pal_plane`: Cleanup and make mostly safe

- src/decode.rs
- src/levels.rs
- src/refmvs.rs
This is the last of the functions before `decode_b` that I've now cleaned up (though many are still `unsafe`, and there are other functions in other modules, too).
> `fn splat_*`: Cleanup and make mostly safe

- src/decode.rs
- src/lf_mask.rs
In 529ed6f159eda299b24f6640abc4895fe74115c3, I had to do something similar to #264 to remove the UB.
The remaining unsafety besides calls to other `unsafe fn`s is from `level_cache` (9bb20b40327b062bc50f7f4aaf6f12795c8505b5).  Passing it as a slice would require making `Dav1dFrameContext_lf::level` a `Vec`, which I can do (and have done), but it's a much more involved refactor, and it results in warnings due to `Vec`s passing over FFI, so we should remove unnecessary FFI calls first.
> `fn dav1d_create_lf_mask_{intra,inter}`: Cleanup and make mostly safe

- src/decode.rs
This is mainly done by using `std::slice::from_raw_parts_mut` on `frame_thread.pal_idx` and determining the length by the `frame_thread.pal_idx.offset(len)` call afterward.  Making it safe all the way to the allocation root is a lot more complex.
> `pal_idx`: Make a safe slice

- src/cdef_apply_tmpl_16.rs
- src/cdef_apply_tmpl_8.rs
- src/cdf.rs
- src/decode.rs
- src/internal.rs
- src/lf_apply_tmpl_16.rs
- src/lf_apply_tmpl_8.rs
- src/lib.rs
- src/log.rs
- src/lr_apply_tmpl_16.rs
- src/lr_apply_tmpl_8.rs
- src/obu.rs
- src/picture.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/thread_task.rs
The reason why there are still a lot of duplicate types left is because they contain bitdepth-dependent types, mainly `pixel` and `coef`.  Luckily, these are all behind pointers, and so we can normalize them to `*mut libc::c_void` and then cast them to the appropriate bitdepth-dependent type when they're used.  Once normalized, they can then be deduplicated.
I initially was going to use a `union` for this, given that there are only two bitdepth variants in the code, 8 and 16, but there are some cases where `coef` and `pixel` pointers are cast to other types as well, such as `*mut uint8_t` and `*mut libc::c_void`, so I've just left them as `*mut libc::c_void` for now.  They can always be changed to a `union` later.
Note also that many of these pointers are slices, so before `.offset`ting …
> Normalize and deduplicate many of the bitdepth-dependent types

- src/decode.rs
An example crash:
```shell
❯ cargo run -- -i ./tests/argon/profile0_core/streams/test10041.obu --filmgrain 1 --verify 8823d10667e90c4314d12b6e1171afdd --cpumask -1 --threads 0 -q   Compiling c2rust_out v0.0.0 (/home/kkysen/work/rust/rav1d)
Finished dev [unoptimized + debuginfo] target(s) in 2.12s
Running `target/debug/dav1d -i /home/kkysen/work/rust/rav1d/tests/argon/profile0_core/streams/test10041.obu --filmgrain 1 --verify 8823d10667e90c4314d12b6e1171afdd --cpumask -1 --threads 0 -q`
Unknown Metadata OBU type 0
thread '<unnamed>' panicked at 'index out of bounds: the len is 7 but the index is 7', src/decode.rs:4244:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'index out of bounds: the len is 7 but the index is 7', …
```
> Fix a typo bug from 9f923675 causing crashes (out-of-bounds accesses) in the argon tests

- src/decode.rs
- src/refmvs.rs
This adds wrapper `fn`s around the FFI/asm `fn`s so things can be made safer without changing any asm signatures.
Once fewer things have to be `#[repr(C)]`, then the `fn` ptr can be made non-`extern "C"` and the args even safer (e.x. slices will work, but aren't safe currently over C's ABI).
Once the inner `*mut refmvs_block` raw ptr is made safe (a slice or an obviously correct separate length), then these functions can be made fully safe (with `unsafe` blocks, but checked ones).
> `splat_mv_fn`: Make safer

- src/recon.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
This leaves a bunch of casts at `get_lo_ctx` call sites in `decode_coefs`, but those should go away once I clean up `decode_coefs`, but since it's still duplicated, I'll do that after deduplication.
> `fn get_lo_ctx`: Cleanup and make safe

- src/recon.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
There's more cleanup we could do here I think to make this function way more concise using some generics, but this is the way the C does it, so I'll leave it at that for now, and it's safe now.
> `fn get_dc_sign_ctx`: Cleanup and make safe

- include/common/dump.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
This `fn` is in `include/`, but is not marked `DAV1D_API`, so I consider it non-exported.
> `fn ac_dump`: Cleanup and make safe

- include/common/dump.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
Since `coef_dump` only prints `coef`s, we can make the generic bound just `Display` here, meaning we don't have to setup full bitdepth generics yet.
To make this fully safe, we'd have to make `Dav1dFrameContext_frame_thread::cf` a `Vec` and `Dav1dTileState_frame_thread::cf` a slice or something.
> `fn coef_dump`: Cleanup and deduplicate as a generic `fn` over `Coef: Display`

- src/decode.rs
See also https://github.com/memorysafety/rav1d/commit/19cb8394582b5af123ac8b2cecdcfd097904a66b#r118089193.
> `fn decode_b`: Revert code deleted in #132

- Cargo.toml
As we port, we increasingly use operations that require more optimizations to be zero-cost, so while `--release` perf stays the same, debug perf suffers a lot, unless we enable the basic optimizations (`opt-level = 1`), which don't increase compile-time that much.
> `profile.dev`: Set `opt-level = 1`

- src/msac.rs
This is a small, simple example of devirtualizing a `fn` ptr into an `enum` in code I've already cleaned up.  Since it still works and there are no segfaults, I assume assembly is not calling the `fn` ptr directly (though there is untested assembly).
> `MsacContext::symbol_adapt16`: Devirtualize

- include/common/bitdepth.rs
An example of using this can be seen in `fn decode_coefs` in [`kkysen/deduplicate-fn-decode_coefs`](https://github.com/memorysafety/rav1d/tree/kkysen/deduplicate-fn-decode_coefs), but that code can't be finished until we deduplicate types, so it's only here as a WIP branch for now.
A complete example is in #311.
> `trait BitDepth`: Enable generic `as` casts in bitdepth-dependent `fn`s

- include/common/bitdepth.rs
- include/common/intops.rs
This reflects actual usage of `iclip_pixel`.
I used an `unsafe` in `fn clip`, as `.try_into().unwrap()` doesn't always get optimized out, and it's way slower when not.  This should be safe as long as the `U: Into<T>` and `T: TryInto<U>` `impl`s are well-formed (they definitely are for all primitives).
> `fn {clip,iclip_pixel}`: Allow them to clip into a smaller type

- include/common/bitdepth.rs
- src/mc.rs
- src/mc_tmpl_16.rs
- src/mc_tmpl_8.rs
`src` is left as a raw ptr due to the negative offset.  It's easier to wait to fix it once the pointers become slices top-down than to figure out exactly how to adjust the indices and calculate the length here.
> `fn put_8tap_c`: Deduplicate w/ generics and cleanup/re-translate, including macros used

- build.rs
We need to set PREFIX to one in config.asm such that the assembly routine names get mangled correctly, otherwise linking will fail.
> Fix macOS build on x86 hosts

- .github/workflows/build-and-test-x86.yml
Since performance testing happens on macOS (for aarch64), it would be nice to automatically test breakage on macOS although GitHub actions do not offer any arch64-apple-darwin test runners at the moment.
> CI: Test on x86_64-apple-darwin

- .github/workflows/build-and-test-aarch64.yml
- .github/workflows/build-and-test-arm7.yml
- .github/workflows/build-and-test-x86.yml
- .github/workflows/test.sh
- Cargo.toml
- meson_options.txt
- tests/meson.build
- tests/seek_stress.rs
Closes #76. This is the easiest way to run all the stress tests so hopefully okay until we address #77. `seek_stress.rs` could be cleaned up (at least deleting all the duplicated types and externs) but that is probably easier to review in a separate PR.
> Add transpiled seek_stress integration test

- src/cdef_apply_tmpl_16.rs
- src/cdef_apply_tmpl_8.rs
- src/cdf.rs
- src/decode.rs
- src/lf_apply_tmpl_16.rs
- src/lf_apply_tmpl_8.rs
- src/lib.rs
- src/log.rs
- src/looprestoration.rs
- src/looprestoration_tmpl_16.rs
- src/looprestoration_tmpl_8.rs
- src/lr_apply_tmpl_16.rs
- src/lr_apply_tmpl_8.rs
- src/obu.rs
- src/picture.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/thread_task.rs
Alternative to #323 that approaches the problem of deduplicating bitdepth-dependent fn pointers by type-erasing the bitdepth-dependent parts. To accomplish this, the relevant `extern "C"` declarations were moved into `looprestoration.rs`, where `pixel` has been defined as `c_void`. For the 8bpc versions, an extra `bitdepth_max: c_int` argument has been added so that the 8bpc and 16bpc fns have the same signature, with the understanding that this extra argument will simply be ignored by the called asm routine. For fn pointers that are defined in Rust code, type-erased wrappers have been added..
> `struct Dav1dLoopRestorationDSPContext`: Deduplicate via type-erased `fn` pointers

- src/looprestoration.rs
- src/looprestoration_tmpl_16.rs
- src/looprestoration_tmpl_8.rs
Deduplicate `padding` into `looprestoration.rs` and make it generic over bitdepth.
> `fn padding`: Deduplicate w/ generics and cleanup

- include/common/bitdepth.rs
This is the same as I suggested for ab5262ca84cdbfb5457e2a2b4328c6b119d9a7b4 in #334, but I wanted to add it as a separate PR and also add docs so it's clear why we're doing it this way.
> `trait BitDepth`: Add `fn from_c` to uniformly convert from C's repr (w/ docs)

- src/looprestoration.rs
These are mostly from my comments on #330 further cleaning up `fn padding`, plus a few other things.
I also think there are other cleanups we can do that would get rid of most of the bounds checking that was added to `fn padding`.  I'll wait until #334 merges first, though.
> `fn padding`: Further cleanup

- include/common/bitdepth.rs
- src/mc.rs
- src/mc_tmpl_16.rs
- src/mc_tmpl_8.rs
I had these from when I was working off of #322.  They're now rebased on `main` and I want to get them merged before I forget too much about them.  After deduplicating `mc.rs`'s `fn`s with `BitDepth` generics, I'll deduplicate its `fn` ptrs with type erasure.
> `fn {{,w_}avg,mask,blend{,_v,_h}_{c => rust}`: Deduplicate w/ generics and cleanup/re-translate

- src/msac.rs
eca5a4addd48b54b7005e040b82137ab2e1a66d6 reverts 4bea6a04b09ffae62530d04c46791f0f1f4384f3 and 908703ea1bc70a3de24e2c130fe72be6a64cb006 from #310.  The rest of the commits simplify the unsafe by passing the extra `cdf.len()` arg so an `assert!` isn't needed and the unsafety is extremely simpler, as well as passing `&mut` instead of `*mut`, which seems to work (if not, I can remove this commit).
> `MsacContext::symbol_adapt16`: Re-virtualize and simplify by passing extra args

- src/intra_edge.h
- src/intra_edge.rs
Backport performance improvement from dav1d 1.2.1. Partially solves #286.
Use 8 bits to represent EdgeFlags instead of 32 bits
> Shrink intra_edge structs

- src/looprestoration.rs
- src/looprestoration_tmpl_16.rs
- src/looprestoration_tmpl_8.rs
This is the first bit of bitdepth deduplication that I've touched that needs to call into bitdepth-specific asm. ~~I used an extension trait to handle this. It's more boilerplate than I'd like, but that can probably be addressed with a macro later if needed. @kkysen let me know if you have a better suggestion.~~ An extension `trait` with associated `const`s in now used.  See https://github.com/memorysafety/rav1d/pull/341#pullrequestreview-1559981624 for an incoming follow-up.
> `fn dav1d_sgr_filter1_neon`: Deduplicate w/ generics

- src/ipred_tmpl_16.rs
- src/ipred_tmpl_8.rs
Some recent PR added or removed some uses and introduced arch-specific import warnings, so I just moved them the single functions they're used in.
> Fix arch-specific unused import warnings

- Cargo.toml
Set `default-run = "dav1d"` so that `cargo run` still runs `dav1d` like it did before adding the `seek-stress` binary.
> Set `default-run = "dav1d"` so that `cargo run` still runs `dav1d` like it did before

- src/mc_tmpl_16.rs
- src/mc_tmpl_8.rs
I didn't deduplicate these ones since they're so trivial and because I'll make `ss_{hor,ver}` `const` generics once I type erase them so that I can just do `w_mask_c_erased::<true, true>`, etc.
> `fn w_mask*c`: Make `ss_{hor,ver}` args `bool`s

- src/mc.rs
- src/mc_tmpl_16.rs
- src/mc_tmpl_8.rs
This is the last of the `mc` `fn`s to deduplicate besides the `*dsp_init*` ones, which I have to do after type erasing the `fn` ptrs.
> `fn {warp_affine_8x8{,t},emu_edge,resize}_{c => rust}`: Deduplicate w/ generics

- include/common/bitdepth.rs
- src/looprestoration.rs
As discussed with @randomPoison in #341, this way of `match`ing on `enum BPC` is a bit cleaner, since it co-locates the bitdepth versions for each `fn`, similarly to the C declarations with `BF`, and it doesn't have to leave a `pub trait`.  Importantly, though, it lets us move conversions from safe to unsafe constructs to inside these wrapper dispatching functions, like is done in 281a8dea3ee8ab84406bbdd49c9eaa70a6233cef.  This way we don't need these conversions to raw pointers at all call sites, just once.  As we continue to clean up these functions further, that will get even more useful.  For now I just cleaned up the trivial ones, like where an array in the caller is passed `.as(_mut)_ptr()`.
Also, we know this is also zero-cost since it successfully links with only one bitdepth …
> `src/looprestoration.rs`: Switch associated `const` `fn` ptrs to compile-time `BPC` `match`es for greater flexibility

- Cargo.lock
- Cargo.toml
- include/common/bitdepth.rs
- lib.rs
- src/decode.rs
- src/looprestoration.rs
Deduplicate the init functions using the `BPC` enum matching approach introduced in #355. I used a macro to generate the wrapper functions to cut down on boilerplate. There a couple of asm functions that don't have both 8bpc and 16bpc versions, so those are handled differently.
> `looprestoration`: Dedup init fns w/ generics

- src/obu.c
- src/obu.rs
obu: validate some timing values
> Backport compliance check from dav1d 1.2.1

- src/itx.rs
- src/itx_tmpl_8.rs
Just removing some unused imports that were causing warnings.
> Remove unused imports

- Cargo.lock
- Cargo.toml
- rust-toolchain.toml
I've noticed a bunch of random download failures of `https://index.crates.io/3/s/syn`, fairly often now to the point where something must be wrong rather than just random network failures.  Since this is related to the newly released sparse registry (`index.crates.io`) and we're using a `nightly`, I thought updating it might help things, so we'll see.
In updating, `proc-macro2` as used by `c2rust-bitfields-derive` failed to build due to a Rust feature being removed, so I update the `c2rust-bitfields` dependency, too, and that worked.
Here's [an example error in CI](https://github.com/memorysafety/rav1d/actions/runs/5959704961/job/16165864698?pr=379):
```
Updating crates.io index
warning: spurious network error (3 tries remaining): [28] Timeout was reached (Operation too slow. Less than …
```
> Update to the latest nightly

- src/decode.rs
This cleans up the majority of `fn decode_sb`, all the simple cleanups that comprise most of the changes.  There are still some things I want to change, but those are more involved, so I want to keep them as separate PRs.
For example, I want to change some of the `enum` sizes separately (`enum`s that were translated as type aliases).  And I want to try to turn `EdgeNode` into an `enum` or at least `union`, as it can be an `EdgeTip` or `EdgeBranch`.  And some other small but trickier things.
> `fn decode_sb`: Cleanup majority of `fn`

- src/intra_edge.rs
I'll work on the safety of the `Edge*` types once I do initial cleanup for their functions.
> `fn init_edges`: Cleanup

- src/looprestoration.rs
This uses the bitdepth-specific `fn`s directly rather than creating bitdepth-dispatching shim `fn`s.  This eliminates the extra call, which is bad for performance (not measured here, but similar shim calls were bad for perf since the cross-language asm call is not inlined into the shim.
See https://github.com/memorysafety/rav1d/pull/367#discussion_r1289774310 and other comments on that PR.
~~This also removes the now-unused `paste!` dependency.~~  Though if we want to avoid repeating all the `match BD::BPC { ... }`s, which will come up in other init `fn`s as well, we can add a wrapper macro that uses `paste!`, similar to the `decl_looprestoration_bd_fn!` macro removed here, but without any shim generation.
> `src/looprestoration.rs`: Avoid extra shim calls in `fn` ptrs

- include/common/bitdepth.rs
- src/cdef.rs
- src/cdef_tmpl_16.rs
- src/cdef_tmpl_8.rs
- src/loopfilter.rs
- src/loopfilter_tmpl_16.rs
- src/loopfilter_tmpl_8.rs
- src/looprestoration.rs
This centralizes all of the type-erased type aliases (for already type-erased modules; for the rest we can do this as we type-erase them).  These are named `Dyn{Pixel,Coef}` so there can't be any confusion with existing bitdepth-specific `pixel` and `coef`.  I also made them `#[repr(transparent)]` newtypes instead of just type aliases so we can't accidentally just use `libc::c_void` instead, so this makes all the signatures a lot easier to understand now instead of having a ton of `libc::c_void`s that could be multiple things.
There are also type aliases for `LeftRowPixel{,2px}`, which can be used with `BD::Pixel` or `DynPixel`.  `LeftRowPixel<DynPixel>` aka `[c_void; 4]` is different from the previous alias of just `libc::c_void`, but they're both behind `*const` ptrs and so passing them …
> Centralize type-erased types

- src/intra_edge.rs
I was also trying to change `struct ModeSelMem` to contain a slice.  It's a local type, so we can change it, but it causes lifetime issues.
> `src/intra_edge.rs`: Cleanup

- src/decode.rs
- src/qm.rs
This is half the way to safety.  I still need to make them non-`mut`, which is much more difficult (but should be doable).
> `static dav1d_qm_tbl`: Store slices instead of raw ptrs

- src/qm.rs
This will let the tables be generated rather than mutated next.
> `fn {transpose,untriangle,subsample}{,d}`: `const`-ify

- src/decode.rs
- src/lib.rs
- src/mem.rs
- src/obu.rs
- src/thread_task.rs
A few are left, the arch-specific ones/ones not in `libc` as well as `pthread_create` since I need to make the `fn` ptr safe first.
> `fn pthread_*`: Deduplicate declarations into `use` imports

- src/decode.rs
I had to do the unsafe cast to `AtomicI32` in 708315c8b688c812969e59fca748e79427a29a66 since making the field itself `AtomicI32` requires us to remove the `#[derive(Copy)]`, which has to be done recursively, so I'd like to do that in its own PR.
> `fn dav1d_decode_frame`: Cleanup and make mostly safe

- src/decode.rs
Addresses performance issue by disabling println! statements.
> `fn decode_sb`: Add back condition accidentally removed in #382

- src/decode.c
- src/lib.c
- src/mem.c
- src/obu.c
- tests/libfuzzer/dav1d_fuzzer.c
- tests/libfuzzer/main.c
- tests/seek_stress.c
- tools/input/ivf.c
- tools/output/y4m2.c
- tools/output/yuv.c
The relooper algorithm `c2rust transpile` uses to translate `goto`s makes a mess of the control flow to the point where it takes a long time to untangle the state machines into normal control flow.  Most of these `goto`s use fairly simple control flow, being mostly used for error cleanup.  So they can be removed by either inlining (if the `goto` is very short), outlining and then calling the outline function at each `goto`, or in a few cases, just reorganize the structured control flow a little bit.
I intend to re-transpile and merge back these `goto`-less functions, as I'm pretty sure that'll be easier than untangling the relooper state machines (I usually end up just re-translating by hand, but some of these functions are quite long).  I'll probably add this to this same PR, but I want …
> Remove error/cleanup-like `goto`s in C

- src/looprestoration.rs
Use 64-bit arithmetic to compute indices to avoid repeated bound checks. Performance regression was observed after #368
> `fn wiener_rust`: Fix perf regression

- src/cdef_tmpl_16.rs
- src/cdef_tmpl_8.rs
- src/decode.rs
- src/filmgrain_tmpl_16.rs
- src/filmgrain_tmpl_8.rs
- src/lf_apply_tmpl_16.rs
- src/lf_apply_tmpl_8.rs
- src/lib.rs
- src/loopfilter_tmpl_16.rs
- src/mc.rs
- src/obu.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/wedge.rs
- tests/seek_stress.rs
This is a repeat of #166 after #425, since #425 heavily reduced indentation, making a lot of the regexes from #166 now work.
> Cleanup trivial redundant casts after removing most `goto`s

- src/cdef.rs
- src/decode.rs
- src/itx.rs
- src/lib.rs
- src/obu.rs
- src/refmvs.rs
- src/thread_task.rs
Some of these are themselves part of other constants like `{FRAME,TILE}_ERROR`, but it's easier to fix all of these first.
> `const {u,i}N::{MIN,MAX}`: Deduplicate

- src/decode.rs
- src/internal.rs
- src/thread_task.rs
This involved some heavy iterator code to avoid bounds checks as much as possible.  One especially, 08f1a37caaa6da368108f931ab6b974198528f60, I want to benchmark.  @fbossen, how have you been doing that?
> `fn dav1d_decode_frame_init_cdf`: Cleanup and make mostly safe

- src/decode.rs
- src/lf_mask.rs
I cleaned up a large chunk of this already, but it's getting very long, and there's some more cross-cutting changes I want to make before finishing cleaning this up, like `c_int` ABI-compatible `bool` and `usize`-wrappers and some changes to the memory allocation functions.
> `fn dav1d_decode_frame_init`: Cleanup part 1

- src/ipred.rs
- src/ipred_tmpl_16.rs
- src/ipred_tmpl_8.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
I wasn't able to remove one of the `Option`s because there's actually a bit of code that checks if that field is `None` in `dav1d_submit_frame`, and it wasn't clear to me if there was another flag that we can use as an appropriate sentinel.
> `struct Dav1dIntraPredDSPContext`: Remove (most) `Option`s

- .gitignore
- retranspile.sh
- src/lib.rs
I seem to have missed this `fn` in #425.
> `fn dav1d_open`: Re-transpile after removing `goto`s

- src/decode.rs
> `fn dav1d_decode_frame_init`: Fix perf by using `.iter()` instead of `.into_iter()`

- src/obu.rs
- src/thread_task.rs
- tools/input/annexb.rs
- tools/input/section5.rs
Most of these were marked unused since they were lost during `case` to `match` transpilation.
> `enum {Task,ObuMeta,Dav1dObu,Dav1dFrame}Type`: Symbolicate `match`/`case` uses

- src/tables.rs
These are initialized with designated initializers in C, which are much easier to read/understand for these tables, so I approximate that here.  Maybe we'll use an enum map crate later, but this is good enough for now.
> `static dav1d_{comp_inter_pred_modes,txtp_from_uvmode}`: Initialize like designated initializers

- src/qm.rs
- src/wedge.rs
@randomPoison, do you think I should move `const fn transposed` somewhere else more general?  I may also add other similar `const fn` utilities, like an integral `for` loop macro (since `for` loops don't work in `const fn`s).
> `fn transpose`: Replace with calls to `const fn transposed`

- src/lib.rs
- src/wedge.rs
This also removes `fn dav1d_init_interintra_masks` as it's now entirely empty.
> `static ii_{,non}dc_mask*`: Make non-`mut` and safe

- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/wedge.rs
No uses check for null, so we can use empty slices as the default instead of `None`, which requires wrapping everything in `Option`.  For the pure Rust paths (no asm), this means we can avoid a `.unwrap()`.  This is slightly less "safe" for the asm paths, since if there's an error, it'll use a pointer to static memory instead of a null pointer that would error right away, but we have tests for that and the pure Rust path will bounds check (eventually).
> `static dav1d_ii_masks`: Use empty slices instead of `None` for defaults

- src/wedge.rs
This simplifies the code a lot (as the multiplications are now done by the compiler) and also more easily tells the compiler that the inner arrays are exclusive (so we can have multiple `&mut`s).  It also makes the length of the slices clear, and also doesn't actually do any slicing (which can't be done in `const fn`s).
> `static wedge_masks_*`: Move the array length multiplication to outer arrays

- src/wedge.rs
`fn fill2d_16x2` is difficult to make `const` directly since it takes `&'static mut` args that are referenced in the return value.  I'm going to switch to a different API that can make this work, but these are some initial steps to prepare for `const`ification before that.
> `fn fill2d_16x2`: Prepare for `const`ification

- src/wedge.rs
`fn fill2d_16x2` as it was couldn't get rid of the `&mut`s to make it a `const fn` and remove the `static mut`s for the `static wedge_masks_*`s, since it took and store (in other statics) references to those statics.  This separates the steps into creating the statics and then referencing them in separate functions/methods, and it also significantly simplifies things as well.
> `struct WedgeMasks`: Encapsulate `static wedge_masks_*`s and `fn fill2d_16x2` in a `struct`

- src/wedge.rs
This is the same as #475, but I accidentally forgot to open #479 (which I just did) earlier so I merged #475 into the wrong branch, so I have to redo this one.
> `struct WedgeCodeBook`: Encapsulate `static wedge_codebook_16_h*w` to simplify `fill!`

- Cargo.lock
- Cargo.toml
- src/wedge.rs
This makes them real `enum`s instead of just integer constants.  To replicate the `const N_*: usize`s, I used `strum`'s `#[derive(EnumCount)]`.
This isn't super necessary for this file, but I wanted to get the hang of converting the integer constant "enum"s to real `enum`s, as it is necessary for performance in other places (due to the stronger `enum` guarantees), and this is an easy place to do as I just finished completely cleaning up the file.
> `enum Wedge{Direction,MasterLine}Type`: Make `enum`s

- src/cdef_apply_tmpl_16.rs
- src/cdef_apply_tmpl_8.rs
- src/cdf.rs
- src/decode.rs
- src/internal.rs
- src/lf_apply_tmpl_16.rs
- src/lf_apply_tmpl_8.rs
- src/lib.rs
- src/log.rs
- src/lr_apply_tmpl_16.rs
- src/lr_apply_tmpl_8.rs
- src/obu.rs
- src/picture.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/thread_task.rs
I replaced these with `c_void`s a while ago before we figured out the type-erasure stuff and added `struct Dyn{Pixel,Coef}`.  For clarity, it's much better to use the specific types.
> `struct Dyn{Pixel,Coef}`: Use instead of `c_void` for clarity

- src/cdf.rs
- src/cpu.rs
- src/decode.rs
- src/lib.rs
- src/log.rs
- src/obu.rs
- src/picture.rs
- src/ref.rs
- src/refmvs.rs
- src/thread_task.rs
The `#[no_mangle]`s that are remaining are:
* Bitdepth-specific `fn`s (many of these)
* `*_c` `fn`s (many of these)
* `DAV1D_API` `fn`s, which must remain `#[no_mangle]`
* `static`s used by asm, which must remain `#[no_mangle]`
* `fn`s not in the `rav1d` library (e.x. in `tools/`), which are lower priority
> `#[no_mangle] fn`s: Deduplicate most non-bpc, non-`*_c` declarations into `use` imports

- tests/seek_stress.rs
- tools/dav1d.rs
- tools/dav1d_cli_parse.rs
- tools/input/input.rs
- tools/output/output.rs
There are some non-trivial things with type-erased/dynamic types that I've left as is for now.
> `tools/`: Deduplicate everything trivial

- src/cdef_apply_tmpl_16.rs
- src/cdef_apply_tmpl_8.rs
- src/cdef_tmpl_16.rs
- src/cdef_tmpl_8.rs
- src/decode.rs
- src/fg_apply_tmpl_16.rs
- src/fg_apply_tmpl_8.rs
- src/filmgrain_tmpl_16.rs
- src/filmgrain_tmpl_8.rs
- src/ipred_prepare_tmpl_16.rs
- src/ipred_prepare_tmpl_8.rs
- src/ipred_tmpl_16.rs
- src/ipred_tmpl_8.rs
- src/itx_tmpl_16.rs
- src/itx_tmpl_8.rs
- src/lf_apply_tmpl_16.rs
- src/lf_apply_tmpl_8.rs
- src/lib.rs
- src/loopfilter_tmpl_16.rs
- src/loopfilter_tmpl_8.rs
- src/lr_apply_tmpl_16.rs
- src/lr_apply_tmpl_8.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/thread_task.rs
This should be the last of the `#[no_mangle]` `fn`s that aren't `DAV1D_API`, and the only `extern "C" {}` `fn`s imported should be asm `fn`s.
Note that in b62e49e the existing signature was wrong (it used `*mut c_void`) so I have to remove the casts to `*mut c_void`.
> `fn dav1d_*_{8,16}bpc`: Deduplicate declarations into `use` imports

- Cargo.lock
- Cargo.toml
- src/ipred_prepare.rs
`#[derive(c2rust_bitfields::BitfieldStruct)]` doesn't generate `const fn`s (https://github.com/immunant/c2rust/issues/1027), so it can't be used in a `const` block to initialize a `static`.  Thus, the `static` has to made `mut` and `unsafe` and initialized at runtime.
I opened https://github.com/immunant/c2rust/issues/1027 and looked into making the generated `fn`s `const`, but they used a lot of `trait`s, which can't contain `const fn`s, so it seemed like non-trivial work.  I also tried looking for other off-the-shelf bitfield crates, but they all either didn't support `const fn`s or still relied on `trait`s within them, and thus only could create `const fn`s with `nightly` features.
Thus, I rolled my own `macro_rules!` macro, `bools_bitfield_struct!` that generates `const fn`s.  The …
> `static av1_intra_prediction_edges`: Make non-`mut` by replacing `#[derive(BitfieldStruct)]` with `bools_bitfield_struct!` for `const fn`s

- Cargo.lock
- Cargo.toml
- src/arm/cpu.rs
- src/cdef_tmpl_16.rs
- src/cdef_tmpl_8.rs
- src/cpu.rs
- src/filmgrain_tmpl_16.rs
- src/filmgrain_tmpl_8.rs
- src/ipred_tmpl_16.rs
- src/ipred_tmpl_8.rs
- src/itx_tmpl_16.rs
- src/itx_tmpl_8.rs
- src/loopfilter_tmpl_16.rs
- src/loopfilter_tmpl_8.rs
- src/looprestoration.rs
- src/mc.rs
- src/msac.rs
- src/refmvs.rs
- src/x86/cpu.rs
I wanted to test out using `bitflags!` for things that were manually bitflags, as there are some other uses of this, too.
In hindsight, I think I could've also made #497 just use `bitflags!` instead.
> `struct CpuFlags`: Make `bitflags!`

- Cargo.lock
- Cargo.toml
- build.rs
- lib.rs
- src/arm/cpu.rs
- src/cpu.rs
- src/lib.rs
- src/x86/cpu.rs
This makes all of the cpu detection code fully safe and fully in Rust now.
For `x86`, `x86_64`, and `aarch64`, the stable `is_{x86,aarch64}_feature_detected!` macros are used, and for `arm`, the unstable `is_arm_feature_detected!` macro is used.  Thus, `#![feature(stdsimd)]` needs to be enabled on `arm`, but on the other hand, `is_arm_feature_detected!` is probably more correct and stable than what the C was doing, and we also get support for `android` this way (we previously didn't translate this part).
To detect `CpuFlags::SLOW_GATHER`, which looks for specific CPUs, we use the `raw-cpuid` crate instead of `cpuid.asm`.
> `fn dav1d_{init_cpu,get_cpu_flags_{x86,arm}}`: Make safe

- .gitignore
- include/common/frame.rs
- include/dav1d/headers.rs
- include/dav1d/picture.rs
- src/cdf.rs
- src/decode.rs
- src/env.rs
- src/fg_apply_tmpl_16.rs
- src/internal.rs
- src/lf_mask.rs
- src/lib.rs
- src/obu.rs
- src/picture.rs
- src/recon_tmpl_16.rs
- src/recon_tmpl_8.rs
- src/refmvs.rs
- src/tables.rs
- src/thread_task.rs
- src/warpmv.rs
This adds the generic `struct DRav1d<R, D>` that stores both the `R` `Rav1d*` and `D` `Dav1d` types.  These are meant to be stored in ref-counted `Rav1dRef`s.  This allows us to store pointers to both the `Rav1d*` and `Dav1d*` versions in their containing types, mainly `{D,R}av1dPicture`.  During `DAV1D_API`s, `.update_rav1d()` is called, which updates the `rav1d` version to match the `dav1d` version for internal `rav1d` use.  And after parsing these types (after which no more modifications are done), we call `.update_dav1d()` so that the `dav1d` version is always up-to-date when returning it from `DAV1D_API`s.
There are 5 types that are like this:
* `{D,R}av1dSequenceHeader`
* `{D,R}av1dFrameHeader`
* `{D,R}av1dContentLightLevel`
* `{D,R}av1dMasteringDisplay`
* `{D,R}av1dITUTT35`
Of …
> `struct DRav1d<R, D>`: For ref-counted types, store both and update them when needed

- include/dav1d/picture.rs
- lib.rs
- src/cdf.rs
- src/data.rs
- src/decode.rs
- src/error.rs
- src/internal.rs
- src/lib.rs
- src/mem.rs
- src/obu.rs
- src/picture.rs
- src/refmvs.rs
- src/thread_task.rs
- tests/seek_stress.rs
- tools/dav1d.rs
- tools/dav1d_cli_parse.rs
- tools/input/annexb.rs
- tools/input/input.rs
- tools/input/ivf.rs
- tools/input/section5.rs
- tools/output/md5.rs
- tools/output/output.rs
- tools/output/y4m2.rs
- tools/output/yuv.rs
This adds an `enum Rav1dError`, which is a narrowed version of the overloaded `c_int` that `dav1d` uses for errors.  `dav1d` uses `errno` values for errors (except for `-1` sometimes).  This PR does the same (the same constants), but with `enum Rav1dError` instead of `c_int`.  Since `Rav1dError` has a niche at `0`, this makes `type Rav1dResult<T = ()> = Result<T, Rav1dError>` equivalent to how `dav1d` uses `c_int`, with `0` meaning no error, negative values meaning an error, and positive values meaning a stateful result.  `struct Dav1dResult` encapsulates this in Rust using a `#[repr(transparent)]` new-type, and there are efficient conversions between `{D <=> R}av1dResult`.
`Rav1dResult` is used as the return type for all error-returning `fn`s that are not part of the `#[no_mangle] extern …
> `enum Rav1dError`: Convert internal error-handling to use `Rav1d{Error,Result}`

- .github/workflows/test.sh
Now we'll be able to see actual errors in CI, which is very important for flaky tests and macOS (in particular, #513 is failing on macOS and I'm not sure why, and #514 is failing on `aarch64` but I can't reproduce it locally).
> `test.sh`: Pass `--print-errorlogs` to `meson test` so `stderr` is saved in `testlog.txt`

- include/common/validate.rs
- lib.rs
- src/data.rs
- src/lib.rs
- src/log.rs
- src/picture.rs
This translates the `validate_input!` macro to (safe) Rust and deduplicates all of its expanded uses.
It also moves null checks that were done with the macro to before those pointers were dereferenced, as some earlier dereferences were added in the `dav1d` to `rav1d` conversions.  Now the `validate_input!` null check happens in the `fn dav1d_*` and safe references are passed to the `fn rav1d_*`, which no longer need to do any null checks.
I also made the `validate_input!` error message a bit more Rusty and also include the source location, which I found useful in debugging things, and seems generally useful for an error message.
> `validate_input!`: Translate macro and all of its uses

- src/decode.rs
- src/internal.rs
- src/lf_mask.rs
- src/lr_apply_tmpl_8.rs
- src/obu.rs
`Av1RestorationUnit` is only 10 bytes, just 2 more than the 8 bytes of a pointer, which also comes with indirection.  Thus, this is likely more performant, and it get rid of nasty lifetimes and shared mutability.
The `lr` array var of `*const Av1RestorationUnit` `const` and just used locally, so the change there is simple.
The `lr_ref` array field is `*mut Av1RestorationUnit`, so `mut` and a field.  However, the `mut` is not needed, so the change becomes simple.
> `struct Av1RestorationUnit`: Make `Copy` and change fields and vars to store by value, not pointer

- Cargo.lock
- Cargo.toml
- src/looprestoration.rs
This just cleans up `Cargo.toml`, which was still mostly generated by `c2rust transpile`.  The package is now named `rav1d` (like the `lib` was already changed to) and I set the version to `0.2.0` for future publishing (and so things like #519 don't need to patch it).  The existing `rav1d` crate is at `0.1.0`, and so since we plan on publishing there, we can start at `0.2.0`.  I also fixed some doc comments so `cargo test` can run.
> `Cargo.toml`: Cleanup

- include/common/bitdepth.rs
- src/internal.rs
- src/lib.rs
- src/recon.rs
- src/thread_task.rs
This adds the generic `BitDepth` `union` type `BitDepthUnion` that can resolve, in a `BitDepth`-generic `fn`, to a `BitDepth`-dependent type.  This is done through `trait BitDepthDependentType`, which has a GAT.  Thus, we're able to abstract over `union`s that store storage for both `BitDepth`s and select the right one in a bitdepth `fn`.  Previously, I had to do this with unchecked ptr casts, but that wouldn't work when things got more cleaned up and the arrays were used directly.  The API in `trait BitDepth`, the `fn select*` methods, is still `unsafe` since `union` field accesses are `unsafe`, but it could easily be adapted to a safe version using `enum`s (which would runtime-check the correct `BitDepth` was used) or even `struct`s (which could just separately store both versions, if …
> `union BitDepthUnion`: Add a generic `BitDepth` `union` type that can resolve to a `BitDepth` dependent type

- src/thread_task.c
- src/thread_task.rs
> backport from `dav1d` 1.2.0: threading: Ensure passing the correct retval to decode_frame_exit

- build.rs
This does some general cleanup and refactoring of `build.rs`.  Some as simple such as putting everything in `mod asm` so we don't need `#[cfg(feature = "asm")]` everywhere.  I also changed the style to more closely match `meson.build` (e.x. `Define::bool` and `Define::new` corresponding to `.set` and `set10` vs. just writing out the whole defines every time.  It also unifies the `fn build_nasm_files` and `fn build_asm_files` to one `fn main` with target checks throughout (again, more similar to `meson.build`).  This PR also keeps the same output/behavior as before, though I did notice some divergences from `meson.build` that I'll fix in the next PR.
> `build.rs`: Cleanup and refactor

- build.rs
`build.rs` diverged in behavior from `meson.build` for some things; this fixes them to match `meson.build`.  `meson.build` still does things somewhat differently, as it always generates `config.h` and generates `config.asm` for `nasm` (x86* only), but `dav1d` needs `config.h` for C code and `*.S` `as`-style asm, while we only need it for the asm.  Thus, I think it's okay that we only generate either `config.h` or `config.asm`.  There are also some remaining configurable options in `meson.build` that should probably turn into `cargo` features, but we should be able to add those later.
> `build.rs`: Align to `meson.build`

- build.rs
Previously `build.rs` wouldn't re-run if any asm was changed, whether in a PR like #534 or in a backporting PR, and this would often cause segfaults after unless we `cargo clean`ed or ran `touch build.rs`.  This uses `cargo:rerun-if-changed=` to tell `cargo` what other sources we're using that it should use to determine if `build.rs` needs to rerun.  Unfortunately, this can't do fine-grained caching at all and `nasm` if fairly slow, but that's okay, as at least it should always be correct now.
> `build.rs`: Emit `cargo:rerun-if-changed=` for every asm file

- src/internal.rs
- src/lib.rs
- src/obu.rs
This cleanup included making some fields of `struct Rav1dContext` `bool`s.
Also, cleaning up this `fn` further runs into borrow checker issues that aren't easily fixed.  We'll need to split up `struct Rav1dContext` so that it and one of its fields can be passed as `&mut`.
> `fn output_image`: Cleanup

- src/filmgrain.rs
Mostly cleaning up `fn sample_lut` and making it safe.
> `src/filmgrain.rs`: Cleanup part 3 (mostly `fn sample_lut`)

- .gitignore
- include/dav1d/headers.rs
- src/arm/32/filmgrain.S
- src/arm/32/filmgrain16.S
- src/arm/64/filmgrain.S
- src/arm/64/filmgrain16.S
- src/arm/asm-offsets.h
- src/fg_apply.rs
- src/filmgrain.rs
- src/x86/filmgrain16_avx2.asm
- src/x86/filmgrain16_avx512.asm
- src/x86/filmgrain16_sse.asm
- src/x86/filmgrain_avx2.asm
- src/x86/filmgrain_avx512.asm
- src/x86/filmgrain_common.asm
- src/x86/filmgrain_sse.asm
As discussed in #534, changing the asm at all means we lose upstream testing, review, and other improvements.  Given that e27877e5f, which made `{D <=> R}av1dFilmGrainData` conversions, had no perf regressions, this commit reverts back to that behavior.
The asm changes were reverted with `git checkout main -- src/x86/* src/arm/*`, where `main` is bb68fb8.
I'm doing this as a follow-up PR after all of the intermediary ones to avoid a ton of merge conflicts.  So once this is approved, I can merge all of the PRs up to and including this one.
This PR also fixes a alignment bug in `dav1d` surfaced/triggered by this asm reversion, which places `Dav1dFilmGrainData`s on the stack in a different place (i.e. alignment) than e27877e5f did.
x86 asm uses `psrad` on a pointer to …
> `struct {D,R}av1dFilmGrainData`: Revert asm changes from #534 and fix a `dav1d` alignment bug

- include/dav1d/headers.rs
- lib.rs
- src/decode.rs
- src/enum_map.rs
Using an `enum` map for these is a lot more clear and harder to mess up accidentally than manually casting the `enum` keys to `usize`, making sure all variants are initialized, etc.  Existing `EnumMap` implementations either weren't `const`-compatible, which we need to initialize `static`s like this, and/or weren't quite zero-overhead.  This relatively simple version I made based on the existing `as usize` approach and existing `EnumMap`s works at `const`-time and is zero-overhead when I checked it in godbolt.  
The downside is a bit of extra verbosity in the type paremeters and having to `impl DefaultValue` for the value type.  The former isn't an issue; just annoying.  For the latter, not all types have a default value that makes sense, but all the places I've seen this pattern used in …
> `struct EnumMap`, `enum_map!`: Add a `const`-compatible `enum` map and use it for `static ss_size_mul`

- lib.rs
- src/fg_apply.rs
- src/filmgrain.rs
- src/wrap_fn_ptr.rs
This adds the macro `wrap_fn_ptr!` that creates a new-type wrapper of a `fn` ptr and `impl`s` `DefaultValue` for it, with the default value being a `fn` that does nothing and just calls `unimplemented!()`.  This default value isn't actually ever used, but is needed for `enum_map!` to work, which will be done in the next PR.
Also, very importantly, by new-typing the `fn` ptrs, we can make the raw `fn` ptr private
and only expose a `fn call` method that does the type-erasing bitdepth casts,
making calls more idiomatic and safer.
This PR then uses this approach for `mod filmgrain`'s `struct Rav1dFilmGrainDSPContext`'s `fn` ptrs.  We should do this for all of the other ones, but we'll get to them later.
> `wrap_fn_ptr!`: Add a macro defining a wrapped `fn` ptr with a `DefaultValue` and use it for `struct Rav1dFilmGrainDSPContext`

- include/dav1d/headers.rs
- src/fg_apply.rs
- src/filmgrain.rs
- src/internal.rs
This creates a new `enum`, `enum Rav1dPixelLayoutSubSampled`, that is a subset of `enum Rav1dPixelLayout`, the subset used in `struct Rav1dFilmGrainDSPContext`'s arrays as keys/indices.  This allows us to idiomatically use `EnumMap` for those arrays.
> `enum Rav1dPixelLayoutSubSampled`: Add separate `enum` for use in `EnumMap`s for `Rav1dFilmGrainDSPContext`

- src/fg_apply.rs
- src/filmgrain.rs
This makes `{uv,is_uv,uv_pl}` args `bool`s, casting to `c_int`/`usize` for FFI/indexing.
By making the arg a `bool` in `fn fguv_32x32xn_rust` and doing the `as usize` cast inside the `fn`[1], (4[2]) bounds checks of `uv` into length-2 arrays are eliminated, fixing a perf regression.  This was checked on `aarch64-unknown-linux-gnu` asm.
[1] Doing the `bool` to `usize` cast inside of the `add_noise_uv` closure didn't make a difference in the number of bounds checks.
[2] 27 => 23 `bl core::panicking::panic_bounds_check`s
> `fn fguv_32x32xn_*`: Make `{uv,is_uv,uv_pl}` args `bool`s, fixing a perf regression due to bounds checks

- include/common/bitdepth.rs
- src/filmgrain.rs
This elides bounds checks from indexing with `val` by clipping the index to a valid one.  Initially, I copied #558's approach, which uses `cmp::min(val, scaling.as_ref().len() - 1)`, and this removes 3 bounds checks.  But since the scaling size is a `const` and is `1 << BD::SCALING_BITS`, we can just truncate the other bits with `&`, which avoids a `csel` and 2 more bounds checks.
> `fn fguv 32x32xn_rust`: Elide `val` bounds checks, fixing a perf regression

- src/filmgrain.rs
The C `NOINLINE`s were originally on the `*_c` functions, which are called through `fn` ptrs and makes sense. The `fn *_rust`s are called only by the `fn *_c_erased`s, which are called through `fn` ptrs, so we were accidentally forcing an extra `fn` call due to mixing this up.
I'm not sure if this noticeably hurt perf, but it's not what the C is doing and seems like it would hurt perf, so we should fix this.
> `fn {generate_grain_uv,fguv_32x32xn}_{rust,c_erased}`: Put `#[inline(never)]` on the `fn *_c_erased`s, not the `fn *_rust`s

- lib.rs
- src/filmgrain.rs
- src/recon.rs
Since these bitdepth-specific `fn`s are Rust `fn`s, not asm `fn`s, we can't use `bd_fn!` in the same way, so when `mod recon` got deduplicated, it broke compiling for a single bitdepth. If we just compile both bitdepths for these `mod`s and rely on dead code elimination, it works again. And once we deduplicate these `mod`s, it will all be for naught since they'll be generic instead.
> `mod {cdef,{cdef,lf,lr}_apply}_tmpl_{8,16}`: Always compile both and dead-code eliminate

- Cargo.toml
- lib.rs
- src/recon.rs
This significantly improves code generation and optimization. In C, translation units correspond to each `*.c` file, and thus things are deliberately grouped together. In Rust, codegen units are chosen with a heuristic and functions are assigned to a codegen unit (passed to LLVM). Thus, to ensure related functions are in the same codegen unit (and are thus inlineable), we should set this to 1. This will also make optimization much more reliable, since a far away change can't suddenly affect an optimization elsewhere.
We probably also want to look at enabling LTO (though we'll need to enable LTO for `dav1d` for equivalent comparisons).
> `Cargo.toml`: Set `codegen-units = 1` for `release`

- lib.rs
- src/assume.rs
- src/filmgrain.rs
This elides the luma bounds check when indexing into `buf_y` by using `unsafe`, but still also statically checking the `unsafe`'s correctness.  Going forward, I'll focus on perf when asm is enabled, as the C/Rust-only perf is not as important, but I had already worked out how to elide this bounds check before that.
> `fn generate_grain_uv_rust`: Elide luma bounds check

- include/common/bitdepth.rs
- include/common/intops.rs
This removes an `unsafe {}` and downgrades the `assert!` to a `debug_assert!` by using `ToPrimitive`, as the `assert!` is not always optimized out.
> `fn clip`: perf: Remove an `assert!`

- rust-toolchain.toml
`nightly-2023-08-24` => `nightly-2023-11-16`.
I'm curious how this affects the benchmarks since it did last time.  Also, some potentially useful APIs have been stabilized.
> `rust-toolchain.toml`: Update to the latest `nightly` 

- include/dav1d/headers.rs
- src/decode.rs
- src/enum_map.rs
- src/filmgrain.rs
This has to be a macro until `#![feature(const_generic_exprs)]` lands.
> `enum_map_ty!`: Add a macro to avoid having to hardcode the `N` in `EnumMap` by using `EnumCount`

- .github/workflows/build-and-test-aarch64.yml
Arm7 and x86 debug builds run with a timeout multiplier of 2. Use the same setting for aarch64 to avoid timeouts on Github runners.
> CI: Increase timeout multiplier for aarch64

- src/lf_apply.rs
Incorrect slice length introduced in 73e6e6e breaks Argon tests.
> `fn backup_lpf`: Fix incorrect pixel_copy

- include/common/bitdepth.rs
- lib.rs
- src/filmgrain.rs
- src/wrap_fn_ptr.rs
We're already matching the `fn` signature with a macro, so generating the `decl_fn!` macro inside is pretty trivial, and this way we don't have to write all of the `decl_*_fn!` macros ourselves.
This also adds documentation for:
* `trait HasFnPtr`
* `struct WrappedFnPtr`
* `wrap_fn_ptr!`
* `bd_fn!`
> `wrap_fn_ptr!`: Generate a `decl_fn!` macro inside; also document macros

- src/filmgrain.rs
- src/ipred.rs
- src/recon.rs
- src/wrap_fn_ptr.rs
This also reworks `wrap_fn_ptr!` to declare `Fn` as a newtype `struct` inside the macro rather than a type alias to the generic `WrappedFnPtr`, which needed a type token for disambiguation.  This results in mode code inside the macro vs. out of it, but the code is much simpler and easier to understand this way.
> `mod ipred`: Use `wrap_fn_ptr!` to generate `decl_fn!`s and add type-safe wrappers

- src/ipred.rs
- src/wrap_fn_ptr.rs
This is how things are done in C, and it simplifies the `#[cfg]`s a lot, too.
> `mod ipred::neon`: Move all `fn *_neon`s to their own `mod`

- lib.rs
This removes #![feature(extern_types)] just for the `rav1d` library, which is what really matters (unlike the binaries).
All types have been deduplicated now, so we don't need this anymore.
Fixes part of #592.
> `#![feature(extern_types)]`: Remove for the `rav1d` library

- include/dav1d/headers.rs
- src/decode.rs
- src/env.rs
- src/lib.rs
- src/obu.rs
- src/recon.rs
- src/refmvs.rs
- src/tables.rs
Main cleanups so far:
* Make args refs.
* Make some vars refs.
* Remove redundant `as` casts.
* Remove redundant type annotations.
* Remove `.wrapping_*` calls.
* Translate `for` loops.
* Use indexing for arrays.
* Add back comments.
> `mod obu`: Cleanup part 1

- src/decode.rs
- src/internal.rs
- src/ipred.rs
- src/recon.rs
This replaces the `Option`s on `.intra_pred` with an `initialized: bool` field as they are always `Some` even if `.is_none()` is checked.
`.is_none()` appears to be checked so that it can lazily initialize DSPs, relying on things being zero-initialized to begin with. 
Ideally we should move initialization to DSP allocation so its not lazy, but for now (and the way closest to the C), we can use a single initialized flag instead of `Option`s on everything.
This also default initializes `.cfl_pred` as it otherwise isn't fully initialized and is thus leaving uninitialized memory, which is UB if it is made a reference at any point (which it is).  This uses `DefaultValue::DEFAULT` for initialization instead of `None`, though, which moves the check from before the call (`.unwrap()`/`.expect()`) …
> `struct Rav1dIntraPredDspContext`: Fix defaults

- include/dav1d/headers.rs
- src/decode.rs
- src/enum_map.rs
- src/filmgrain.rs
- src/ipred.rs
- src/recon.rs
I'll do the same for the other array fields, but I need to make the `enum`s for those first; this one already exists from before.
> `struct Rav1dIntraPredDspContext::cfl_ac`: Make an `EnumMap` over `Rav1dPixelLayoutSubSampled`

- include/dav1d/headers.rs
- lib.rs
- src/cdf.rs
- src/decode.rs
- src/internal.rs
- src/obu.rs
Deduplicate these macros:
* `offsetof` (requires `#![feature(offsetof)]`, but this way is `unsafe` and will be replace soon)
* `is_key_or_intra`
* `is_inter_or_switch`
* `RAV1D_MAX_SEGMENTS`
* `DAV1D_MAX_SEGMENTS`
> `mod obu`: Deduplicate macros

- src/obu.c
- src/obu.rs
- src/picture.c
- src/picture.h
- src/picture.rs
I couldn't figure out how to push a rebased version to #518, so this is the same as #518 just rebased.
> backport from `dav1d` 1.2.0: picture: fix attaching props to delayed output pictures

- src/obu.rs
Some `continue`s in loops were not translated, and instead turned into a long `if` block with the opposite condition.  This turns them back into `continue`.
And `switch`es with early `break`s and fall-throughs were turned into `current_block_[0-9]+`-style state machines that are very confusing to read.  This keeps them as state machines, but uses this pattern:
```rust
let mut state = scrutinee;
loop {
match state {
A => {
...
state = B;
continue; // fall-through
}
B => {
if early_break_condition {
break;
}
}
}
break;
}
```
`break`s at the end of `switch` cases turn into nothing like a normal `match` arm.  Early `break`s turn into `break`s out of the surrounding `loop`.  And fall-throughs turn into switching to the following state and `continue`ing.  This is a lot more readable than the …
> `mod obu`: Cleanup transpilation-specific control flow

- src/cdf.rs
- tests/seek_stress.rs
- tools/dav1d.rs
- tools/input/input.rs
- tools/output/output.rs
`offsetof`s from C were translated as `const`s, so these are brittle to types changing without noticing.  This is an unstable feature, but I'll be able to remove all of the `offset_of!`s very soon.
> `offset_of!`: Translate all `offsetof`s

- include/dav1d/headers.rs
- src/obu.rs
I accidentally merged #604 early/into the wrong branch, so re-opening and will merge shortly.
> `fn parse_seq_hdr`: Initialize and return `Rav1dSequenceHeader` directly

- Cargo.toml
Temporary workaround for #614. Replaces #613.
> Temporarily set opt-level = 1 for debug builds

- src/internal.rs
Copies all comments from internal.h to our Rust version. Preparing to make core internal structures safe Rust types.
> `mod internal`: Add comments to internal structures

- include/dav1d/headers.rs
- src/cdef_apply_tmpl_16.rs
- src/cdef_apply_tmpl_8.rs
- src/decode.rs
- src/lf_apply.rs
- src/obu.rs
- src/picture.rs
- src/recon.rs
- src/refmvs.rs
- src/thread_task.rs
`struct Rav1dFrameSize` was extracted from the monolithic `struct Rav1dFrameHeader` to do this.  The `fn` was also renamed from `fn read_frame_size` to match the names and signatures of the other `fn parse_*`s in `mod obu`.
I'd like to double-check perf on this, as due to extracting out `struct Rav1dFrameSize`, the fields were re-arranged, and I just want to make sure that didn't hurt cache perf.
> `fn parse_frame_size`: Initialize and return `Rav1dFrameSize` directly

- src/obu.rs
The only remaining `unsafe`ty is `rav1d_get_bit(s)`, which I'll do soon, and `Rav1dPicture::frame_hdr`, which will be `Arc`ed.
> `fn parse_frame_size`: Cleanup and make mostly safe

- src/obu.rs
This passes the args `fn parse_frame_hdr` needs to parse a `Rav1dFrameHeader` directly to it vs. initializing some of them before the call or deriving them from `Rav1dContext` pointers.  And then it uses `MaybeUninit::zeroed()` to do the initialization `memset` was before.  I didn't `#[derive(Default)]` `Rav1dFrameHeader` since we'll soon just initialize it directly and this is simpler for an equivalent intermediary state.
> `fn parse_frame_hdr`: Return `Rav1dFrameHeader` directly

- include/dav1d/common.rs
- src/data.rs
- src/lib.rs
- src/picture.rs
This is helpful in replacing `Rav1dData`'s `Rav1dRef` with an `Arc`, which I'm doing next.
> `fn rav1d_data_props_set_defaults`: Replace with `fn Rav1dDataProps::default`

- include/dav1d/common.rs
- include/dav1d/data.rs
- include/dav1d/picture.rs
- src/lib.rs
As we add types that `mem::needs_drop`, dropping these extra copies can become incorrect.  Also, `.clone()` on `Dav1d*` types won't do ref-counting like it will for `Rav1d*` types as we port the `Rav1dRef`s to Rust.
> `DAV1D_API`: `ptr::{read,write}` C ptrs across the `DAV1D_API` to avoid cloning and dropping intermediaries

- .github/workflows/build-and-test-x86.yml
- .github/workflows/test.sh
The upstream dav1d project tests with threads=2 and framedelay=1,2 in CI, we should be doing the same.
Closes #644
> Add threaded testing to CI

- src/lib.rs
This way we don't need to do useless `.update_rav1d()`s and updating the API to be safe is simpler later.
For now, this is implemented by using `MaybeUninit::zeroed().assume_init()`, but this is temporary; eventually these types will be returned directly by the `fn rav1d_*`s.
> `DAV1D_API`: Don't `ptr::read` and convert `out` args

- src/obu.rs
This also makes it easier to keep the logging as is as I refactor parsing `fn`s to directly initialize things (#627).
I also fixed a few typos.
> `struct Debug`: Simplify `mod obu`'s logging

- src/obu.rs
For fields whose initialization is complex, especially for sub-`struct`s, this extracts them to their own `fn parse_*`s.  Besides being easier to read this way since there's not one giant parsing `fn`, it also makes it tremendously simpler to directly initialize and return those sub-`struct`s.
> `fn parse_frame_hdr`: Extract `fn parse_*`s for complex fields

- include/dav1d/headers.rs
- src/decode.rs
- src/obu.rs
For all of the sub-parser `fn`s under `fn parse_frame_hdr`, this converts them all to initialize and return their types directly, as well as break up the `&Rav1dFrameHeader` into the actual data dependencies so that they can be called from `fn parse_frame_hdr` before the `Rav1dFrameHeader` has been initialized.
> `fn parse_*`: Initialize and return directly for `fn parse_frame_hdr`'s sub-parsers

- src/getbits.rs
- src/obu.rs
`GetBits` is made safe by storing an index and a slice instead of a current, start, and end ptr.
> `struct GetBits`: Make safe

- include/dav1d/common.rs
- include/dav1d/headers.rs
- include/dav1d/picture.rs
- lib.rs
- src/data.rs
- src/decode.rs
- src/lib.rs
- src/obu.rs
- src/picture.rs
- tests/seek_stress.rs
- tools/dav1d.rs
This replaces `struct Rav1dUserData`, with its `Rav1dRef`, with `Option<CArc<u8>>`.
This lets us do ref-counting automatically and safely with a `#[derive(Clone)]`.  Thus, this replaces other `fn`s on `Rav1dDataProps`:
* `fn *_unref` s are `fn drop`s that leave the source in a valid, generally zeroed/`Default::default()` state, similar to C++ move constructors.  Thus, I've replaced these with `let _ = mem::take(...)`s.
* `fn *_ref`s and `fn *_copy`s are `fn clone`s that do ref-counting, so I've replaced them with `.clone()`s, where the ref-counting happens automatically with `#[derive(Clone)]` from the `Arc`.
* `fn *_move_ref`s are moves that leave the source in a valid state like `fn *_unref`s.  Thus, I've replaced these with `mem::take`s.
Furthermore, using `memset(0)` to clear …
> `struct Rav1dUserData`: Replace `Rav1dRef` with `Option<CArc<u8>>`

- src/lib.rs
- src/obu.rs
There are a bunch of various cleanups in here.  A bunch of them make things progressively safer and are pulled from #652, which I'm still debugging, so this will help separate the non-buggy changes from it.
> `mod lib`: Various cleanup in preparation for replacing `Rav1dData`'s `Rav1dRef` with a `CArc<[u8]>`

- include/dav1d/headers.rs
- src/obu.rs
This makes `Rav1dITUTT35` no longer a DST, which is very tricky (it makes `Arc`ification much more difficult, for example), at the cost of an extra layer of indirection, but since the payload probably won't be accessed through the `Rav1dITUTT35` excessively, I don't think this should be a problem.  Note that having a separate `Rav1dITUTT35` from `Dav1dITUTT35` allows us to do this easily.
> `struct Rav1dITUTT35`: Make `payload{,_size}` fields a `Box<[u8]>`

- include/dav1d/headers.rs
- include/dav1d/picture.rs
- src/internal.rs
- src/lib.rs
- src/obu.rs
- src/picture.rs
- tests/seek_stress.rs
- tools/dav1d.rs
Note that we skip `.update_rav1d()`ing it as we never read it.
> `struct {D,R}av1dITUTT35`: Replace `Rav1dRef`s with `Option<Arc<DRav1d<_, _>>>`s

- src/internal.rs
- src/lib.rs
- src/thread_task.rs
Replace C atomics in `Rav1dFrameContext.frame_thread` with Rust atomics.
> `struct Rav1dFrameContext_frame_thread`: Replace atomic intrinsics w/ `Atomic*` types

- include/dav1d/headers.rs
- include/dav1d/picture.rs
- src/cdef_apply.rs
- src/decode.rs
- src/fg_apply.rs
- src/internal.rs
- src/lf_apply.rs
- src/lib.rs
- src/lr_apply.rs
- src/obu.rs
- src/picture.rs
- src/recon.rs
- src/ref.rs
- src/thread_task.rs
- tests/seek_stress.rs
- tools/dav1d.rs
- tools/output/y4m2.rs
As these types are heavily used unlike the other `Rav1dRef`ed types, `impl Deref for DRav1d` is added, `deref`ing to `R` as that's the type used primarily in Rust.
And to simplify uses and avoid triple derefs (including an `Arc` deref and `Option::unwrap`) at use sites, a `let {frame,seq}_hdr = &***{f,c}.{frame,seq}_hdr.as_ref().unwrap();` is refactored out in each `fn` where it's used.
Furthermore, similarly to #661, `.update_rav1d()`s are skipped.  Although these types are indeed read, they are meant to be read-only, so this should be okay to do.
Unlike the previous `Arc`ified types in #659 and #661, these `Rav1dRef`s were pooled, which the `Arc` replacement is not.  However, those pools were not thread-local, so it's not clear if it is a perf regression to remove them (we'll check). …
> `struct {D,R}av1d{Sequence,Frame}Header`: Replace `Rav1dRef`s with `Option<Arc<DRav1d<_, _>>>`s

- src/decode.rs
- src/lib.rs
- src/obu.rs
- src/picture.rs
- src/thread_task.rs
This is split off of #666, which I messed up (`progress` needs to be or be part of an `Arc`).
(Copied from #666) @rinon, this may interfere with some of your atomic work, but it wasn't too large of a change to potentially duplicate. I wasn't intending on touching that part of the codebase, but it's entangled with `Rav1dPicture`, its `Rav1dRef`, and the `pic_ctx`.
> `struct Rav1dThreadPicture::progress`: Replace atomic intrinsics w/ `AtomicU32`

- src/decode.rs
- src/lib.rs
- src/obu.rs
- src/picture.rs
- src/thread_task.rs
Previously, `progress` was part of the `pic_ctx_context` `Rav1dRef`, but optionally using a DST.  To avoid that at the cost of a separate `Arc` allocation, this moves `progress` to a separate `Option<Arc<_>>`.
The `pic_ctx_context` `Rav1dRef` is especially complex to `Arc`ify due to the `fn` ptrs, etc. in it, so while this does incur an extra allocation cost and an extra `Arc::clone` on `Rav1dThreadPicture::clone`, it should still be worth it.
I also tried to avoid redundant `.unwrap()`s where possible.
`progress.is_some() == c.n_fc > 1`, so we only need to check one of these.
Sometimes the `c.n_fc > 1` check is done much earlier, though, so the checks can't be combined.
> `struct Rav1dThreadPicture::progress`: Make an `Option<Arc<_>>` separate from the `pic_ctx_context` `Rav1dRef`

- include/dav1d/data.rs
- src/data.rs
- src/decode.rs
- src/lib.rs
- src/obu.rs
- tests/seek_stress.rs
- tools/dav1d.rs
~~This is still buggy on those 3 tests (`00000063`, `redundant_frame_header`, `issue_48`) failing in #652.  The output video is off by a small number of bits for each of them, but the picture parameters and headers and OBU metadata are all the same.  I've now narrowed down the PR to this smaller one (specifically the 2nd commit, 6afc41b), which still evidently contains the bug.  The divergence in the data happens somewhere in `fn rav1d_decode_tile_sbrow`, but the dataflow gets very confusing and I haven't been able to narrow it down further yet.~~
~~Among the changes in 6afc41b, I also tried not splitting up `Rav1dData` into `CArc<[u8]>` and `Rav1dDataProps` within `fn parse_obus`, but that doesn't change anything.  `fn gen_picture` is also changed in a more straightforward manner that is …
> `struct Rav1dData`: Replace `Rav1dRef` with `Option<CArc<[u8]>>`

- src/thread_task.rs
`rav1d_worker_task` involves complex control flow with gotos, and therefore was transpiled into a state machine. This refactoring restores the original structure with minimal additional structured control flow to emulate gotos.
> `fn rav1d_worker_task`: Refactor state machine

- src/obu.rs
- src/picture.rs
Taking the args by value is more flexible.  This allows us to avoid a few `.clone()`s, for example.  But more importantly, it starts to untangle a lot of the code to eventually make `Rav1dPicAllocator` safe.  And by doing the `.clone()`s up front, we can avoid intermediary references, which may help (see https://github.com/memorysafety/rav1d/pull/673#discussion_r1449342589).
> `fn rav1d_picture_copy_props`: Take args by value

- src/decode.rs
In debugging another bug, I tried using [`cargo careful`](https://github.com/RalfJung/cargo-careful) (it tries to detect some UB with extra checks, so not as thorough as `miri`, but can run on any code), and it found this one UB where we in effect call `slice::from_raw_parts(ptr::null(), 0)`, which is not allowed.  This just changes that code path to use `&[]` instead.
Also, it might be a good idea to run `cargo careful` in CI for the debug/`opt-dev` builds.
> `fn rav1d_decode_frame_init_cdf`: `cargo careful`: Don't call `slice::from_raw_parts(null(), 0)`

- Cargo.lock
- Cargo.toml
- src/internal.rs
- src/obu.rs
- src/picture.rs
A cheaper `Atomic` alternative to the `RwLock` in #673 (see https://github.com/memorysafety/rav1d/pull/673#discussion_r1449325925).
> `struct Rav1dContext::frame_flags`: Make `PictureFlags` `Atomic<PictureFlags>`

- src/cdf.rs
- src/thread_task.rs
Replaces raw pointers to the following types with references where possible in `thread_task.rs`:
- `Rav1dContext`
- `TaskThreadData`
- `Rav1dFrameContext`
- `Rav1dTaskContext`
> `mod thread_task`: Replace raw pointers with references

- include/stdatomic.rs
- lib.rs
- src/cdf.rs
- src/decode.rs
- src/internal.rs
- src/lib.rs
- src/obu.rs
- src/ref.rs
- src/thread_task.rs
Each commit in this PR replaces the atomic field(s) in an individual struct.
Closes #638.
> Replace remaining C atomic intrinsics with native Rust atomics

- src/thread_task.rs
In refactoring the state machine of `fn rav1d_worker_task` I missed a
null check that was necessary. This change adds that check back in.
> `fn rav1d_worker_task`: Add missing null check

- src/cdf.rs
- src/thread_task.rs
Replaces raw pointers to the following types with references where possible in `thread_task.rs`:
- `Rav1dContext`
- `TaskThreadData`
- `Rav1dFrameContext`
- `Rav1dTaskContext`
> `mod thread_task`: Replace raw pointer with references

- include/dav1d/picture.rs
- src/picture.rs
Note that this adds to the requirements of `Dav1dPicAllocator::alloc_picture_callback`, part of the `DAV1D_API`.  It requires all accesses to `cookie` to be thread-safe (if threading is enabled), whereas previously it said it will always be called on the main thread.
In practice, I've found 3 implementations of `alloc_picture_callback` (which account for all of the uses in chromium and its dependencies) and they are all unconditionally thread-safe:
* `rav1d`'s default `fn dav1d_default_picture_alloc`: `cookie` is a `Rav1dMemPool`, which is protected by a mutex and thus thread-safe
* `dav1d`'s `fn picture_alloc` (for negative strides): the `cookie` is not uses
* [`ffmpeg`'s `fn libdav1d_picture_allocator`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/ffmpeg/libavcode …
> `struct Rav1dPicAllocator`: Make methods `&self` and require callbacks to access `cookie` thread-safely

- src/obu.rs
- src/ref.rs
* Fixes #640.
#640 has already been fixed, but the last use of `rav1d_ref_create` I forgot to remove even though it was really unused.  #640 was fixed mostly by:
* #659
* #661
> `fn rav1d_ref_create`: Remove as all uses are gone (forgot to remove the final use even though it was unused)

- include/dav1d/picture.rs
- src/decode.rs
- src/fg_apply.rs
- src/lib.rs
- src/obu.rs
- src/picture.rs
- src/recon.rs
- src/thread_task.rs
- tests/seek_stress.rs
- tools/dav1d.rs
- tools/output/md5.rs
- tools/output/y4m2.rs
- tools/output/yuv.rs
I've been trying to `Arc`ify this `Rav1dPictureData`, but keep running into a bug with `Rav1dFrameHeader`'s `Arc` getting corrupted and having a ref count `> isize::MAX`.  To narrow down a smaller change, this is a set of changes in preparation for the actual `Arc`ification that don't have any issues.
> `struct Rav1dPic{tureData,Allocator}`: Refactor in preparation for `Arc`ification

- src/decode.rs
- src/internal.rs
- src/lib.rs
- src/obu.rs
- src/picture.rs
- src/thread_data.rs
- src/thread_task.rs
Replaces the locking in `Rav1dFrameContext_task_thread.pending_tasks` and `TaskThreadData` with Rust equivalents. `TaskThreadData` can now be accessed as read-only with interior mutability as needed.
> `struct TaskThreadData`: Replace pthread mutexes with Rust equivalents

- src/internal.rs
- src/lib.rs
- src/thread_task.rs
Replaces `Rav1dFrameContext_task_thread.lock` with a Rust instead of pthreads mutex. This lock does not cover any data but appears to be an alternative lock to the lock in TaskThreadData to reduce unnecessary contention.
> `struct Rav1dFrameContext_task_thread::lock`: Make a Rust `Mutex`

- src/decode.rs
- src/recon.rs
- src/thread_task.rs
We want to remove the `Rav1dTaskContext` borrow from `Rav1dFrameContext`, so we need to pass both context structures to filters.
> `filter_sbrow_fn`: Add `&mut Rav1dTaskContext` arg

- src/internal.rs
- src/lib.rs
- src/thread_task.rs
`Rav1dTaskContext` doesn't need to hold a pointer to its parent if we pass this borrow into the thread start function explicitly.
> `struct Rav1dTaskContext`: Remove `*const Rav1dContext` field

- include/common/bitdepth.rs
The implementation was easier than creating an issue for it, so I just did it.
> `impl Default for BitDepthUnion`: Initialize as default whichever variant is larger

- src/decode.rs
- src/internal.rs
- src/lib.rs
- src/obu.rs
* fixes https://github.com/memorysafety/rav1d/issues/707
the issue suggests this could be a `Vec<_>`, but because this allocation cannot grow a boxed slice seems more natural to me.
I tried to take this a bit further, but the code in `lib.rs` runs into serious borrow checker issues.
> `Rav1dContext_frame_thread::out_delayed`: Make a `Box<[_]>`

- src/decode.rs
- src/internal.rs
- src/levels.rs
- src/lib.rs
- src/recon.rs
Converting `b` to a `Box<[]>` means that in `decode_b` we now have a proper borrow of `f.frame_thread.b`, whereas before we had a raw pointer to the borrowed element. This triggered a number of borrowcheck errors since throughout the function we also pass a reference to `f` to different functions, causing a conflict with the mutable borrow of `f.frame_thread.b`. I was able to make some relatively minor changes to `decode_b` to resolve the borrow conflicts, but I'm not sure if the change to how `DEBUG_BLOCK_INFO` is called (i.e. calling it once at the beginning of the function and caching the result) preserves the original behavior. Since `DEBUG_BLOCK_INFO` is currently hard-coded to return false I figured it was more important to fix the borrow issue than to preserve how debug logging was …
> `Rav1dFrameContext_frame_thread::b`: Convert to `Vec`

- src/cdef_apply.rs
- src/decode.rs
- src/internal.rs
- src/lf_apply.rs
- src/lib.rs
- src/lr_apply.rs
Removes `n_tc` and replaces it with tc.len() now that tc is a slice.
> `struct Rav1dContext`: Remove `n_tc` field

- lib.rs
- src/lf_apply.rs
- src/unstable_extensions.rs
See:
* https://github.com/memorysafety/rav1d/pull/728#discussion_r1479252179
* https://github.com/memorysafety/rav1d/pull/728#discussion_r1479261085
The current "unaligned" access of `lvl`, added in #726, and a proposed change in #728, [are UB according to `miri`](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=80849f822a890cabd324b3b898b291b8), as they cast `&[u8; 3]` and `&u8` to `&[u8; 4]`, which is an out of bounds read of a borrow.  This `fn unaligned_lvl_slice` helper `fn` fixes it and passes `miri` by transmuting (through `.align_to`) to a `&[u8]`, doing the slice, and then doing a checked cast back to `[u8; 4]`.  It also does correct bounds checking, as the previous ways were off by one in their bounds checking, as they didn't consider the read of the …
> `fn unaligned_lvl_slice`: Safely encapsulate "unaligned" slices of `lvl: &[[u8; 4]]`, as previous accesses were UB

- src/decode.rs
- src/internal.rs
Change `level` into a `Vec` (instead of a `Box<[]>`) and use `resize` to reallocate. This makes the field more consistent with how we've been translating similar fields.
I also fixed a minor error in how the array was being over-allocated, i.e. the original C over-allocated 3 **bytes**, whereas we were allocating an extra 3 **elements** (12 bytes). We now over-allocate a single element (4 bytes).
> `Rav1dFrameContext_lf::level`: Make into a `Vec` and fix padding size

- src/cdef.rs
- src/cdef_apply.rs
- src/recon.rs
Besides cleanup, this also fixes bugs in `slice::from_raw_parts(_mut)` calls in `BD::pixel_copy`s introduced during bitdepth deduplication.
can be reviewed commit-by-commit. 
these PRs get pretty large and have many unrelated changes. Would stacked PRs easier to review?
I'll leave some specific notes/questions in inline comments.
> `src/cdef_apply.rs`: cleanup

- src/cdef_apply.rs
- src/recon.rs
builds on https://github.com/memorysafety/rav1d/pull/733
> `src/cdef_apply.rs`: more cleanup

- src/lf_apply.rs
- src/recon.rs
Remove unnecessary casts, use `bool` type where appropriate, and use slices instead of raw pointers.
> `lf_apply.rs`: clean up code

- src/cdf.rs
- src/decode.rs
- src/thread_task.rs
use macros to match the original C source as closely as possible 
https://code.videolan.org/videolan/dav1d/-/blob/master/src/cdf.c?ref_type=heads#L3952
kind of a messy diff, best reviewed with the "split" view I think.
@kkysen turns out a macro is possible! It works in the majority of cases here, sometimes a variable bound in the macro is required, but then the macro can just be inlined one level and you still get most of the succinctness of the macros.
linking https://github.com/memorysafety/rav1d/issues/701
> `src/cdf.rs`: use macros to clean up code

- src/decode.rs
- src/recon.rs
DEBUG_BLOCK_INFO was a macro in the original dav1d sources and we keep running into borrow check issues with it being a function in Rust. Rather than work around these issues by adding complexity, we should just make this a Rust macro.
> `fn DEBUG_BLOCK_INFO`: Make a Rust macro to let the compiler see which fields are borrowed

- src/decode.rs
- src/lf_apply.rs
- src/lib.rs
- src/lr_apply.rs
- src/obu.rs
- src/recon.rs
- src/thread_task.rs
Removes excess mutability and replaces pointers to `struct Rav1dFrameContext` with references wherever possible, i.e. function arguments.
> `struct Rav1dFrameContext`: Remove excess mutability and pointers from uses

- src/decode.rs
- src/internal.rs
- src/lf_apply.rs
- src/lib.rs
- src/lr_apply.rs
- src/picture.rs
- src/recon.rs
- src/thread_task.rs
We want to replace `Rav1dFrameContext` with a wrapper struct that holds the atomic and locked fields accessed concurrently and put the rest of the struct inside a Mutex. This automatic refactoring rename is in preparation for this refactoring.
> `struct Rav1dFrameContext`: rename to `Rav1dFrameData`

- src/internal.rs
- src/lib.rs
- src/thread_task.rs
Lifts the `Rav1dFrameContext_frame_thread::*progress` atomics out of the frame thread structure field to a separate struct in preperation for splitting `Rav1dFrameContext` into a locked inner structure and unlocked atomics accessed concurrently.
> `struct Rav1dFrameData`: Lift progress fields out of frame thread field

- lib.rs
* Fixes part of #592
Feature no longer needed now that we use stable SIMD APIs.
> `#![feature(core_intrinsics)]`: Remove as it's unused

- src/decode.rs
- src/internal.rs
Resolves the borrow check errors by pulling the current block out of `Rav1dFrameData::frame_thread::b` and operating on it, then replacing the block back into the vector.  We pass the current block around so much, along with the frame context, that this version of inner mutability is necessary.
> `fn decode_b`: Make `Rav1dFrameData` a reference

- src/cdef_apply.rs
- src/decode.rs
- src/internal.rs
- src/lib.rs
- src/recon.rs
- src/thread_task.rs
This PR adds `Rav1dFrameData` as an explicit argument everywhere it is needed and removes the pointer to it from `Rav1dTaskContext`.
> `struct Rav1dTaskContext`: Remove `Rav1dFrameData` pointer

- include/common/bitdepth.rs
- src/decode.rs
- src/internal.rs
- src/thread_task.rs
`fn Rav1dFrameContext_bd_fn::new` is `const` and pure, so we can have a pure `bitdepth_max: c_int` => `&'static Rav1dFrameContext_bd_fn` `fn`, thereby avoiding `.clone()`s and saving on memory.
See https://github.com/memorysafety/rav1d/pull/748#discussion_r1491936115 and https://github.com/memorysafety/rav1d/pull/748#discussion_r1491949677.
We can also do a similar thing for `Rav1dDSPContext`, but with it cached based on runtime CPU features.
> `fn Rav1dFrameContext_bd_fn::get`: Replace field with lookups to static versions

- src/decode.c
- src/decode.rs
- src/internal.h
- src/internal.rs
- src/lib.rs
Addresses #753 by using unsigned integer values for `tile_start_off` instead of signed ones to avoid possible overflow.
> Backport security fix from dav1d 1.4.0

- src/align.rs
- src/decode.rs
- src/internal.rs
- src/lib.rs
- src/recon.rs
This also adds `AlignedVec64` to have the `Vec` aligned, since a `Vec<Align64<T>>` would add extra padding between each element since it would align each element, and we only want to align the whole `Vec`/slice.
> `Rav1dFrameContext_frame_thread::pal`: Make into an aligned `Vec`

- src/decode.rs
- src/internal.rs
- src/intra_edge.rs
- src/lib.rs
`root` contained pointers to `branch_sb128` and `branch_sb64`, so we can replace it with a simple getter.
In investigating this I discovered that most of our logic for working with the mode tree still uses raw pointers to nodes. I've added #756 to track the work to make node access safe.
> `struct Rav1dContext_intra_edge::root`: Replace with safe getter

- src/lr_apply.rs
- src/recon.rs
Fixes #704 :
- restore comments from C code 
- use of slices instead of raw pointers where possible
- general cleanup including removal of unnecessary casts, loop cleanup, and use of `bool` type where appropriate
> `mod lr_apply`: clean up code

- src/decode.rs
- src/lf_mask.rs
- src/lr_apply.rs
`Av1RestorationUnit` is already `Copy` and only 10 bytes, so `Cell` has no overhead. This lets us borrow `lf.lr_mask` immutably and still modify an `Av1RestorationUnit`.
> `struct Av1Restoration`: Put `Av1RestorationUnit` in a `Cell`

- src/cdef_apply.rs
- src/decode.rs
- src/internal.rs
- src/lf_apply.rs
- src/lib.rs
- src/recon.rs
In a number of cases both `f` and `f.lf.mask` were being passed into the same function, which caused borrow conflicts once the code was changed to use safe slice operations. In these cases I changed the logic to instead pass an offset into the function. In some of these cases the initial offset is actually negative, and another positive offset is added to get a non-negative offset before indexing into the slice. In these cases the offset is passed as an `i32`, otherwise the offset is passed as a `usize`.
There are still some cases where we're taking a raw pointer to `mask` within a function, and a pointer to `mask` is stored in `Rav1dTaskContext::lf_mask`. I've opted to not make all of these fully safe in this PR to keep the changes simple. Looking at how `mask` is used, I noticed that …
> `struct Rav1dFrameContext_lf::mask`: Make into `Vec`

- src/align.rs
- src/internal.rs
- src/lib.rs
This makes `AlignedVec` generic over alignments by using a marker `trait AlignedByteChunk` `impl`ed for types with the same alignment and size (e.x. `Align64<[u8; 64]>`.  Since `#[repr(align(N))]` is not a const generic, const generics couldn't be used for this, but this works nicely.  We check that `mem::size_of::<C>() == mem::align_of::<C>()` in `AlignedVec`'s constructors to ensure `AlignedByteChunk` is `impl`ed on valid types.  Thus, I also ensured that the `AlignedVec`s were actually constructed, not transmuted through `unsafe { mem::zeroed() }`.
> `struct AlignedVec`: Make generic over alignment

- src/decode.rs
- src/internal.rs
- src/lf_mask.rs
- src/lib.rs
- src/lr_apply.rs
~~In order to make this work I had to inline `setup_tile` into its one call site in order to address borrow conflicts. Once making `lr_mask` into a `Vec`, it became necessary to pass `f` as a `&mut Rav1dFrameData` in order to get mutable access to `lr_mask`. This caused a large number of borrow conflicts in the calling function because a large amount of immutable borrows are held across the call site. Most notable is that we're calling `setup_tile` within a `for tile in &f.tiles`, which means we can't pass `&mut f` into a function within the loop body.~~
~~I don't like this solution, mostly because I don't see this being a solution we can apply in the general case, but I couldn't think of a cleaner way to address the borrow issue here. The main alternative here I considered was to not …
> `struct Rav1dFrameContext_lf::lr_mask`: Make into a `Vec`

- include/common/bitdepth.rs
This way we don't have to do `BD::pxstride(stride as usize) as isize`, which is verbose and wrong for negative strides.  There may still be some places where strides are always positive, though, so it's kept generic.  This also lets us fix #636 gradually; this is the first major step in fixing #636.  We'll fully fix that later.
@fbossen, hopefully this'll help you in your PRs not have to write the hundreds of extra `as usize) as isize` casts.
> `fn BitDepth::pxstride`: Make generic over `stride` type and `BitDepth`

- src/decode.rs
- src/internal.rs
- src/lf_apply.rs
- src/lib.rs
`tx_lpf_right_edge` was being used to store two arrays in a single allocation, with the second pointer pointing halfway into the same allocation as the first pointer. I opted to split the field into two `Vec`s because it seemed like the two halves of the allocation were being treated as disjoint in practice. The new field names use the `_y` and `_uv` suffixes based on how each of the arrays is used.
> `struct Rav1dFrameContext_lf::tx_lpf_right_edge`: Make into `Vec`

- src/cdf.rs
- src/decode.rs
- src/env.rs
- src/intra_edge.rs
- src/levels.rs
- src/tables.rs
a bit more experimental, and some naming choices to be made here. I'll leave some inline comments
> `enum BlockLevel`: Make a real `enum`

- src/decode.rs
- src/internal.rs
- src/lf_apply.rs
This way, borrows are made of the field, not the whole `Rav1dFrameContext_lf`.
Fixes the borrowck issue encountered in https://github.com/memorysafety/rav1d/pull/728#issuecomment-1972300089.
> `struct TxLpfRightEdge`: New-type wrap the `Vec` in `Rav1dFrameContext_lf::tx_lpf_right_edge`

- include/common/bitdepth.rs
- src/cdef_apply.rs
- src/decode.rs
- src/internal.rs
- src/recon.rs
The pointers in `cdef_line` were pointing into the buffer owned by `cdef_line_buf`. In converting them to offsets, I had to make sure that that offsets were consistently in terms of pixels (rather than bytes). The original code was inconsistent here, with the logic working with `u8` pointers (and so was using byte offsets), but the code that uses `cdef_line` treats the pointers as `BD::Pixel` pointers, so the offset logic is calculated in terms of pixels. In converting to offsets I normalized on pixel offsets. To do so I had to add a couple of helpers:
* `BPC::pxstride` - Does the same thing as `BitDepth::pxstride`, but works in non generic code. This was needed to calculate pixel offsets during the initialization logic.
* `BitDepth::cast_pixel_slice{_mut}` - Converts a `&[u8]` to a …
> `struct Rav1dFrameContext_lf::cdef_line`: Convert pointers to offsets

- src/cdef_apply.rs
- src/decode.rs
- src/internal.rs
- src/lf_apply.rs
I'm getting a couple of weird test failures on this, but I'm putting it up in a PR now so that others can review.
> `struct Rav1dFrameContext_lf::cdef_lpf_line`: Make ptrs into offsets

- src/lf_apply.rs
- src/recon.rs
> `mod lf_apply`: clean up code and use slices instead of raw pointers

- include/dav1d/headers.rs
- src/obu.rs
This one does not have a `Dav1d` counterpart. The variant names are a based on the spec (https://aomediacodec.github.io/av1-spec/av1-spec.pdf, A.2, page 638)
> `enum Rav1dProfile`: make a real enum

- src/refmvs.rs
- src/x86/refmvs.asm
- src/x86/refmvs.h
- tests/checkasm/refmvs.c
> `fn dav1d_load_tmvs_sse4`: backport `x86_64` asm function from dav1d 1.3.0

- include/dav1d/headers.h
- include/dav1d/headers.rs
- src/obu.rs
> `struct Dav1dContentLightLevel`: backport size reduction from dav1d 1.3.0

- src/decode.c
- src/decode.rs
- src/intra_edge.c
- src/intra_edge.h
- src/intra_edge.rs
Eliminate duplicate and constant `intra_edge` table entries
> `mod intra_edge`: Backport memory reduction from dav1d 1.2.1

- .gitlab-ci.yml
- meson.build
- package/crossfiles/aarch64-android.meson
- package/crossfiles/arm-android.meson
- package/crossfiles/i686-w64-mingw32.meson
- package/crossfiles/wasm32.meson
- package/crossfiles/wasm64.meson
- package/crossfiles/x86-android.meson
- package/crossfiles/x86_64-android.meson
- package/crossfiles/x86_64-w64-mingw32.meson
- tests/checkasm/checkasm.c
Backport commits related to `checkasm`, `CI` and build.
> Backport miscellaneous commits from dav1d 1.2.0

- .github/workflows/build-and-test-aarch64-darwin.yml
- meson.build
- tests/meson.build
- tests/seek_stress.c
- tools/dav1d_cli_parse.rs
- tools/meson.build
Closes #807 and #803.
When the `test_rust` meson option (on by default) is set, use a custom meson command to build `librav1d.a` and link `dav1d` and `seek_stress` with it instead of `libdav1d`. 
Notes:
- Using the subprojects feature of meson doesn't seem to be an option since it requires a specific directory layout.
- Cross-compiling isn't supported.
- The macOS build behaves differently than local macOS, possibly due to meson version differences. Didn't root cause.
> Link `librav1d` against C `dav1d` and `seek_stress` instead of Rust versions

- src/recon.rs
* fixes #865
These are all uses of printf that I can find (`use libc::printf` is not used anywhere any more). The `tools/` do use `libc::fprintf` but that's not a part of the issue. The main library does not use `fprintf` anywhere.
> `fn printf`: Replace with `println!`

- src/internal.rs
- src/lib.rs
- src/thread_task.rs
Store the index of a frame context in the array of frame contexts, rather than doing pointer arithmetic to determine the index.
> `struct Rav1dFrameData`: Add `index` field

- src/decode.c
- src/internal.h
- src/intra_edge.c
- src/intra_edge.h
- src/lib.c
No Rust changes are needed because these optimizations (global default value and use of offsets instead of pointers) have already been implemented.
> Backport `intra_edge` optimizations from dav1d 1.2.1

- src/internal.h
- src/internal.rs
- src/recon.rs
- src/recon_tmpl.c
Define union to share memory space for `ac` and `txtp_map`
> Backport memory optimization from dav1d 1.3.0

- src/decode.rs
- src/internal.rs
- src/lib.rs
Also remove `FrameTileThreadData` because it only had a single field and was only used in one place. `lowest_pixel_mem` is now a direct field of `Rav1dFrameData`.
@rinon let me know if this looks like it'll conflict with your changes. From what I saw it doesn't look like you changed `FrameTileThreadData` so I'm not expecting it to conflict, but we can wait to merge this until after your changes are merged if that'll help.
* Closes #712
> `struct FrameTileThreadData::lowest_pixel_mem`: Make into `Vec`

- src/decode.rs
- src/internal.rs
- src/thread_task.rs
To work around borrow issues I had to change a couple of functions where both `&f` and `lowest_pixel` (i.e `&mut f.lowest_pixel_mem`) were being passed into the same function. In both cases, I was able to directly pass the parts of `f` that functions were using, since they only needed access to a couple of fields.
Part of [#715](https://github.com/memorysafety/rav1d/issues/715)
> `struct Rav1dTileState::lowest_pixel`: Make into offset

- README.md
- tests/meson.build
> Fix `seek_stress` test papercut

- src/decode.rs
- src/env.rs
- src/levels.rs
- src/recon.rs
this PR looks big but most lines are because I needed to reverse two branches so that 
```rust
if comp_type.is_none() { ... } else { ... }
```
can turn into
```rust
if let Some(comp_type) = comp_type { ... }  else { ... }
```
the first commit is most changes, the second one just the switching of branches and using the variable bound by the if-let
> `enum CompInterType`: make a real enum

- src/decode.rs
- src/internal.rs
- src/recon.rs
Rename `TileStateDq` to `TileStateRef` and use it for both fields, since both have the same structure of either referencing a field in the frame data or referencing the local tile state field.
* Closes #715
> `struct Rav1dTileState::lflvl`: Make into enum

- Cargo.lock
- Cargo.toml
- include/dav1d/headers.rs
- src/decode.c
- src/decode.rs
- src/lf_mask.h
- src/lf_mask.rs
- src/lr_apply.rs
- src/lr_apply_tmpl.c
Embed `sgr_idx` into `enum Rav1dRestorationType` to avoid storing it separately. Define `enum Rav1dRestorationType` as `repr(u8)` to match C code and save some memory.
> `enum Rav1dRestorationType`: backport optimization from dav1d 1.3.0

- src/internal.h
- src/internal.rs
- src/recon.rs
- src/recon_tmpl.c
Combine `eob` and `txtp` into single value.
> `struct Rav1dFrameContext_frame_thread`: backport memory optimization from dav1d 1.3.0

- src/internal.rs
- src/lib.rs
- src/thread_task.rs
`Rav1dTask`s are stored in two arrays and linked into a linked list by pointers. This change refactors the lists into a `Rav1dTasks` structure that links tasks by index instead of pointer.
We still access the `Rav1dTasks` structure with unsafe interior mutability, because we would have borrowing errors between the `Rav1dFrameData` reference lifetime and the lifetime of borrows out of the `Rav1dTasks` structure. This will be fixed soon when we split `Rav1dFrameData` into an immutable, interiorly mutable portion and a mutex protected mutable portion.
> `struct Rav1dFrameContext_task_thread`: Make `Rav1dTask` lists indexed

- Cargo.toml
- src/ipred.rs
Fixes situations where debug builds wouldn't link without dead code elimination and resets debug builds to the defaults.
> Reset debug to defaults

- src/decode.rs
- src/internal.rs
- src/recon.rs
The first commit converts the field to an `Option<usize>` because the pointer was being set to null in one case. However all usages of `pal_idx` were asserting that it's not null before using, so I don't think making this an `Option` is actually necessary. The second commit removes the `Option`, but I left it as a separate commit in case it's problematic for some reason I'm missing.
> `struct Rav1dTileState_frame_thread::pal_idx`: Make into offset

- Cargo.toml
Currently tests hang if a thread panics, meaning that if a lot of tests panic CI can hang for a long time. For testing purposes we just want to abort on panic to ensure we get quick test output in those cases.
> Abort on panic

- src/decode.rs
- src/env.rs
`fn get_cur_frame_segid` is always called with a whole slice (or will be once segmaps are `Arc`anized), so we only have to worry about negative offsets within this `fn`.  I think this should work for negative strides?
Actually `stride` can't be negative here.
> `fn get_cur_frame_segid`: Remove negative offsets

- include/dav1d/headers.rs
- src/obu.rs
I believe this is the final enum/struct in `headers.rs`
> `struct Rav1dColorPrimaries`: make a newtype wrapper

- src/decode.rs
- src/refmvs.rs
* Fixes `frm_hdr` field of #822.
This removes the `*const Rav1dFrameHeader` in the field, passing it through the call stack.  But we can't change the field's layout since `*const refmvs_frame` is passed to asm, so we make the field `*const ()` and `ptr::null()`. This also fixes the problem of accidentally conflating `*const Rav1dFrameHeader` and `*const Dav1dFrameHeader` in that field.
> `struct refmvs_frame::frm_hdr`: Replace raw ptr with `*const ()`

- src/decode.rs
- src/refmvs.rs
I'm working on `mvs`, `refmvs`'s `Rav1dRef`, so it's easier to have this cleaned up first.
> `fn rav1d_refmvs_init_frame`: Cleanup

- src/decode.rs
- src/refmvs.rs
> `fn rav1d_refmvs_tile_sbrow_init`: Cleanup

- src/decode.rs
- src/refmvs.rs
> `fn rav1d_refmvs_save_tmvs`: Cleanup

- src/decode.rs
- src/refmvs.rs
> `fn rav1d_refmvs_find`: Minor cleanup and remove unused `&mut`s from calls

- src/decode.rs
- src/refmvs.rs
> `struct refmvs_tile::rf`: Remove field and pass through the callstack instead

- src/decode.rs
- src/refmvs.rs
This also removes the indirection in `mod ffi` that I added a long time ago.  We have long since figured out that indirection is bad for perf, so this removes it.  The extra length args are passed at the end of the args so that asm calls can be done without modification/interception.
> `mod refmvs`: `fn` ptr cleanup

- src/align.rs
- src/decode.rs
- src/env.rs
- src/internal.rs
- src/lf_apply.rs
- src/lib.rs
This will need to be wrapped in a `DisjointMut` due to being accessed concurrently across threads, but I want to start by making it `Vec` and then add the wrapper in a followup PR.
> `struct Rav1dFrameData::a`: Make into `Vec`

- Cargo.lock
- Cargo.toml
- include/common/bitdepth.rs
- src/decode.rs
- src/internal.rs
- src/recon.rs
To avoid borrow checker issues I modified `decode_coefs` to use a new `CfSelect` enum to determine which of the two possible coef bufs to use. I also added coef versions of `pxstride` and `cast_pixel_slice` so that I could correctly convert between byte offsets and coef offsets.
I also had to make a couple of functions take a `&mut Rav1dFrameData` (previously they were taking a shared reference) in order to get mutable access to the coef buffers. @rinon does this conflict with your current work?
> `struct Rav1dTileState_frame_thread::cf`: Make into offset

- src/decode.rs
Fixes breakage introduced by https://github.com/memorysafety/rav1d/pull/902
> `fn decode_b_inner`: Fix borrow checker error

- src/cdf.rs
- src/decode.rs
- src/lib.rs
- src/obu.rs
- src/thread_task.rs
Convert `CdfThreadContext` from a `Rav1dRef` of `CdfContext` + `progress` atomic to an `Arc`. This is complicated by the fact that this structure has several states, which are now represented by an `enum` and optional `progress` field.
* Closes #824
> `struct CdfThreadContext`: convert to `Arc`

- src/decode.rs
- src/internal.rs
- src/recon.rs
- src/thread_task.rs
I mildly regret turning all the `(*ts)` into `ts` because it makes the diff very noisy, apologies for that. If I run into a similar situation for future fields I'll break the cleanup into a separate PR.
* Part of #716
> `struct Rav1dTaskContext::ts`: Make into an offset

- src/refmvs.rs
Since we pass them as pointers, we can change `*const T` args to `*const [T; N]` if we're always passing an array, as their representation is the same and so asm will treat them the same.  But for the fallbacks, we have less unsafety since we get an array instead of just a pointer with unknown length.
> `type save_tmvs_fn`: Make `rr`, `ref_sign` args array ptrs

- src/decode.rs
- src/internal.rs
- src/lf_apply.rs
- src/lib.rs
- src/mem.rs
- src/refmvs.rs
This lets us change `RefMvsFrame` to be safe, as it's no longer `#[repr(C)]` and we can change its layout. Since the asm functions only take `*const refmvs_frame`, the one-way conversion is easy and should stay simple.  There are only 2 of these conversions needed, and they're only 224 bytes (for `refmvs_frame`) `memcpy`s pretty much.
> `struct RefMvsFrame`: Create a `Rav1d` version of the `Dav1d` `refmvs_frame`, which is passed to asm

- src/decode.rs
- src/env.rs
- src/internal.rs
- src/lf_mask.rs
- src/recon.rs
- src/thread_task.rs
This helps a lot with borrowck errors, like in #937 and the one that will follow this for `fn obmc` and `fn mc`.
> `struct Bxy`: Move `Rav1dTaskContext::{bx,by}` into its own `struct`

- include/common/bitdepth.h
- include/common/bitdepth.rs
- src/arm/32/ipred.S
- src/arm/32/ipred16.S
- src/arm/64/ipred.S
- src/arm/64/ipred16.S
- src/decode.c
- src/decode.rs
- src/internal.h
- src/internal.rs
- src/ipred.h
- src/ipred.rs
- src/ipred_tmpl.c
- src/recon.h
- src/recon.rs
- src/recon_tmpl.c
- src/unstable_extensions.rs
- src/x86/ipred_avx2.asm
- src/x86/ipred_avx512.asm
- src/x86/ipred_sse.asm
- tests/checkasm/ipred.c
Allocate memory for palette mode according to bit depth of pixel instead of fixed `u16` size.
> Backport memory optimization for palette mode from dav1d 1.3.0

- include/common/bitdepth.rs
- lib.rs
- rust-toolchain.toml
- src/log.rs
`rust-analyzer` has been showing me a ton of warnings lately, things like `non_camel_case_types`, which we allow for `rustc`, and which I realized is due to the `rust-analyzer` version being new, and our `rustc` toolchain being old.  Upgrading it to the latest nightly fixes this.  These warnings are especially annoying as they slow down my edit and compile cycle, and we are due for an upgrade anyways, though hopefully we can go to `stable` next (once #620 is merged, though it hasn't been enough of a priority).
We can also replace the `target_arch = "arm"`-dependent `#![feature(stdsimd)]` with the much more specific and more likely to stabilize soon `#![feature(stdarch_arm_feature_detection)]`.
* Fixes #623.
> `rust-toolchain.toml`: Upgrade to `nightly-2024-04-01`

- .github/workflows/build-and-test-x86.yml
With disjoint mut debug checks, we are seeing enough slowdown in CI that we need to increase the timeout.
> Increase timeout multiplier from 2 to 3

- src/lib.rs
Initialize `Rav1dContext::tiles` and `Rav1dFrameData::tiles` as they were not being correctly initialized previously.
> Initialized `tiles` vecs

- .github/workflows/build-and-benchmark-x86.yml
- .github/workflows/build-and-test-aarch64-darwin.yml
- .github/workflows/build-and-test-x86-extra.yml
- .github/workflows/build-and-test-x86.yml
Sometimes testing without optimizations can surface issues so we add an unoptimized test run for aarch64-darwin since tests run fast on that platform.
> CI: Test debug build on aarch64-darwin

- lib.rs
- src/align.rs
- src/disjoint_mut.rs
Applies the wrapper to `struct Rav1dFrameContext_frame_thread::pal`.  When debug assertions are enabled, this wrapper tracks borrows and ensures that mutable borrowed regions are actually exclusive for their lifetime. In release mode, borrowing is unchecked and relies on correct disjoint access.
> Add `DisjointMut` wrapper to allow concurrent mutable slicing

- src/internal.rs
- src/recon.rs
Elements in the `cbi` field are actually `i16`s, so we can make them atomic for inner mutability rather than having to use a lock.
> `struct CodedBlockInfo`: Make cbi elements atomic

- src/decode.rs
- src/lf_mask.rs
- src/lr_apply.rs
`Rav1dFrameContext_lf::lr_mask` is shared across threads, and therefore must be a thread-safe `Sync` type. This changes replaces an existing usage of `Cell` to provide interior mutability with non-blocking usage of `RwLock`.
> `struct Av1Restoration`: Replace `Cell` with `RwLock`

- src/refmvs.rs
* Fixes part of #703.
* Fixes part of #841.
> `fn *refmvs_dsp_init*`: Make safe

- src/getbits.rs
- src/lib.c
- src/lib.rs
- src/obu.c
- src/obu.h
- src/obu.rs
Avoid creating an entire decoder instance to just parse a sequence header.
> `fn dav1d_parse_sequence_header`: backport simplification from dav1d 1.2.1

- .github/workflows/test.sh
We still want `RUST_BACKTRACE=1` to print a backtrace on panicking, as that's very useful and doesn't slow tests down. But that also causes `Backtrace::capture()` to actually capture a backtrace, and since we do that in every `DisjointMut::{index,index_mut}` call, it makes the tests extremely slow. Setting `RUST_LIB_BACKTRACE=0` overrides this and makes the tests fast (enough) again. And it can always be overridden again on the command line.
> `test.sh`: Set `RUST_LIB_BACKTRACE=0` so `debug_assertions` tests don't take forever due to capturing a ton of backtraces

- src/decode.rs
- src/internal.rs
- src/lf_apply.rs
Adds inner mutability to the right edge split vector by using DisjointMut and narrower ranges for reading and writing data.
> `struct TxLpfRightEdge`: Add inner mutability

- src/decode.rs
- src/internal.rs
- src/lib.rs
- src/obu.rs
- src/thread_task.rs
Adds inner mutability to the `retval` and `update_set` fields of `Rav1dFrameContext_task_thread`.
Also adds a finished flag so we don't have to inspect the `tiles` field.
> `struct Rav1dFrameContext_task_thread:` Give fields inner mutability

- src/disjoint_mut.rs
When I was first looking into why `DisjointMut` slowed things down so drastically, I first tried simplifying the ranges/bounds.  I then discovered it was mostly the backtraces (fixed in #967), but I had already done this and started building stuff off of it, and I think it makes the logic a lot clearer (I had a hard time understanding the previous overlapping logic), specifically `fn overlap` and `fn get_mut`.  I also improved the error messages, making it more concise, and printing the `Display` version of the `Backtrace` that's normally printed on panics rather than the `Debug` version we'd been printing.
> `struct DisjointMut`: Simplify bounds and improve error messages

- src/decode.rs
- src/recon.rs
- src/refmvs.rs
This is replaced with a static assert that `refmvs_block` is 12 bytes. `packed` works slightly differently in Rust than in C, which is why this still works, and `packed` is less well supported in Rust, so it's nice to remove it, as it frees up other possibilities, and just makes things simpler.
> `struct refmvs_block`: Remove `#[repr(packed)]` on `struct refmvs_block_unaligned`, as it's already 12 bytes

- lib.rs
- src/decode.rs
- src/ffi_safe.rs
- src/recon.rs
- src/refmvs.rs
This removes `&mut` accesses of `Rav1dFrameData` added in #942.
> `struct RefMvsFrame::r`: Add `DisjointMut`

- src/refmvs.rs
This is just basic cleanup.  I'll make it safer next (the fields that I've already made safe on the other side of the `fn` ptr boundary).  Then I'll be able to `Arc`ify the `mvs` fields, as those are accessed here through raw pointers on this side of the `fn` ptr boundary.
> `fn load_tmvs_c`: Cleanup

- src/decode.rs
- src/refmvs.rs
This also makes `fn RefMvsFrame::as_mut_dav1d` take `&self` and use `DisjointMut`'s inner mutability when calling `load_tmvs`.  This way the uses of `f.rf` are `&`s and won't prevent making `f` `&` in #952.
This then sets the stage for passing `DisjointMut`s directly to `fn load_tmvs_c` and using it safely there.  The asm `fn` ptrs will continue to things completely unsafe, as we can't really get around that.
> `struct RefMvsFrame::rp_proj`: Add `DisjointMut`

- src/internal.rs
- src/lf_mask.rs
- src/lib.rs
I found these by running the argon tests in debug mode (not just `debug_assertions`), as these `libstd` assertions are only run in actual debug mode.
> `struct DisjointMut`: Fix missing initializations of `DisjointMut` fields

- src/decode.rs
This fixes a bug from #971 where I was overslicing.  It wasn't caught by the normal tests, only the argon tests that only ran on `main` once I merged.
> `fn get_prev_frame segid`: Fix overslicing

- src/decode.rs
- src/refmvs.rs
`fn splat_mv` is already a method, and `fn rav1d_refmvs_save_tmvs` was already like a method, but as a free `fn`.  So this just makes them all methods on `Rav1dRefmvsDspContext`, which helps things for `fn load_tmvs` as I make it and the `mvs` fields safe.
> `struct Rav1dRefmvsDSPContext`: Add wrapper methods

- src/decode.rs
- src/internal.rs
- src/lib.rs
- src/obu.rs
- src/ref.rs
- src/refmvs.rs
* Fixes `{,ref_}mvs{,_ref}` fields of #713.
* Fixes `refmvs{,_pool}` fields of #641.
> `struct Rav1dFrameData::{mvs,ref_mvs}`: `Arc`ify with `Option<DisjointMutArcSlice<refmvs_temporal_block>>`s

- src/internal.rs
- src/lib.rs
This was already `Arc`ified in a previous PR, so this removes the now unused pool.
> `struct Rav1dContext::cdf_pool`: Remove now-unused `cdf_pool`

- src/cdef.rs
- src/cdef_apply.rs
- src/cpu.rs
- src/decode.rs
- src/enum_map.rs
- src/filmgrain.rs
- src/internal.rs
- src/ipred.rs
- src/itx.rs
- src/levels.rs
- src/lf_apply.rs
- src/lib.rs
- src/loopfilter.rs
- src/looprestoration.rs
- src/lr_apply.rs
- src/mc.rs
- src/recon.rs
- src/thread_task.rs
* Fixes `dsp` field of #713.
* Fixes all `fn *dsp_init`s of #862.
* Improves DSP initialization code size of #809.
This
* Makes all `fn *dsp_init*`s safe.
* Changes all `fn *dsp_init*`s into `fn *DSPContext::new`s that directly initialize the type without `unsafe`ly zero initializing it first.  This is done by directly initializing in `fn default`, which is for the fallback `fn`s, and then updating the `fn` ptrs in the `fn init_{x86,arm}`s.  These `fn`s are also all `const` now, as that was trivial.
* Adds `wrap_fn_ptr!` and `enum_map!`s to the array fields of `Rav1dMCDSPContext`, since I needed a default value to initialize the arrays directly if I want it the indices to be named (rather than a normal array, whose order is easy to mix up).  `wrap_fn_ptr!` provides that default value, …
> `fn Rav1dDSPContext::get`: Lazily initialize with `OnceLock` and store `&'static`s

- src/disjoint_mut.rs
- src/internal.rs
- src/lf_apply.rs
- src/recon.rs
- src/unstable_extensions.rs
The `pal` buffer is a type-erased `Pixel` buffer that needs to be accessed concurrently. This change adds support for casting `DisjointMut` guards from `[u8]` buffers to appropriate bitdepth-dependent types that implement `FromBytes`.
> `struct Pal`: Add inner mutability to pal buffer

- include/common/bitdepth.rs
- src/cdef_apply.rs
- src/decode.rs
- src/disjoint_mut.rs
- src/internal.rs
- src/lf_apply.rs
- src/lr_apply.rs
Adds inner mutability to the `cdef_line_buf`, and `lr_line_buf` fields by using locks taken without blocking. Any blocking indicates contention that we should address in other ways.
> `struct Rav1dFrameContext_lf`: Add inner mutability

- src/lib.rs
> `struct Rav1dPicture`: Replace `MaybeUninit::zeroed().assume_init()` with `Default::default()` as we already `impl Default`

- include/dav1d/headers.rs
- include/dav1d/picture.h
- include/dav1d/picture.rs
- meson.build
- src/decode.rs
- src/internal.h
- src/internal.rs
- src/lib.c
- src/lib.rs
- src/obu.c
- src/obu.rs
- src/picture.c
- src/picture.h
- src/picture.rs
Reopening #528 since it got closed because I deleted the target branch, which I guess happens when the PR branch is on a fork.
> backport from `dav1d` 1.2.0: picture: allow storing an array of `Dav1dITUTT35` entries

- .github/workflows/build-and-test-x86.yml
It seems `macos-latest` transitioned (is transitioning) from `x86` to `aarch64`. This may lead to unintended interactions with caching of the Rust toolchain. We've observed runs that failed because `cargo` was not found. My best guess is that we restored a `x86` toolchain onto a `aarch64` host but reproducing to make sure would take too much time. Requesting `macos-13` instead of `macos-latest` should avoid this issue altogether.
> CI: Pin version of macos to avoid build failure

- include/dav1d/picture.rs
- src/decode.rs
- src/fg_apply.rs
- src/lib.rs
- src/obu.rs
- src/picture.rs
- src/recon.rs
- src/ref.rs
- src/thread_task.rs
> `struct Rav1dPictureData`: `Arc`ify

- .github/workflows/build-and-test-qemu.yml
- build.rs
- include/common/attributes.h
- include/common/bitdepth.rs
- lib.rs
- meson.build
- src/cdef.rs
- src/cpu.c
- src/cpu.h
- src/cpu.rs
- src/filmgrain.rs
- src/ipred.rs
- src/itx.rs
- src/lib.rs
- src/loongarch/cpu.c
- src/loongarch/cpu.h
- src/loopfilter.rs
- src/mc.rs
- src/meson.build
- src/refmvs.rs
- src/riscv/cpu.c
- src/riscv/cpu.h
- src/thread_task.rs
- tests/checkasm/checkasm.c
- tests/checkasm/checkasm.h
- tools/dav1d_cli_parse.c
- tools/dav1d_cli_parse.rs
* Closes #775.
* Closes #861.
Build for QEMU user with:
```
RUSTFLAGS="-C target-feature=+crt-static,+v -C linker=riscv64-linux-gnu-gcc"  \
cargo build --target riscv64gc-unknown-linux-gnu
```
(Note to self: remove `,+v` in above command to test RISC-V sans assembly.)
Note: the above command seems to work on Ubuntu 22.04 which comes with ld version 2.38 but fail on Ubuntu 20.04 where ld is version 2.34.
> Build and test for RISC-V

- build.rs
- lib.rs
- src/decode.c
- src/decode.rs
- src/internal.h
- src/internal.rs
- src/lib.c
- src/lib.rs
- src/meson.build
- src/pal.c
- src/pal.h
- src/pal.rs
- src/x86/pal.asm
- src/x86/pal.h
- tests/checkasm/checkasm.c
- tests/checkasm/checkasm.h
- tests/checkasm/pal.c
- tests/meson.build
Move palette packing/edge-extension into a DSP function and provide asm and Rust equivalents
> Backport palette packing asm from dav1d 1.3.0

- src/decode.rs
- src/internal.rs
- src/recon.rs
Makes the various scratch `union`s into safe "union"s by using `zerocopy`.
> `struct Rav1dTaskContext::scratch`: Make into `zerocopy`-based "unions"

- src/decode.rs
- src/internal.rs
- src/lib.rs
- src/obu.rs
- src/thread_task.rs
Separates the frame data into intialized and then rarely updated data (`Rav1dFrameData`) and a few of the fields required to pick tasks before accessing the rest of the frame data to execute the task.
> `struct Rav1dFrameContext`: Separate into data and context

- src/decode.rs
- src/internal.rs
- src/lib.rs
- src/obu.rs
- src/picture.rs
- src/refmvs.rs
- src/thread_task.rs
Replaces the C allocation and `fc` array pointer of `Rav1dFrameContext` structures with a Rust boxed slice.
> `struct Rav1dContext`: Make frame contexts a `Box<[_]>`

- src/decode.rs
- src/internal.rs
- src/ipred_prepare.rs
- src/lib.rs
- src/recon.rs
Part of https://github.com/memorysafety/rav1d/issues/713
> `struct Rav1dFrameData::ipred_edge`: Make into `DisjointMut<AlignedVec<u8>>`

- include/dav1d/headers.h
- include/dav1d/headers.rs
- src/cdef_apply.rs
- src/cdf.rs
- src/decode.rs
- src/internal.rs
- src/lf_mask.rs
- src/lib.rs
- src/obu.c
- src/obu.rs
- src/recon.rs
- src/refmvs.rs
- src/thread_task.rs
* Fixes `Dav1dFrameHeader` of #505.
Shrinks `Rav1dFrameHeader` from 1664 to 1120 bytes.
> `struct Dav1dFrameHeader`: backport memory size reduction from dav1d 1.3.0

- src/decode.rs
- src/levels.rs
- src/recon.rs
In preparation for making the `union`s into `enum`s/other safe constructs, this renames all of the `c2rust_unnamed*` fields into real names.  This is a very simple but noisy change, so I wanted to put this in its own PR first.
> `{struct,union} Av1Block*`: Rename fields and types

- src/decode.rs
- src/internal.rs
- src/lib.rs
- src/obu.rs
- src/thread_task.rs
The `delayed_fg` mutex was contended because multiple threads need to read from it concurrently. This change splits the mutex back into a lock field, with the same usage as the original pthreads lock, and an `RwLock` for `delayed_fg`.
This change also splits out `delayed_fg.exec` so we don't need to lock the inner struct for writing to write this boolean.
* Fixes #763
> `struct TaskThreadData`: Split `delayed_fg` lock from thread lock

- src/decode.rs
- src/levels.rs
- src/recon.rs
* Fixes `Av1BlockIntraInter` of #854.
`Av1Block::intra` is already the discriminant for `enum Av1BlockIntraInter`.  However, initialization happens piecemeal, so I'll convert that next and then remove the `Av1Block::intra` discriminant field since we now have it in the `enum` (for now it's just default initialized).  Also, I'll next remove excessive `.{inter,intra}()` calls where possible, as a lot of places, we can just call it a few times.
> `enum Av1BlockIntraInter`: Make the `union` an `enum`

- include/dav1d/picture.rs
- src/internal.rs
- src/lib.rs
- src/mem.rs
- src/picture.rs
* Fixes #641.
This rewrites from scratch the `unsafe` `Rav1dMemPool` as the safe `MemPool`.  There are a few important differences here:
* `Rav1dMemPool` used `Box<[u8]>` essentially.  `MemPool` uses `Vec<T>` (`T = u8` in this case), which saves on some reallocations, as `Rav1dMemPool` would only reuse an allocation if it was exactly the same size.
* By returning `Vec`s, the caller can decide how initialization is done, as `MemPool` only does the capacity allocation.
Since these picture allocations are large, this code is performance-critical.  When running on `./tests/large/chimera_10b_1080p.ivf -l 100`, I observed a ~5% performance regression initially (401 ms baseline, 415 ms new).  However, if I do not zero out the data buffer (using `Vec::resize_with`, which only initializes the new …
> `struct MemPool`: Rewrite `Rav1dMemPool` as fully safe and use it for `Rav1dContext::picture_pool`

- include/dav1d/picture.rs
- src/lib.rs
- src/picture.rs
> `mod picture`: Make fully safe

- lib.rs
- src/decode.rs
- src/internal.rs
- src/iter.rs
- src/lib.rs
- src/thread_task.rs
The remaining `unsafe` is from `Rav1dFrameContext_task_thread::tasks`, which is an `UnsafeCell<Rav1dTasks>`.
> `fn rav1d_flush`: Cleanup and make mostly safe

- src/decode.rs
- src/levels.rs
- src/recon.rs
Now we can get rid of the `.{inter,intra}_mut()` methods, avoid their overhead, avoid extra default initialization, and now the shape of `union Av1BlockInterNd` is very clear.
> `struct Av1BlockIntraInter`: Initialize directly

- src/decode.rs
- src/internal.rs
- src/levels.rs
- src/recon.rs
This removes `Av1Block::intra`, which was the now-redundant discriminant of `Av1BlockIntraInter`.  Now code matches on `Av1BlockIntraInter` directly and avoids checks when accessing `inter` or `intra`.
> `struct Av1BlockIntraInter`: Access variants directly, avoiding checks

- src/cdef.rs
- src/decode.rs
- src/filmgrain.rs
- src/internal.rs
- src/ipred.rs
- src/itx.rs
- src/lf_apply.rs
- src/lib.rs
- src/loopfilter.rs
- src/looprestoration.rs
- src/mc.rs
- src/msac.rs
- src/pal.rs
- src/recon.rs
- src/refmvs.rs
- src/thread_task.rs
Sorry that this PR is a little all over the place, but essentially what it does is:
* Make `*DSPContext` initialization safe, all `const fn`, and return the DSPs directly.
* Consolidate the non-`BitDepth` dependent DSPs into `Rav1dDSPContext`, with the former `Rav1dDSPContext` renamed to `Rav1dBitDepthDSPContext`.
* Add `Rav1dMsacDSPContext` to use the same approach there instead of a one-off different one.
* Fix incorrectly translated `#[cfg]`s for asm enabling in `mod msac`.
* This would also set us up to easily turn on CPU feature detection for asm `fn`s in `mod msac` as is does everywhere else.  Only compile-time CPU detection is done correctly, so for example, `sse2` asm `fn`s are not used on `x86` unless specifically compiled with `sse2`.
> `struct Rav1d{,BitDepth}DSPContext`: Consolidate, make safe, and fix some `#[cfg]`s for asm

- src/cdf.rs
- src/decode.rs
- src/obu.rs
- src/thread_task.rs
This makes a bunch of `fn`s that were already safe or trivially safe nominally safe:
* `fn reset_task_cur_async`
* `fn rav1d_task_delayed_fg`
* `fn get_frame_progress`
* `fn abort_frame`
* `fn read_restoration_info`
* `fn rav1d_cdf_thread_alloc`
* `fn get_qcat_idx`
* `fn rav1d_cdf_thread_init_statci`
* `fn rav1d_cdf_thread_copy`
* `fn parse_obus::skip`
* `fn parse_obus::parse_tile_grp`
* `fn rav1d_parse_sequence_header`
* `fn parse_frame_size`
* `fn parse_refidx`
* `fn parse_segmentation`
* `fn parse_loopfilter`
* `fn parse_skip_mode`
* `fn parse_gmv`
* `fn parse_film_grain`
It also cleans up all of those `fn`s, and `mod cdf` is also now made `#![deny(unsafe_code)]`.
> `fn *`: Make a bunch of already safe `fn`s nominally safe and clean them up

- include/dav1d/dav1d.rs
- lib.rs
- src/decode.rs
- src/extensions.rs
- src/internal.rs
- src/lib.rs
- src/obu.rs
* Fixes `Rav1dContext` of #862.
This replaces the zero (`memset`) initialization of `Rav1dContext` with `Default::default()` initialization in `fn rav1d_open`.  I haven't yet made initialization fully safe in `fn rav1d_open` due to borrowck errors, but this should ensure everything is safely initialized, and hopefully fixes some heisenbugs?
> `struct Rav1dContext`: Initialize as `Default::default()`

- src/internal.rs
- src/lib.rs
* Fixes `Rav1dFrameData` of #862.
* Fixes `Rav1dFrameContext_lf` of #862.
> `struct Rav1dFrameData`: `impl Default` instead of unsafely zeroing and partial initialization

- src/decode.rs
- src/msac.rs
I was trying to make `fn new` totally safe by adding a lifetime to `MsacContext`, but I'm not sure how to do that yet (it is a slice from a `Rav1dData`).  Since @randomPoison is working on making `ts: *mut Rav1dTileState` safe right now and `MsacContext` is a field of `Rav1dTileState`, I'll leave that part for later.
> `fn MsacContext::new`: Make `fn rav1d_msac_init` a method returning `Self` directly and make `data` a slice

- src/arm/64/ipred.S
- src/arm/64/ipred16.S
- src/arm/64/refmvs.S
Amend call type in refmvs. Because these blocks are reached via blr x11, they need to be annotated.
Add missing BTI landing pads in ipred.S and ipred16.S. Because the subroutines are called via a br from register, they need annotation with 'bti j' (AARCH64_VALID_JUMP_TARGET).
> fix: various errors in implementation of BTI

- src/decode.rs
- src/internal.rs
- src/msac.rs
- src/recon.rs
- src/thread_task.rs
This is the first step in giving `Rav1dTileState` interior mutability, which is necessary to make the `ts` allocation safe.
The context fields of `Rav1dTileState` (`msac` and `cdf`) are accessed exclusively from one thread at a time, so I've put them in a `Mutex` to allow us to still gain mutable access once the tile state is immutably shared between threads. This required reworking how the data is accessed, as the original logic was accessing the fields at multiple points in the callstacks, which would have resulted in lock conflicts when a function further down in the callstack would try to acquire a lock that's already held higher up. I've changed the code to pass down the mutable reference, ensuring that the lock is only held once. For a couple of functions this meant taking an …
> `struct Rav1dTileStateContext`: Put `cdf` and `msac` in a `Mutex`

- include/common/intops.rs
- src/decode.rs
- src/lf_mask.rs
Came across this when reviewing #1032.  We can pass array refs instead of slices and eliminate the bounds checks.
> `fn {init_quant_tables,rav1d_calc_lf_values}`: Cleanup and elide bounds checks

- src/disjoint_mut.rs
Fixes an issue where the wrong immutable range can be removed if there are multiple borrows with the same range.  Previously, the wrong one could be removed, which removed an equivalent range, but one with the wrong location (for debugging purposes).
> `struct DisjointMut`: Ensure the correct range is removed

- src/fg_apply.rs
- src/internal.rs
- src/lib.rs
- src/thread_task.rs
Make raw picture pointers in `delayed_fg` into ref-counted references. `Rav1dPicture` needs inner mutability, which is still currently unsafe.
* Fixes #833.
* Fixes `TaskThreadData_delayed_fg` of #862.
> `struct TaskThreadData_delayed_fg`: Make raw pointers owned references

- Cargo.lock
- include/dav1d/headers.rs
Also helps with https://github.com/memorysafety/rav1d/pull/1032#discussion_r1591558410.
> `struct Abcd`: Use `Atomic<[i16; 4]>` now that `atomig` supports this automatically

- Cargo.lock
- src/decode.rs
- src/internal.rs
- src/lib.rs
- src/mem.rs
- src/recon.rs
- src/thread_task.rs
* Fixes the `ts` field of #713.
* Closes #713.
> `struct Rav1dTileState`: Make into `Vec` and give interior mutability

- src/itx.rs
* Fixes `fn inv_txfm_add_wht_wht_4x4_rust` of #817.
* Fixes `fn inv_txfm_add_wht_wht_4x4_rust` of #836.
Very similar to #1041.
> `fn inv_txfm_add_wht_wht_4x4_rust`: Cleanup and make mostly safe

- src/decode.rs
- src/refmvs.rs
Remove `unsafe` marker from the smaller functions in `decode.rs` that are already safe or mostly safe, and add `unsafe` blocks and safety comments where needed.
> `decode.rs`: Remove `unsafe` marker from safe functions

- src/itx.rs
- src/itx_1d.rs
* Fixes #816.
* Fixes #844.
All 624 `unsafe` ops in `mod itx_1d` (the largest `mod` remaining in terms of `unsafe` ops) are now gone.  Only 2214 left!
There's a bunch more that could be polished and optimized here (e.x. bounds checks), but these are fallbacks, so it's not really worth it.
> `mod itx_1d`: Make fully safe

- src/recon.rs
Also add comments for `goto`s and their labels.
> `fn decode_coefs`: Add back comments

- src/recon.rs
The C `case_sz` macro is pretty short and contains a lot of ident joining, which doesn't work as well from Rust, so I chose to not keep the macro and just simplify some things as much as possible so there's not too much repetition.
> `fn decode_coefs`: Cleanup `case_sz` macro

- src/decode.rs
`max` can be 0 and subtracting 1 causes underflow
> Fix underflow introduced in #1007

- src/recon.rs
There are some `goto`s in the C, but they are just used for skipping an `if` block, so the existing `c2rust transpile` version is good enough.
> `fn rav1d_recon_b_intra`: Cleanup

- src/internal.rs
- src/recon.rs
`Cf` and `AlPal` were simple arrays so I used zerocopy for those. The only remaining usage of `BitDepthUnion` was `Grain`, which is only accessed mutably in one place, so I made that into an enum and lazily initialized it when accessed mutably.
> `Cf`,`AlPal`: Make into safe zerocopy-based "unions"

- src/thread_task.rs
- tests/dav1d_argon.bash
Writes to `copy_lpf` were hitting contention with reads during task selection in the argon tests. This seem rare enough that we should just block.
Fixes argon test failures on main.
> `struct Rav1dFrameContext_frame_thread_progress`: Block write to `copy_lpf`

- include/common/bitdepth.rs
- src/internal.rs
- src/thread_task.rs
Removes `BitDepthUnion` and replaces the last usage of it with an enum. Split off from #1073 due to questions around lazy initialization. I've reworked this to eagerly initialize the `Grain` enum in `rav1d_task_delayed_fg` where we setup the rest of the delayed fg task.
> `union BitDepthUnion`: Remove and replace with safe `enum`

- src/internal.rs
- src/mc.rs
- src/recon.rs
The `tmp1` and `tmp2` args to these fns are always pointers to fixed-size arrays, so I've changed the signatures to pass them as array references, allowing us to use safe slice operations in the Rust fallback fns.
Part of https://github.com/memorysafety/rav1d/issues/842.
> `fn {w_}{avg,mask}_*`: Pass array reference for `tmp` args

- src/mc.rs
The `tmp` arg for the the `warp_affine_8x8t` fns is always a slice, so I've added an extra arg to the end of the function calls to pass the slice length in so that we can safely reconstruct the slice in the Rust fallback fns.
* Part of #842.
> `fn warp_affine_8x8t`: Pass `tmp` len for use in Rust fallback

- src/ipred_prepare.rs
Use correct casts to `isize` and `usize` when computing indices into `dst` slice to avoid numerical under/overflows.
> `mod ipred_prepare`: fix arithmetic when using negative strides

- include/dav1d/picture.rs
- lib.rs
- src/disjoint_mut.rs
- src/fg_apply.rs
- src/picture.rs
- src/recon.rs
This adds `Rav1dPictureDataComponent`, which stores the ptr and length of each of the YUV components of a `Rav1dPictureData`.  This is wrapped in `DisjointMut` so that it can be safely accessed disjointly mutably, but for now, access is still done unsafely through `.as_mut_ptr()`.  Changing that to safe/checked `.index(_mut)`s can be done, but I'll have to narrow/split up a bunch of the borrows, and there are a lot of uses, so I'm leaving that to my next PR.
> `struct Rav1dPictureDataComponent`: Store pic data in a `DisjointMut`, but still unsafely use `.as_mut_ptr()` for now

- src/mc.rs
The `tmp` arg for the `mct` fns is always a slice, so I've added an extra arg to the end of the function calls to pass the slice length in so that we can safely reconstruct the slice in the Rust fallback fns.
* Part of #842.
> `fn mct`: Pass `tmp` len for use in Rust fallback fns

- src/mc.rs
Fixes the places where we were incorrectly converting potentially-negative stride values to `usize`. In a few places this meant reverting slices and iterator operations back to raw pointer operations.
* Part of #636.
> `mc.rs`: Restore support for negative strides in Rust fallback fns

- src/lf_apply.rs
- src/recon.rs
Fixes slice construction and offset computation when negative strides are used.
* Partly fixes #636
> Fix use of negative strides in loop filters

- src/decode.rs
- src/levels.rs
- src/recon.rs
We can't just store this as a `bool` directly since it doesn't `impl FromBytes`, so we just provide a getter.
I noticed this in #1084.
> `fn Av1BlockInter1d::mask_sign`: Access as a `bool` to elide bounds checks

- include/dav1d/picture.rs
@fbossen pointed out that the pic allocator can return null for the chroma data, but I had added an `Option<NonNull<_>>::unwrap`.  This changes that to use `NonNull::dangling()` instead, which is valid to use to construct 0-length slices.
> `fn Rav1dPicAllocator::alloc_picture_data`: Allow null and replace with `NonNull::dangling`

- src/decode.rs
- src/refmvs.rs
Mark `decode_b`, `decode_sb`, `rav1d_decode_tile_sbrow`, and `rav1d_decode_frame_main` as safe, putting any unsafe operations in `unsafe` blocks and documenting their safety invariants. For the `bd_fn` calls those should be safe since they're pure Rust calls and just haven't been marked safe. Once they're made safe we can clean up the unnecessary `unsafe` blocks. I also marked `load_tmvs` and `save_tmvs` safe since those wrap the unsafe asm call and handle converting the safe Rust args to the raw pointers that asm needs.
Part of #843.
> `decode.rs`: Mark functions safe and document unsafe operations

- src/ipred.rs
> `fn ipred_{v,h}_rust`: Cleanup and make safe

- src/disjoint_mut.rs
Since `Bounds` represents `start..` and `..` with `usize::MAX` for the end bound, multiplying it is incorrect.  This adds `trait TranslateRange` to do the multiplication on the generic range before converting to `Bounds`.
> `trait TranslateRange`: Replace `fn Bounds::multiply` as `Bounds` uses `usize::MAX` for unknown ends, which can't be multiplied

- src/disjoint_mut.rs
This inlines all of the `fn index`-type methods, allowing the bounds checks to be in the caller so that they can be optimized with knowledge from the caller.  At the same time, the error paths are put in `#[inline(never)]` inner `fn`s so that they don't bloat the code at all.  Then, the `Bounds::from` calls in `fn DisjointMutIndex::get_mut` are replaced with `fn SliceBounds::to_range`, which uses `len` directly instead of `usize::MAX`.  `Bounds::from` first substitutes `usize::MAX` for `len`, and then converts it back, but this conflates a range given as `..usize::MAX`, and thus can't be optimized as well.  Finally, the `start < len` check is redundant when we're already checking that `start <= end` and `end <= len`.  I thought LLVM could optimize this out, but it can't, and `std` does it …
> `fn DisjointMut::index{,_mut}`: Optimize

- include/dav1d/picture.rs
- src/internal.rs
- src/mem.rs
- src/picture.rs
`fn MemPool::pop_init` uses `vec![]` and thus can optimize to `alloc_zeroed`, which lets the OS handle zeroing out pages, which is far faster.  Thus, we can now safely initialize picture data without significant perf overhead, at least for the default pic allocator.
From my basic benchmarking, it appears this eliminates the perf overhead of initialization that I previously saw with `buf.resize(pic_cap, 0)`.  @fbossen and/or @rinon, could you check this more carefully?
> `fn dav1d_default_picture_alloc`: Zero initialize pic data with `fn MemPool::pop_init`

- include/dav1d/picture.rs
- tools/dav1d.c
- tools/dav1d.rs
Designing our APIs to lazily initialize `Rav1dPictureData` memory is quite difficult.  It turns out that there is no performance overhead if new (e.x. not pooled, which are already initialized) picture allocations are zeroed, as the OS can zero it.  From what I can tell, basically every OS (and things like wasm) zero new memory, so this should largely be free/delayed until writes occur, which is what we want.  #1097 changes `rav1d`'s default pic allocator to do this, but requiring it for all pic allocators would allow us to store `u8`s instead of `MaybeUninit<u8>`s.  Leaving things as `MaybeUninit<u8>` makes things much more difficult and unsafe.
The upstream changes to zero memory should be pretty simple (e.x. replacing `malloc` with `calloc`).  chromium uses the default pic allocator, …
> `fn Dav1dPicAllocator::alloc_picture_callback`: Add safety requirement to initialize memory

- include/dav1d/picture.rs
- lib.rs
- src/disjoint_mut.rs
- src/fg_apply.rs
- src/picture.rs
- src/recon.rs
The data ptrs returned through `alloc_picture_callback` are strided (i.e. at the end of the data if the stride is negative).  This means it wouldn't work with `DisjointMut` as is.  To fix this, we calculate the starting ptr and use that as the base for `DisjointMut`.  Then I added another wrapper type around the `DisjointMut<Rav1dPictureDataComponentInner>` to translate the ptrs back to strided ones when methods like `.as_mut_ptr::<BD>()` are called.
Next, I added `fn index{,_mut}` methods to the wrapper type that convert things from the internal `AlignedPixelChunk` (the one with greater alignment) to `BD::Pixel` and does indexing in terms of that.  Note that this depends on #1098, as `MaybeUninit<_>` doesn't `impl AsBytes` (even if we sidestepped this with `unsafe`/unchecked …
> `struct Rav1dPictureDataComponent`: Allow for safe indexing

- src/fg_apply.rs
- src/lf_mask.rs
- src/recon.rs
- src/thread_task.rs
Quite simple; just want to split this out before more important changes.
> `struct Rav1dPictureDataComponent`: Refactor out accesses in each `fn`

- src/mc.rs
- src/recon.rs
We had also changed one of the `isize` args to `usize` for some reason.  I changed it back for the `fn` ptr itself.
This is used with picture data, so I wanted to make this safer first.
> `fn emu_edge`: `wrap_fn_ptr!` it and make call safer

- src/decode.rs
- src/recon.rs
This makes picture data access safe, so now the whole `fn` and its callers can be safe.
> `fn rav1d_backup_ipred_edge`: Make safe

- src/itx.rs
- src/recon.rs
This is used with picture data, so I wanted to make this safer first.
It also removes the `Option`, deduplicates the asm `fn`s declarations vs. assignments, and makes `coeff` a slice.
> `fn itxfm`: `wrap_fn_ptr!` it and make call safer

- src/ipred.rs
- src/recon.rs
I'm trying to pass `Rav1dPictureDataComponent` through here, so I want to make the rest as safe as possible first.
> `fn pal_pred`: Make FFI boundary safer

- src/ipred.rs
> `fn ipred_smooth{,_v,_h}_rust`: Cleanup and make safer

- include/dav1d/picture.rs
- src/fg_apply.rs
- src/ipred.rs
- src/recon.rs
This makes the rest of `fn pal_pred` safe.  `dst` is made safe by adding an extra `FFISafe<Rav1dPictureDataComponent>` arg.  `idx` is made safe by recreating the slice, with the length checked in `fn call`.  Thus, the fallback `fn pal_pred_rust` is now safe, so I marked `fn pal_pred::Fn::call` safe, too (just asserting the asm is safe).
> `fn pal_pred`: Make safe

- src/fg_apply.rs
735033346 caused a failure in the argon tests I didn't catch until I merged #1114.
> `fn rav1d_apply_grain_row`: Fix argon failure caused by 735033346

- Cargo.lock
- Cargo.toml
- src/decode.rs
- src/internal.rs
- src/lib.rs
- src/thread_task.rs
Replaces the task queue with a simpler version that uses a single `Vec` and atomic index fields.
This version should allow us to replace most of the global locking with lock-free iteration.
> Rewrite task queue with safe inner mutability

- src/decode.c
- src/decode.rs
- src/internal.h
- src/internal.rs
- src/lib.c
- src/recon.rs
- src/recon_tmpl.c
Account for chroma subsampling when allocating cbi buffers.
Reduces memory usage (by 3 kB per sb128 for 4:2:0) when decoding streams with subsampled chroma when frame threading is enabled.
> Backport `cbi` buffer optimization from dav1d 1.3.0

- include/dav1d/picture.rs
- src/fg_apply.rs
- src/filmgrain.rs
This replaces the ptr args of `fn fg{y,uv}_32x32xn::Fn::call` with `&Rav1dPictureDataComponent`s, doing the ptr offset calculations inside the `fn`.  This prepares things for making the `fn` ptr call pass extra `FFISafe<Rav1dPictureDataComponent>` args to make the fallbacks safe.
Note also that the `src` and `dst` strides have already been asserted to be equal before these `fn`s are called.
> `fn fg{y,uv}_32x32xn::Fn::call`: Make args safe `Rav1dPictureDataComponent`s

- src/filmgrain.rs
- src/ipred.rs
This adds extra `FFISafe<Rav1dPictureDataComponent>` args to the `fn` ptr to make the fallback safe.
> `fn fg{y,uv}_32x32xn_rust`: Make safe

- src/fg_apply.rs
- src/filmgrain.rs
- src/lib.rs
- src/thread_task.rs
This makes the `fn generate_grain_{y,uv}_rust` fallbacks safe, and then marks all callers safe where possible.
* Fixes #856.
* Fixes #858.
Note that for `mod fg_apply` (#856), it is made `#![deny(unsafe_code)]`.  However, for `mod filmgrain` (#858), I didn't add a module-wide `#![deny(unsafe_op_in_unsafe_fn)]`, as I left the `unsafe fn *_neon` asm wrappers, as it's mostly just delegating to the asm `fn`s.  The other few `ptr::add`s are done safely in the fallbacks, so adding `// SAFETY` comments here seems redundant.  The other `unsafe fn *_c_erased` ones are individually marked `#[deny(unsafe_op_in_unsafe_fn)]`, as it makes sense for them.
> `fn generate_grain_{y,uv}_rust`: Make safe

- src/decode.rs
- src/lib.rs
- src/picture.rs
> `mod decode`: Make remaining `fn`s safe

- src/refmvs.rs
* Fixes #1152.
35dd0e9 avoids calculations on `r`s that are not actually passed to the `fn` ptr.  We still create the array of 37 elements, both for the guards and for the raw ptrs, as we can't use `alloca`.  This requires extra zero initialization, but otherwise avoids unneeded calculations.
752ec1d then optimizes this further by making the arrays `MaybeUninit`s.  So now the stack allocation is just a subtraction and no initialization is necessary.  This also means we must call destructors manually, but we can use `mem::needs_drop` to skip this when the guard has no `impl Drop` in release mode (i.e. `!cfg(debug_assertions)`).
In 90a6eb8, I also realized we don't need the extra `rr_len: usize` arg, as `bh4` is the same.
I benchmarked this with `cargo build --release && hyperfine …
> `fn Rav1dRefmvsDSPContext::splat_mv`: Optimize

- src/decode.rs
- src/internal.rs
- src/lib.rs
- src/obu.rs
- src/picture.c
- src/picture.rs
Picture: propagate the new sequence event flag in the next picture if the current one is from a lower layer.
Change type of `max_spatial_id` from `bool` to `u8` to ensure that tests comparing two values of `max_spatial_id` are correct.
> Backport fix for new sequence event flag from dav1d 1.4.0

- src/ipred.rs
- src/recon.rs
This does duplicate the `uv_dst` and `uv_off` variables, but that's because I haven't made `fn hex_dump` safe yet, which is called in some other more complex `fn`s, so I haven't made it safe yet.  Once I make it all safe, the deduplication will be gone.
> `fn cfl_pred`: Make safe w/ extra `FFISafe<Rav1dPictureDataComponent>` arg

- src/itx.rs
- src/recon.rs
This adds 2 extra args to `fn itxfm`.
`coeff_len: u16` is the length of the `coeff` slice to recreate it.  I tried to see if it possible to compute this in `fn itxfm::Fn::call` and slice `coeff` to ensure the length was correct, but that seemed a lot more computationally expensive than just passing an extra arg.  Also, I passed a `u16` since the length fits in that, and smaller args could maybe be combined?  Not sure.
`dst` is the `&Rav1dPictureDataComponent`.  Note that in one call, the `dst` ptr originally passed was an argument to the recursive `fn read_coef_tree`, so it's difficult to get the original `dst_offset`, so for now I just unsafely recomputed it from the `dst` ptr.  Once I make `fn read_coef_tree`, I can fix this.
I also removed/simplified a lot of the macros used in `mod …
> `fn itxfm`: Make safe w/ extra args

- src/ipred_prepare.rs
- src/recon.rs
`fn rav1d_prepare_intra_edges` was already safe since we constructed the slice before calling the `fn`, but the slice construction was `unsafe`, and it was overlapping other `DisjointMut` `&mut` borrows.  This changes it to use `Rav1dPictureDataComponent` and thus be fully safe.
There's some duplication in the callers for the offsets and stuff.  That'll go away as I make more things fully safe regarding picture data.
> `fn rav1d_prepare_intra_edges`: Make data race safe

- include/common/bitdepth.rs
- src/lf_apply.rs
- src/mc.rs
- src/recon.rs
We need this abstraction to add the adapter code in the `fn call`s.
> `mod mc`: Use `wrap_fn_ptr!` on all remaining `fn` ptrs

- include/dav1d/picture.rs
- src/cdef.rs
- src/cdef_apply.rs
`top` is always from another buffer, and `bottom` is sometimes from another buffer, sometimes from a `Rav1dPicture`, so I'm going to do those separately.
> `fn cdef{,_dir}`: Make `dst` arg safe w/ `Rav1dPictureDataComponentOffset`

- src/levels.rs
- src/mc.rs
This also fixes the `fn *bilin*rust`s to have the strides be `isize`s instead of `usize`s.
> `fn {put,prep}{,_scaled}_c_erased`: Make const generic instead of using macros

- src/mc.rs
We had already done this for some of these.  This makes `tmp` a slice in all of them.
> `fn prep_{8tap,bilin}{,_scaled}_rust`: Make `tmp` arg a slice

- include/dav1d/headers.rs
- src/lib.rs
- src/obu.rs
I wanted to look into if some `Option`s could make this nicer, but this is simpler.  I just `#[derive(Default)]`ed everything, even though some of them don't really have a real default.
> `fn parse_frame_hdr`: Make safe with a `..Default::default()`

- src/cdef.rs
This fixes the out-of-bounds bug from #1163 ([CI](https://github.com/memorysafety/rav1d/actions/runs/9378749875/job/25822460121#step:7:3685)).
I guess the CI PR that enabled `--negstride` testing in CI hadn't been rebased into #1163 when it merged, so CI only failed after merging.
> `fn padding`: Fix out-of-bounds bug w/ negative strides from #1163 

- src/lib.rs
The null check is removed since the allocation is now infallible.
The "default allocator now having a cookie" check is moved up to use `validate_input!` instead.
I also changed it to return `EINVAL` instead of `ENOMEM` (different from C), since it's an argument being checked, and there's no out-of-memory error.
Since both are before the `Rav1dContext` exists or is (non-default) initialized,
we don't need to call `close_internal` here, which frees up some other API designs.
> `fn rav1d_open::error`: Remove

- src/refmvs.c
- src/refmvs.rs
Fix buffer overread in `save_tmvs()` asm
The `refmvs_block` struct is only 12 bytes large but it is accessed using 16-byte unaligned loads in asm.
In order to avoid reading past the end of the allocated buffer, it is made slightly larger.
> `mod refmvs`: Backport fix for buffer overread from dav1d 1.4.2

- src/itx.rs
* Last bit of trivial cleanup for #817.
> `itx.rs`: Replace C types with Rust equivalents

- src/ipred.rs
This cleans up `ipred_filter_rust` and makes the helper function `filter_fn` safe. I left most of the pointers within the function as pointers because they will point into `dst` at some point (e.g. it's initialized to `topleft_in`, but in a later loop iteration is changed to point to `dst`), so they couldn't be trivially made safe. It may be possible to make this fully safe once `dst` has been made into a `Rav1dPictureDataComponent` ref.
> `fn ipred_filter_rust`: Cleanup and make safer

- src/decode.rs
- src/internal.h
- src/internal.rs
- src/lf_mask.rs
Ensures that SIMD stores performed by memset() are aligned.
> Backport `lvl` buffer alignment from dav1d 1.4.2

- src/recon.rs
The `goto` here is a bit more complex than just a cleanup block at the end of the function, so I think the generated state machine control flow is pretty much the most reasonable way to represent the necessary control flow. So I've just replaced the `current_block` variable with a cleaner enum that does the same thing.
> `fn decode_coefs`: Cleanup `current_block` control flow

- src/looprestoration.rs
These functions were already safe, just not marked as such.
> `fn rotate_*`: Mark safe

- src/cdf.c
- src/cdf.rs
The intrabc and dmv contexts are never reused between frames.
> Backport `fn {d|r}av1d_cdf_thread_update` simplification from dav1d 1.4.2

- src/cdf.c
- src/cdf.h
- src/cdf.rs
`cdf`: Make `qcat` calculation branchless
> Backport `cdf` optimization from dav1d 1.4.2

- src/decode.rs
- src/internal.rs
- src/lib.rs
- src/obu.rs
- src/picture.rs
- src/thread_task.rs
- tests/seek_stress.rs
- tools/dav1d.rs
Our previous code where we passed a `&Rav1dContext` to the worker threads and mutated the `&mut Rav1dContext` through `DAV1D_API`s like `fn rav1d_flush` was unsound, as we were mutating `Rav1dContext` while a `&Rav1dContext` exists.  This moves all of those fields mutated on the main thread from the `DAV1D_API`s into `Rav1dState`, and then puts `Rav1dState` into a `Mutex` (`.try_lock()`ed) into `Rav1dContext`.  We only need to `.try_lock()` it a few places in the `DAV1D_API`s; otherwise, we can just pass `c: &Rav1dContext, state: &mut Rav1dState` args to most `fn`s.  Now `Rav1dContext` is always accessed through a `&` except during its construction in `fn rav1d_open`.
This also lets us remove the `Mutex` around `cached_error_props` and the `Atomic` around `frame_flags`, since they are now …
> `struct Rav1dState`: Split out the fields of `Rav1dContext` that are mutated on the main thread and put them in a `Mutex`

- include/dav1d/dav1d.rs
- src/c_arc.rs
- src/internal.rs
- src/lib.rs
- src/thread_task.rs
- tests/seek_stress.rs
- tools/dav1d.rs
* Fixes #862 (`Rav1dContext` initialization, which is the last one).
* Fixes #705.
This does a few things to make `fn rav1d_open`, the construction of `Rav1dContext`, and its usage from the main and worker threads, and its `unsafe` conversion from `Dav1dContext`s all safe or as safe as possible (full `// SAFETY` comments for the latter incoming shortly).
Specifically, this first makes the initialization of `Rav1dContext` in `fn rav1d_open` safe (not through a raw ptr).  This necessitates sending a `&Rav1dContext` to the worker threads (as we `unsafe`ly used to do through a raw ptr).  Since the worker threads may outlive both `fn rav1d_open` and `fn rav1d_close`, we change the `Box<Rav1dContext>` to `Arc<Rav1dContext>`.
Since we still need to set `c.tc` after spawning the worker threads, …
> `fn rav1d_open`: Make safe by sending an `Arc<Rav1dContext>` to worker threads

- src/c_arc.rs
- src/lib.rs
- tests/seek_stress.rs
- tools/dav1d.rs
- tools/dav1d_cli_parse.rs
- tools/input/annexb.rs
- tools/input/ivf.rs
- tools/input/section5.rs
- tools/output/md5.rs
- tools/output/null.rs
- tools/output/y4m2.rs
- tools/output/yuv.rs
* Fixes #847.
This marks `mod lib` as `#![deny(unsafe_op_in_unsafe_fn)]` by adding `# Safety` docs and `// SAFETY` comments on all `DAV1D_API`s.
The few Rust `fn`s that remain `unsafe` I added temporary `unsafe {}` blocks and `!#[allow(unsafe_op_in_unsafe_fn)]`s on.
> `mod lib`: Mark `#![deny(unsafe_op_in_unsafe_fn)]` with safety docs and comments

- include/dav1d/headers.rs
- lib.rs
- src/cdef_apply.rs
- src/decode.rs
- src/internal.rs
- src/lf_apply.rs
- src/lf_mask.rs
- src/lib.rs
- src/obu.rs
- src/recon.rs
- src/relaxed_atomic.rs
- src/thread_task.rs
* Fixes #1173.
`RelaxedAtomic` requires `Ordering::Relaxed` loads and stores, disallowing other relaxed ops like `.fetch_or`.  The former are always plain loads and stores, while the latter are contended `lock *` instructions, so this ensures `RelaxedAtomic`s have little to no overhead.  It also makes clear which types are meant to be fully relaxed.
This should fix #1173 because it removes all relaxed `.fetch_*`es and replaces them with `.update`s, which do separate relaxed loads and stores, which don't have overhead.  This may replace an `add` with a load, `add`, and store, for example, but it gets rid of the `lock add`, which can cause contention, so it should generally have little to no overhead over no atomics at all.
> `struct RelaxedAtomic`: Replace `Atomic*`s that use only relaxed ops with `RelaxedAtomic`

- src/lf_apply.rs
- src/loopfilter.rs
This also helps prepare for making `fn loopfilter_sb`'s `lvl` slice safe.
> `fn filter_plane_{cols,rows}_{y,uv}`: Refactor, cleanup, and optimize

- src/cdf.c
- src/cdf.h
- src/cdf.rs
- src/decode.c
- src/decode.rs
Remove separate intra-only `dmv` contexts in `struct CdfContext` and use the regular `mv` contexts for intra frames.
They are mutually exclusive, and the `dmv` contexts were already discarded and replaced with default contexts on frame completion.
> Backport `struct CdfContext` size reduction from dav1d 1.4.2

- Cargo.lock
- Cargo.toml
- rust-toolchain.toml
- src/cpu.rs
- src/decode.rs
- src/disjoint_mut.rs
- src/ipred_prepare.rs
- src/lf_apply.rs
- src/lib.rs
- src/recon.rs
- src/refmvs.rs
- src/thread_task.rs
This lets us make a couple of things safe (`fn <* [T]>::len`), as well as simplify a lot of guard stuff due to lifetime extension.
> `1.79.0`: Update `nightly` to Rust 1.79

- src/looprestoration.rs
- src/lr_apply.rs
Pass the full `DisjointMut` buffer and an `isize` offset into the `loop_restoration_filter` function, then reconstruct the offset in the Rust fallback functions. This makes the Rust fallbacks fully safe.
* Closes #852
> `fn loop_restoration_filter`: Take safe `lpf` arg for Rust fallbacks

- src/looprestoration.rs
The aarch64 functions were already basically clean, minus some redundant type annotations and other minor issues. This PR cleans those up.
> `looprestoration.rs`: Cleanup in aarch64 functions

- src/thread_task.rs
> `fn rav1d_worker_task`: Use `read` instead of `try_read` to fix contention

- src/arm/32/msac.S
- src/arm/64/msac.S
- src/msac.c
- src/msac.rs
- src/x86/msac.asm
Skip the overhead of shifting in ones into the LSB in the common case, that's only required in the EOB padding. In practice this means we only have to invert bits once during the refill process instead of twice in every call to `msac` functions.
Also make some improvements to the refill asm, mainly involving keeping partially inserted bytes at the end instead of clearing them.
NOTE: the original dav1d commit also applies changes to `loongarch` asm that aren't included here.
> Backport `mod msac` improvements from dav1d 1.4.1

- src/arm/64/msac.S
- src/decode.c
- src/decode.rs
- src/msac.h
- src/recon.rs
- src/recon_tmpl.c
- tests/checkasm/msac.c
Various improvements to `msac` functions. `fn {d,r}av1d_msac_decode_symbol_adapt4` cannot be used for 5 possible symbol values anymore.
> Backport `mod msac` improvements from dav1d 1.4.2

- src/lf_apply.rs
This (along with #1193) gets rid of the last bounds checks inside the loops in these `fn`s, which hopefully helps since these `fn`s are hot.
> `fn filter_plane_{cols,rows}_{y,uv}`: Remove last of bounds checks in the loop

- src/cdf.rs
- src/ipred.rs
- src/lf_apply.rs
This is what I meant by https://github.com/memorysafety/rav1d/pull/1105#pullrequestreview-2067487703.
Also, I included a couple of other random little changes.
> `fn splat_dc`: Use `zerocopy` to make the slice casting safe

- src/arm/cpu.c
- src/arm/cpu.h
- src/cpu.h
- src/cpu.rs
- tests/checkasm/checkasm.c
- tools/dav1d_cli_parse.c
- tools/dav1d_cli_parse.rs
Add run-time CPU feature detection for DotProd, i8mm, SVE and SVE2. SVE and SVE2 are AArch64-only features.
> Backport extended arm feature detection from dav1d 1.4.1

- include/dav1d/picture.rs
- src/align.rs
- src/ipred.rs
- src/recon.rs
This makes `fn angular_ipred` and all of its fallbacks fully safe.
For most of these, this was pretty simple, but `fn ipred_filter_rust` was more complex since it uses normal buffers for the first iteration and then switches to `dst: Rav1dPictureDataComponentOffset`.  For the inner of these, I switched to an `if`, which as I explain in the commit 14dde20, I think should be fine perf-wise.
As for the call sites, sometimes and tmp/scratch buffer is passed in instead of an existing `Rav1dPictureDataComponent`, so I added `fn wrap_buf` for this, which safely wraps a `&mut buf`.  Since this is a unique reference, subdividing it further with the `DisjointMut` is sound (normally the buf is owned by the `DisjointMut`, and so is unique that way).
> `fn angular_ipred`: Make safe w/ `Rav1dPictureDataComponentOffset`

- include/common/dump.rs
- src/decode.rs
- src/internal.rs
- src/recon.rs
* Fixes #863.
This makes `fn hex_{,f}dump` safe by splitting it into two versions:
* `fn hex_fdump`: Using slices.
* `fn hex_fdump_pic`: Using `Rav1dPictureDataComponentOffset`.
> `mod dump`: Make safe

- src/align.rs
- src/decode.rs
- src/refmvs.rs
This
* uses `wrap_fn_ptr!` on the `fn` ptrs here.
* splits the fallback `fn`s into clear `fn *_c`s that do all of the `unsafe` conversions, and safe `fn *_rust`s.
* adds some missing `// SAFETY` comments.
> `mod refmvs`: Make safe

- include/dav1d/picture.rs
- src/mc.rs
- src/recon.rs
Make `r#ref` var a `Rav1dPictureDataComponentOffset`, using `fn wrap_buf` for `emu_edge_buf`, and passing it to `fn mc{,t}{,_scaled}::Fn::call`.
To accomodate `emu_edge_buf`, which is `320 * (256 + 7)`, this also introduces `const RAV1D_PICTURE_GUARANTEED_MULTIPLE = 64` (as opposed to `64 * 64`), which is what's checked and `assume`d always.  `RAV1D_PICTURE_MULTIPLE` is still checked for actual `Rav1dPictureData`s.
> `fn mc`: Make `r#ref` var safe w/ `Rav1dPictureDataComponentOffset`

- src/decode.rs
- src/mc.rs
- src/recon.rs
This lets us make `fn {mc,obmc,warp_affine,rav1d_recon_b_inter}` safe, which is a large chunk of safety.  I'll work on the safety of the fallback `fn`s in `mod mc` next.
We're now down to < 200 `unsafe` ops left!  The vast majority (137) in `mod mc`.
> `fn {mc,warp8x8}{,t}{,_scaled}`: Mark asm calls safe with `TODO SAFETY`s

- include/common/bitdepth.rs
- src/mc.rs
This deduplicates the `{rnd,rnd2,clip}` variants of `filter_8tap` and `filter_bilin` into shared methods on `FilterResult`, which also makes it easier to diverge the implementations of `filter_8tap` and `filter_bilin` for `mid: &[i16]` and `src: Rav1dPictureDataComponentOffset`s inputs, which would be trickier to combine under a single generic interface.  I also simplified some stuff with `BD::PREP_BIAS` that was pretty repetitive.
> `fn FilterResult::{rnd,rnd2,clip}`: Replace the `filter_{8tap,bilin}_{rnd,rnd2,clip}` `fn`s with methods on a shared `FilterResult`

- src/mc.rs
This also refactors out `const MID_STRIDE = 128` and makes the `mid` arrays 2D to simplify things.
`fn filter_8tap` also used to negative index, so this shifts things forward by 3 (really it removes the shift forward by 3 elsewhere) so that we only have positive indices.
> `fn filter_{8tap,bilin}_mid`: Separate out safe `mid: &[i16]` versions from the `src: *const BD::Pixel` versions

- include/dav1d/headers.rs
- lib.rs
- src/cdf.rs
- src/decode.rs
- src/env.rs
- src/internal.rs
- src/levels.rs
- src/lf_mask.rs
- src/recon.rs
It also removes some checks from `fn decode_b` and its callees, which is also a hot spot.
> `struct SegmentId`: Add newtype wrapper for `seg_id` that enforces in-bounds

- src/assume.rs
- src/decode.rs
- src/internal.rs
- src/msac.rs
- src/recon.rs
This adds docs to the `mod msac` `fn`s on the range of their args and return values, and for return values, it ensures this by masking them.  This eliminates a bunch of bounds checks in callers, like `fn decode_coefs`.
I also included a couple of other small commits in here; didn't really want to put them all in their own PRs.
> `mod msac`: Document range of values used and returned and mask return values

- include/dav1d/headers.rs
- src/decode.rs
- src/env.rs
This removes a bunch of casts and also moves checks to where the `Rav1dFilterMode`s are first calculated, and where it is deducible that no checks are needed.
> `enum Rav1dFilterMode`: Use instead of `u8`s or `Dav1dFilterMode` in more places

- src/recon.rs
Optimize and remove all of the bounds checks by checking `dir.len()` directly instead of `tx`.
> `fn get_skip_ctx`: Optimize

- lib.rs
- src/in_range.rs
- src/levels.rs
- src/recon.rs
Use it, for now, to optimize `struct SegmentId` (already similarly optimized, but not generically) and `fn get_skip_ctx`'s return value.
Note that we need this for `fn get_skip_ctx` because it is not inlined, and thus the bounds checks using `sctx` aren't removed in `fn decode_coefs`.  It is not inlined because `fn get_skip_ctx` is not `BitDepth`-generic, but `fn decode_coefs` is.  I think `dav1d` still had `fn get_skip_ctx` inlined because it is manually duplicated with the templating system.  But if LLVM thinks it is better not to inline this even with an `#[inline]` or even an `#[inline(always)]`, and we're still able to propagate information through the return type, I'm inclined to leave it un-inlined.
> `struct InRange`: Add type that enforces its value is within a const generic range

- src/cdf.rs
- src/decode.rs
- src/env.rs
- src/itx.rs
- src/levels.rs
- src/lf_mask.rs
- src/qm.rs
- src/recon.rs
- src/refmvs.rs
- src/scan.rs
- src/tables.rs
This makes `TxfmSize` and `RectTxfmSize` into a real `enum`, which eliminates many bounds checks in hot `fn`s like `fn decode_ceofs`.  It also lets us further simplify the `itx` macros and eliminate the distinction between the `R`ect ones.
Note that `TxfmSize` defined the square sizes; these ones are named with an `S` prefix, while the `R`-prefixed `RectTxfmSize` stay `R`-prefixed.
There are a few new places where we have to create `TxfmSize`s using `from_repr` and thus do a bounds check.  These should be pretty cheap, but there are optimizable out, as they ultimately come from `static`/`const` data whos bounds are known but LLVM is not able to deduce them.  This is why I added 7f0cdc2, starting to try to fix this, though it's a little complicated, so I didn't want to …
> `enum TxfmSize`: Make a real `enum`

- lib.rs
- src/log.rs
Remove by replacing the remaining use with a `mem::transmute` from a non-variadic `fn` to a variadic `fn`, as we don't actually use the variadic args, we just need its type.
* Fixes part of #592.
> `#![feature(c_variadic)]`: Remove for the `rav1d` library

- src/arm/32/filmgrain.S
- src/arm/32/filmgrain16.S
- src/arm/64/filmgrain.S
- src/arm/64/filmgrain16.S
- src/arm/filmgrain.h
- src/fg_apply.rs
- src/fg_apply_tmpl.c
- src/filmgrain.h
- src/filmgrain.rs
- src/filmgrain_tmpl.c
- src/thread_task.c
- src/thread_task.rs
Also consistently use named constant instead of magic numbers.
> Backport renaming of `BLOCK_SIZE` to `FG_BLOCK_SIZE` from dav1d 1.3.0

- src/levels.rs
- src/recon.rs
This optimizes `fn get_lo_ctx`.
9d00ae6 optimizes it enough that it is now inlined (it was already `#[inline]`), which enables other optimizations.
a5c6209 makes `stride` a `u8`, which it is in the caller `fn decode_coefs`, and which tells LLVM that `_ * stride` can't overflow, and thus `2 * stride` being in bounds means that `0 * stride` is in bounds, for example.
242065b then pre-indexes `levels` so that there is only one bounds check per branch.  There is still actually another since LLVM does not know that `stride != 0`.  This can be optimized out with more effort in `fn decode_coefs`, as `stride` is ultimately derived from `t_dim.h`, which comes from `static`/`const` data.
> `fn get_lo_ctx`: Optimize

- include/common/bitdepth.rs
- src/levels.rs
- src/recon.rs
This is a combination of mostly cleanups and some optimization, especially things like narrowing variable types, which can help later optimizations I want to do.
> `fn decode_coefs`: Cleanup, especially `decode_coefs_class!`

- src/levels.rs
- src/recon.rs
There are a lot of captured args here, so I first tried a closure. But there is no stable way to mark it `#[inline]`, and it wasn't being inlined, which is crucial, since there's a lot of redundant code for each `TxClass` that needs to be dead-code eliminated. Keeping it as a macro is an option, but it's very annoying since rust-analyzer doesn't really work well inside of it, and so it makes future refactorings and optimizations much harder to do. With a `fn`, I can pass `tx_class` as a const generic macro, ensuring it gets DCEd, and I can mark it `#[inline]`, ensuring it gets inlined (though I did have to repeat the arg list for each separate call).
Also note that I had to move some initialization into the `fn`, both things for the borrowck like `{eob,hi}_cdf`, which had to be …
> `fn decode_coefs_class`: Make a `fn` from a macro

- src/recon.rs
Move the `tok != 0` check before the `*= 0x17ff41` so that `cmov` is used, not a mispredicted branch.
> `fn decode_coefs_class`: Fix branch misprediction

- src/decode.rs
- src/lf_mask.rs
`get_prev_frame_segid` does not need to be inlined and performance is slightly better without it being inlined. `rav1d_create_lf_mask_inter` is inlined by default and performance suffers if it is, so mark it as inline(never).
> `fn {get_prev_frame_segid, rav1d_create_lf_mask_inter}`: Remove inlining

- src/decode.rs
`seq_hdr` is referenced throughout `decode_b`, but creating the reference early avoids unwrap work near its first use site.
> `fn decode_b`: Move `seq_hdr` reference up

- src/lf_apply.rs
Bound check is already elided and modulo operation is superfluous (and potentially costly).
> `fn filter_plane_cols_{y,uv}`: avoid modulo operation

- src/c_arc.rs
- src/decode.rs
- src/msac.rs
This stores a `CArc<[u8]>` in `MsacContext` to safely store the `buf_{pos,end}` lifetime.  The lifetime is tricky to do otherwise since it comes from a `Rav1dData` is passed to multiple threads, and the `Rav1dData` already has a `CArc<[u8]>`.  Thus, we pay `Arc::clone`s on the `CArc::split_at`s introduced here, but hopefully that shouldn't be too expensive.  Furthermore, this lets us keep the data origin in `MsacContext`, which allows us to make #1071 safe, which does negative indexing.  To make that simple, `fn data` and `fn buf_index` can be used.
Since `MsacContext` was passed to asm, it needed to be FFI-safe, but `CArc` and the `Arc` inside of it are not.  To get around this, I renamed it to `MsacAsmContext` and created a new wrapper non-FFI-safe `MsacContext` storing the `CArc`.
`fn …
> `struct MsacContext`: Make data safe

- include/common/dump.rs
- include/dav1d/picture.rs
- lib.rs
- src/cdef.rs
- src/cdef_apply.rs
- src/fg_apply.rs
- src/filmgrain.rs
- src/ipred.rs
- src/ipred_prepare.rs
- src/itx.rs
- src/lf_apply.rs
- src/loopfilter.rs
- src/looprestoration.rs
- src/lr_apply.rs
- src/mc.rs
- src/pic_or_buf.rs
- src/pixels.rs
- src/recon.rs
- src/strided.rs
- src/with_offset.rs
This refactors out the generic `struct WithOffset`, `trait Pixels`, and `trait Strided` from `Rav1dPictureDataComponent{,Offset}` and uses them to implement `enum PicOrBuf`.
> `enum PicOrBuf`: Add `enum` that can be either a pic or buf and refactor out shared code

- src/internal.rs
It is more optimal to `.unwrap_or_default()`, which is a `cmov`, rather than branching to a panic message, which bloats the code a lot.
This reduces stack usage in `fn decode_coefs` by 64 bytes, from 296 to 232.
> `enum TileStateRef`: Manual `impl Atom` instead of `#[derive(Atom)]`ing it, since the derive may panic

- src/recon.rs
> `enum Ac`: Put `qm_tbl: &[u8]` in `Ac::Qm` to avoid `.unwrap()`ing it

- include/common/bitdepth.rs
- src/internal.rs
- src/recon.rs
For the `CfSelect::Task` case, no slicing is done, the array is just used as is.  For the `CfSelect::Frame` case, the `DisjointMut` is sliced to get a `CF_LEN` array.  Then `fn get` and `fn set` can directly index into this array with no bounds checks and no `match`.
> `fn CfSelect::{get,set}`: Remove and replace with direct indexing, slicing once in `fn decode_coefs`

- src/recon.rs
Although the previous code would usually emit branchless `cmov`s, this was not guaranteed and a branch was emitted in one the 16bpc `TxClass`es, causing mispredictions and slowdowns.  This changes the logic to use only bit operations.
This effectively replaces a `test` and `cmov` with a `xor`, `and`, `xor`, which should be similarly efficient.  In the branched case, it is far more performant.
During benchmarking, @fbossen found that this helps on x86 and doesn't hurt on arm.
> `fn decode_coefs_class`: Replace simple branch w/ branchless logic

- src/lf_apply.rs
- src/mc.rs
- src/pic_or_buf.rs
- src/recon.rs
* Fixes #842.
This pattern can also be used in #1239 and can be used to resolve https://github.com/memorysafety/rav1d/pull/1239#discussion_r1656418583.
> `fn resize`: Make safe w/ `WithOffset<PicOrBuf<AlignedVec64<u8>>>`

- src/decode.rs
- src/lf_apply.rs
- src/loopfilter.rs
- src/recon.rs
- src/thread_task.rs
* Fixes #848.
* Fixes #855.
* Fixes #841.
This does add back some bounds checks since the only and final slicing is done in `fn loopfilter_sb::Fn::call`, which is inside inner loops.  @fbossen, how does this look for perf?
Only 2 `unsafe` ops left (after #1239 is merged, too)!  Though still 122 `unsafe` ops in `neon` `fn`s.
So it turns out the `- b4strideb` in `fn loop_filter_sb128_rust` makes the index negative, so the initial slice needs to be larger.  This is difficult to safely do, though, because all of the other uses of `f.lf.level` do not go through `DisjointMut`'s safe APIs since there were overlapping `&mut`s since indices 0 and 1 are written simultaneously to 2 and 3, and thus were done `unsafe`ly.  This loses the disjointedness checking, though, which is a problem for making …
> `fn loopfilter_sb`: Make safe

- src/c_arc.rs
- src/c_box.rs
Including #1239, this is the last of non-`neon` `unsafe` ops.
> `mod c_{box,arc}`: Make safe

- src/decode.rs
- src/lf_mask.rs
These functions are not inlined in C and removing `read_vartx_tree` inlining speeds up performance on Chimera 8-bit on my 7700X by about 0.7%.
> Remove inlining of `read_vartx_tree` and `rav1d_create_lf_mask_intra`

- Cargo.toml
`debug = true` changes the stack layout and variable spill decisions to ensure that variable contents are available in a debugger for their entire lifetime. This results in different code than a release build, which is not helpful when profiling. Adding line tables only instead still gives source line mapping (when possible) but avoids changes to the machine code.
> Only add line table debug info in `release-with-debug` profile

- src/cdf.c
- src/cdf.h
- src/cdf.rs
- src/decode.rs
Reorder CDF arrays so that copying can be performed in larger blocks.
> Backport `fn {d,r}av1d_cdf_thread_update` code size reduction from dav1d 1.4.2

- src/looprestoration.rs
I wanted to split this out into its own PR since it's diff heavy.
> `mod looprestoration::neon{,_erased}`: Move `neon` `fn`s to their own `mod`

- src/looprestoration.rs
Assuming #1239 is already merged, this removes the last of `unsafe` ops when compiling for `target_arch = "arm"`.  Now only `target_arch = "aarch64"` remains with 110 `unsafe` ops in `mod looprestoration::neon` (`x86`, `x86_64` are already done).
> `mod looprestoration::neon`: (arm32) Make safe

- Cargo.toml
Add a `--profile checked-release`, which is mostly `release`, but with all checks enabled (e.x. `debug-assertions` and `overflow-checks`).  This doesn't need to absolute highest performance, so `opt-level = 2` is done instead of `opt-level = 3`, and `codegen-units = 16` is used as well (the normal `release` default, overridden by us to `codegen-units = 1`).
This is especially helpful when running tests locally under qemu, which can be very slow if running the `opt-dev` profile.  This could also be used in CI instead of `opt-dev`, as `opt-level = 2` should help those run quite a bit faster while still having all checks enabled.
> `Cargo.toml`: Add `profile.checked-release`

- src/lf_mask.rs
This adds some complexity, but it improved performance significantly, especially on intel. Zeroing an entire page of stack with `memset` (which is what was previously happening) is expensive.
> `fn decomp_tx`: Do not zero `txa` before initialization

- src/decode.c
- src/decode.rs
Check for trailing marker/zero bits in tile data
> Backport compliance check from dav1d 1.4.0

- src/cdef.rs
- src/cdef_apply.rs
- src/internal.rs
- src/pixels.rs
- src/recon.rs
- src/thread_task.rs
Makes the remaining Rust fallback in `cdef.rs` safe by passing in additional arguments.
* Closes #850.
* Closes #851.
> `fn cdef`: Make safe

- include/dav1d/headers.rs
- lib.rs
- src/cdf.rs
- src/decode.rs
- src/env.rs
- src/internal.rs
- src/ipred_prepare.rs
- src/itx.rs
- src/levels.rs
- src/lib.rs
- src/msac.rs
- src/obu.rs
- src/recon.rs
- src/refmvs.rs
- src/thread_task.rs
- src/warpmv.rs
- tests/seek_stress.rs
- tools/dav1d.rs
- tools/dav1d_cli_parse.rs
* Fixes `#![allow(non_camel_case_types)]` of #1299.
Supersedes #1301 by just fixing the warnings instead of papering over what appears to be a `rust-analyzer` false positive bug.
> `#![allow(non_camel_case_types)]`: Fix and remove

- lib.rs
- src/cdef.rs
This also fixes `mod cdef`, which still had a couple of asm calls not marked with `unsafe {}` blocks.  This adds them in the same style as the others were done.
> `#![deny(unsafe_op_in_unsafe_fn)]`: Add to whole `librav1d` crate

- include/dav1d/data.rs
- include/dav1d/picture.rs
- lib.rs
- src/align.rs
- src/c_arc.rs
- src/c_box.rs
- src/disjoint_mut.rs
- src/filmgrain.rs
- src/intra_edge.rs
- src/lf_mask.rs
- src/log.rs
- src/msac.rs
- src/refmvs.rs
* Part of #1270.
This adds `#![deny(clippy::undocumented_unsafe_blocks)]` to the `librav1d` crate.  Since we don't yet run `clippy` in CI, this doesn't do anything yet, but that's good, since we can turn that on once we fix all of the errors.  This PR only turns on the lint and fixes the existing safety comments into ones that the lint recognizes.
> `#![deny(clippy::undocumented_unsafe_blocks)]`: Add and fix existing safety comments

- include/dav1d/headers.rs
* Part of #1177.
This makes `Dav1dITUTT35: Send + Sync`.
> `struct ITUTT35PayloadPtr`: Newtype `Dav1dITUTT35::payload` to `unsafe impl Send + Sync` on it

- src/ctx.rs
It's never hit (I tried replacing the `*as_array(buf) = [val; 64]` arm with a panic and the tests all passed). This makes sense because the original C code only had `upto` values of 16 and 32.
> `fn small_memset`: Remove the unused `UP_TO == 64` case

- src/disjoint_mut.rs
Just some unnecessary code I noticed while looking at `disjoint_mut.rs`.
> `mod disjoint_mut`: Remove unused trait bounds and derives

- src/msac.rs
This refactors out `MsacAsmContext::buf_{pos,end}` to `MsacAsmContextBuf` and then `unsafe impl Send + Sync` on it since it stores pointers from the `Send + Sync` `Option<CArc<[u8]>>` in `MsacContext::asm`.  This makes `MsacContext: Send + Sync`.
> `struct MsacAsmContextBuf`: Refactor out and `unsafe impl Send + Sync`

- include/dav1d/picture.rs
- src/c_box.rs
- src/data.rs
- src/lib.rs
- src/log.rs
- src/picture.rs
- tools/dav1d.rs
- tools/seek_stress.rs
This helps simplify some upcoming changes for `Send + Sync` safety.
> `struct *::cookie`: Make `*mut c_void`s into `Option<NonNull<c_void>>`s

- src/cdef_apply.rs
- src/decode.rs
Inlines `backup2x8` which is inlined in C and improves performance slightly.
The `f.a[t.a]` block context reference is constant
throughout `decode_b`, but it appears that the
function is too complex for the optimizer to not
recompute this reference. Making it a local
improves performance measurably (~1% on a Ryzen
7700X for 8-bit Chimera).
> `fn decode_b`: Performance improvements

- src/disjoint_mut.rs
Does this reasoning make sense?
In particular, I'm unsure about the provenanceless thing and data races not leading to memory unsafety.  Is this worth it to say?  Is it worth it to add an `unsafe trait Provenanceless` to ensure such a thing at a more detailed level?  I do think it's an important point that data races won't lead to memory unsafety, though.
> `struct DisjointMut`: `unsafe impl Send + Sync`

- include/dav1d/picture.rs
- lib.rs
- src/c_box.rs
- src/data.rs
- src/lib.rs
- src/log.rs
- src/picture.rs
- src/send_sync_non_null.rs
- tools/dav1d.rs
`SendSyncNonNull` is sound through `unsafe` methods, and we use it here to make the `cookie` fields `Send + Sync`.
> `struct SendSyncNonNull`: Add a `Send + Sync` `NonNull` type

- src/arm/64/mc_dotprod.S
The DotProd/I8MM horizontal and HV/2D subpel filters use -4 offset for sampling instead of -3 to be better aligned in some cases. This resulted in an out of bounds access, which led to crashes.
This is backported from dav1d 1.4.3.
> AArch64: Fix potential out of bounds access in DotProd H/HV filters

- src/levels.rs
This is a simpler, fully safe alternative to #1331.  It reduces `Av1BlockIntraInter` from 28 to 24 bytes, and `Av1Block` from 36 to 32 bytes, just like #1331.
I haven't checked memory usage, though, since I'm not sure how to do that, but since it reduces the type sizes the same, I assume it would have the same memory savings.
> `enum Av1BlockIntraInter`: Remove `#[repr(C)]`, reducing size by 4 bytes

- Cargo.toml
- build.rs
- src/mc.rs
- tools/Cargo.toml
Adds the `asm_arm64_dotprod` and `asm_arm64_i8mm` features. We previously assumed that dotprod and i8mm were always enabled when building for aarch64 and then disabled at runtime if not supported. We also want to support the configuration where we do not even build the code, so these added features (enabled by default) allow this to be configurable.
> Make dotprod and i8mm configurable features

- src/cdef.rs
- src/pixels.rs
- src/with_offset.rs
* Fixes #1336.
That specific test should pass now.
> `trait Pixels`: Add `fn wrapping_*as_{mut_,}ptr` methods for non-bounds checked versions

- src/lib.rs
- src/obu.rs
Reverts default logging back to stderr and fixes a logging print to match dav1d.
> Make logging match dav1d

- src/align.rs
This is a necessary check for soundness, as demonstrated by the test which can SIGSEGV without the check. Before the check, an overflow in the underlying buffer calculation can create incoherent state where the vector believes in an impossibly large buffer of the item type which is not actually backed by a correctly sized buffer of chunks.
* Closes: #1356
> `fn AlignedVec::resize`: Validate safety requirements, specifically overflow

- src/disjoint_mut.rs
As @Darksonn [pointed out](https://github.com/memorysafety/rav1d/pull/1360#discussion_r1771637705), using `mem::transmute` on an `Arc` is unsound since it's not `#[repr(transparent)]`, and we need to go through `Arc::into_raw` and `Arc::from_raw` with a ptr cast instead.
> `fn mem::transmute`: Replace with sound `Arc::from_raw(Arc::into_raw(…) as *const _)`

- include/dav1d/headers.rs
Found when implementing a Rust API in #1362.
> `const DAV1D_MC_BT2020_NCL`: was defined as `CL`, not `NCL`

- Cargo.lock
- build.rs
- tools/Cargo.toml
- tools/build.rs
@thedataking, I only noticed after you merged #1295 a few things.
This should let us cross-compile from windows, cross-compile to `*-windows-gnu` (I think; the linker wasn't installed so I couldn't test all the way), and print a clear error when trying to cross-compile to `*-windows-msvc`.  It also lets us do full cross-compilation on `rav1d`, as the `snprintf` stuff for windows is only for `rav1d-cli`.
* Fixes #1365.
> `build.rs`: Fix windows cross compilation

- src/align.rs
Turning the pointer of an aligned chunk into a reference to the overlay element type requires us to verify the element type's alignment invariant on the address. This check need not happen dynamically if we can provide a stronger static assertion.
The use of `AlignedVec` is over-aligning the storage with regards to the elements. This guarantees that all aligned block addresses are at least as aligned as required for elements. With this commit we validate that only vectors with appropriate element types can be instantiated. This verifies the constructor instead of the type parameters due to simplicity. Turning the violation into a compile error may be beneficial during development but should not be strictly necessary. Passing through a constructor is a dominator code path of the creation …
> `struct AlignedVec`: Verify alignment for `T`

- src/lib.c
- src/refmvs.c
- src/refmvs.h
- src/refmvs.rs
- src/x86/refmvs.asm
Backport changes in `refmvs` allocation but keep memory buffers separate for `RefMvsFrame::r` and `RefMvsFrame::rp_proj` as they use different data types.
> `mod refmvs`: backport changes from dav1d 1.5.0

- Cargo.lock
- Cargo.toml
- tools/Cargo.toml
* Fixes #1376.
This prepares us for the 1.1.0 release. Let me know if I missed anything else that needs to be changed before we release a new version.
> Bump version numbers to 1.1.0

- .github/workflows/build-and-benchmark-x86.yml
- .github/workflows/build-and-test-aarch64-android.yml
- .github/workflows/build-and-test-aarch64-darwin.yml
- .github/workflows/build-and-test-qemu.yml
- .github/workflows/build-and-test-x86-extra.yml
- .github/workflows/build-and-test-x86.yml
- .github/workflows/cargo-fmt.yml
* Fixes #1391.
`rustup` no longer automatically installs a toolchain in `rust-toolchain.toml`, so we get errors like https://github.com/memorysafety/rav1d/issues/1391 now.  Moreover, we only use the pinned nightly for targets where CPU feature detection is unstable (`arm`, `riscv64`, `riscv32`).  Elsewhere we use `stable` for stability, so it helps to be more explicit about using the `stable` toolchain there.
This also adds some missing `rustup` toolchain caching steps.
Distinguishing between `stable` and the pinned nightly from `rust-toolchain.toml` is also quite tricky, so this switches to using `dtolnay/rust-toolchain` for that, which is also used by many `rust-lang` repos.
This also switches to using a pinned stable version for benchmarking for performance consistency.
Since I'm …
> ci: ensure every CI workflow caches and explicitly installs a `rustup` toolchain

- src/fg_apply.rs
- src/lf_mask.rs
A few `Rav1d*` types were unified with their `Dav1d*` counterparts and thus no longer need to be `.clone()`d and converter.
> perf: remove some redundant clones

- src/recon.rs
The function accesses level pairs (0, 1), (0, 2), (0, 3), (0, 4), (1, 0), (1, 1) and (2, 0) for computing the result.
Notably, it does not access levels(1, 4). However, it does try to bounds check that pair in an attempt to elide other bounds checks.
We can prove statically that access to the required pairs is safe. We cannot statically prove that access to (1, 4) is safe. Doing the maths, I think this is because an access to (1, 4) is not actually guaranteed to be safe.
Stop trying to help the compiler here.
This removes a jump to a bounds check failure handler from both versions of decode_coefs, when compiled on both macOS (Apple Silicon) and Linux x86_64 with rust nightly.
I don't think it makes a major performance difference, but it's nice.
> perf: `fn get_lo_ctx`: elide a bounds check

- src/cdef.rs
- src/with_offset.rs
* Supersedes #1402.
There seems to be a slowdown in some of the Arm asm functions due to increased stack usage in `rav1d_cdef_brow` (`def_filter4_pri_edged_8bpc_neon` is ~20% slower when called from rav1d).
By keeping `WithOffset`s "internal" to the function, LLVM is able to optimize away most of the `alloca`-s (first commit).
After doing that, it seemed that `backup2x8` was still slower when calling `.stride()` (vs. a version which doesn't have the Rust fallback args _at all_), which I think is related to how LLVM optimizes the entire `rav1d_cdef_brow` (second commit).
main:
(`$ cargo asm -p rav1d-cli --bin dav1d --llvm rav1d_cdef_brow 0`)
```llvm
; rav1d::src::cdef_apply::rav1d_cdef_brow
; Function Attrs: nounwind
define internal fastcc void @rav1d::src::cdef_apply::rav1d_cdef_brow(..) …
```
> perf: `fn rav1d_cdef_brow`: reduce stack usage

- src/align.rs
- src/decode.rs
- src/internal.rs
- src/lf_apply.rs
- src/lf_mask.rs
- src/loopfilter.rs
Previously, two adjacent 8-bit stores were done.  By doing them as `u16`s instead of `[u8]`s/`[u8; 2]`s, we can get a single 16-bit store to be emitted instead.
This gets `strh`s emitted instead of the pair of `strb`s previously.
Based on what @iximeow found in https://github.com/iximeow/rav1d/commit/e133a89f9a80bfdb69be9ce3535855ae231d0ff8 and https://github.com/memorysafety/rav1d/pull/1401#discussion_r2096219012.
Before:
```asm
❯ cargo asm -p rav1d --lib --rust rav1d_create_lf_mask_intra --color | rg filter_level -C 10
if start <= end && end <= len {
cmp x13, x12
b.hi .LBB440_79
// /home/khyber/work/rav1d/src/lf_mask.rs : 458
let lvl = &mut *level_cache.index_mut((idx + 0.., ..2));
ldr x12, [x1, #8]
// /home/khyber/.rustup/toolchains/nightly-2025-05-01-aarch64-unknown-linux-gnu/lib/rustl …
```
> perf: `fn rav1d_create_lf_mask_{intra,inter}`: store as `u16`s

- src/include/dav1d/headers.rs
- src/include/dav1d/picture.rs
Pulled out the docs additions from #1439 into its own PR.
> Add some docs on AV1 items

- .github/workflows/build-and-test-qemu.yml
- .github/workflows/build-and-test-x86-extra.yml
- .github/workflows/build-and-test-x86.yml
`awalsh128/cache-apt-pkgs-action@latest` is currently broken (see https://github.com/awalsh128/cache-apt-pkgs-action/issues/163), as it tries to use a `git.io` GitHub URL shortener URL to install `apt-fast`, but GitHub has removed that service.  To get CI working now, this switches to my fork which fixes the issue (https://github.com/awalsh128/cache-apt-pkgs-action/pull/164). Once the issue is fixed upstream, we can switch back.
> ci: switch `awalsh128/cache-apt-pkgs-action@latest` to my own fork to fix `apt-fast` error

- src/data.rs
- src/decode.rs
- src/error.rs
- src/include/dav1d/dav1d.rs
- src/include/dav1d/picture.rs
- src/lib.rs
- src/obu.rs
- src/picture.rs
- src/thread_task.rs
Pulled out the `Rav1dError` changes from #1439 into a separate PR.
> `enum Rav1dError`: rename fields to more Rusty versions and add docs

- src/cdf.rs
- src/include/dav1d/picture.rs
- src/wrap_fn_ptr.rs
This resolves a couple of new warnings that appear when building with newer nightly toolchains.
These warnings don't show up with the toolchain version specified in `rust-toolchain.toml`, but the fixes are fully compatible with it. These changes are purely cosmetic and result in an identical compiled binary.
The first change addresses the `mismatched_lifetime_syntaxes` lint that became enabled by default in nightly [1.89](https://github.com/rust-lang/rust/pull/138677) - this lint suggests making elided lifetimes in return types explicit to avoid ambiguity.
The second change silences a warning about deriving `PartialEq` and `Eq` for the function wrapper `Fn(FnPtr)`, as the address of a given function is not guaranteed to be unique across codegen units.
This was caused by `Fn(FnPtr)` …
> Fix warnings from newer toolchain versions

- src/internal.rs
This seems to have been removed a long time ago in 8f78cfe, but we never realized that it was dead code since it was `pub`. The newly released Rust 1.89 warns about this, however, since it was never constructed either, and our `cargo +stable clippy -- -D warnings` CI step uses the latest stable.
> `struct Rav1dFrameContextTaskThreadPendingTasks`: remove unused code

- src/arm/itx.h
- src/itx.h
- src/x86/itx.h
Splitting out of the large #1438.
> `mod itx`: backport deduplicating `itx` macros

- .github/workflows/build-and-test-aarch64-darwin.yml
Fixes https://github.com/memorysafety/rav1d/actions/runs/18050648613/job/51371714091?pr=1457.
> ci: missed installing `clippy` component on aarch64 darwin CI
